/** Product surface derived from std module export lines.
 *  Only public exports are listed; suite-only helpers are omitted.
 *
 *  Each public export is a Laravel-style reference entry under the site voice
 *  rules: description, call form, parameters, returns, and an Echo example.
 */

/** @deprecated Kept for callers; every module now requires full entries. */
export const stdCoreFullPaths = [
  "std/io",
  "std/str",
  "std/bytes",
  "std/list",
  "std/time",
  "std/math",
] as const;

export type StdCoreFullPath = (typeof stdCoreFullPaths)[number];

export type StdExport = {
  name: string;
  /** Short index line */
  role: string;
  /** How you invoke it after import, e.g. `io.print(value)` or `reflect.KIND_INT` */
  call: string;
  /** Reference description */
  description: string;
  /** Parameter meanings (Laravel-style Parameters section) */
  params: string;
  /** Return value meaning (Laravel-style Return Value section) */
  returns: string;
  /** Concrete Echo usage with import */
  example: string;
};

export type StdModule = {
  /** Import path without leading slash, e.g. std/io */
  path: string;
  /** Final path segment used as the bind name */
  name: string;
  title: string;
  summary: string;
  group: string;
  /** Docs page path under /docs/std/... */
  docsPath: string;
  exports: StdExport[];
};

export const stdModules: StdModule[] = [
  {
    path: "std/io",
    name: "io",
    title: "I/O",
    summary: "Print strings to stdout, log, and stderr.",
    group: "Core",
    docsPath: "/docs/std/io",
    exports: [
      {
        name: "print",
        role: "Write a string to standard output with a newline",
        call: "io.print(value)",
        description: "Writes value as text to standard output, followed by a newline.",
        params: "value: string (or value rendered as text) to write.",
        returns: "None.",
        example: "/ std/io\n\nio.print(\"hello\")",
      },
      {
        name: "log",
        role: "Write a string to the log stream with a newline",
        call: "io.log(value)",
        description:
          "Writes value to the log stream with a newline. Use for diagnostic lines separate from primary program output.",
        params: "value: text to write to the log stream.",
        returns: "None.",
        example: "/ std/io\n\nio.log(\"ready\")",
      },
      {
        name: "eprint",
        role: "Write a string to standard error with a newline",
        call: "io.eprint(value)",
        description:
          "Writes value to standard error with a newline. Use for error messages that should stay off stdout.",
        params: "value: text to write to stderr.",
        returns: "None.",
        example: "/ std/io\n\nio.eprint(\"failed\")",
      }
    ],
  },
  {
    path: "std/str",
    name: "str",
    title: "Strings",
    summary: "String conversion, text helpers, and number parse.",
    group: "Core",
    docsPath: "/docs/std/str",
    exports: [
      {
        name: "from_int",
        role: "Integer to decimal string",
        call: "str.from_int(n)",
        description: "Converts an integer to its decimal string form.",
        params: "n: integer to convert.",
        returns: "Decimal string for n.",
        example: "/ std/io\n/ std/str\n\nio.print(str.from_int(42))",
      },
      {
        name: "from_float",
        role: "Float to string",
        call: "str.from_float(n)",
        description: "Converts a float to a string.",
        params: "n: float to convert.",
        returns: "String form of n.",
        example: "/ std/io\n/ std/str\n\nio.print(str.from_float(<f64>3.14))",
      },
      {
        name: "from_bytes",
        role: "UTF-8 decode bytes to string (lossy)",
        call: "str.from_bytes(b)",
        description: "Decodes a byte sequence as UTF-8 text. Invalid sequences are handled lossily.",
        params: "b: bytes value to decode.",
        returns: "UTF-8 string decoded from b.",
        example: "/ std/io\n/ std/str\n\nio.print(str.from_bytes(b'hi'))",
      },
      {
        name: "from_duration",
        role: "Duration to human unit string",
        call: "str.from_duration(d)",
        description: "Formats a duration value as a human-readable unit string.",
        params: "d: duration value.",
        returns: "Human-readable duration string.",
        example: "/ std/io\n/ std/str\n\nio.print(str.from_duration(1s))",
      },
      {
        name: "from_locator",
        role: "Locator path or URI to string",
        call: "str.from_locator(loc)",
        description: "Converts a locator (path or URI) to its string form.",
        params: "loc: locator value.",
        returns: "String form of the locator.",
        example: "/ std/io\n/ std/str\n\nio.print(str.from_locator(p'/tmp/x'))",
      },
      {
        name: "from_debug",
        role: "Shallow debug text for any value",
        call: "str.from_debug(v)",
        description: "Returns shallow debug text for any value (REPL bare-expr display and diagnostics).",
        params: "v: any value.",
        returns: "Debug text string.",
        example: "/ std/io\n/ std/str\n\nio.print(str.from_debug([1, 2]))",
      },
      {
        name: "len",
        role: "Length in UTF-8 bytes",
        call: "str.len(s)",
        description: "Returns the length of a string in UTF-8 bytes (same index space as get and slice).",
        params: "s: string value.",
        returns: "Byte length of s as an integer.",
        example: "/ std/io\n/ std/str\n\nio.print(str.from_int(str.len(\"hi\")))",
      },
      {
        name: "is_empty",
        role: "True when the string is empty",
        call: "str.is_empty(s)",
        description: "Reports whether a string has length zero.",
        params: "s: string value.",
        returns: "Boolean.",
        example: "/ std/str\n\n$ empty = str.is_empty(\"\")",
      },
      {
        name: "cat",
        role: "Concatenate two strings",
        call: "str.cat(a, b)",
        description: "Concatenates two strings.",
        params: "a: left string. b: right string.",
        returns: "Concatenated string a then b.",
        example: "/ std/io\n/ std/str\n\nio.print(str.cat(\"hel\", \"lo\"))",
      },
      {
        name: "contains",
        role: "True when hay contains needle",
        call: "str.contains(hay, needle)",
        description: "Reports whether hay contains needle as a substring.",
        params: "hay: string to search. needle: substring to find.",
        returns: "Boolean.",
        example: "/ std/str\n\n$ ok = str.contains(\"hello\", \"ell\")",
      },
      {
        name: "starts_with",
        role: "True when string starts with prefix",
        call: "str.starts_with(s, prefix)",
        description: "Reports whether s begins with prefix.",
        params: "s: string. prefix: expected prefix.",
        returns: "Boolean.",
        example: "/ std/str\n\n$ ok = str.starts_with(\"hello\", \"he\")",
      },
      {
        name: "ends_with",
        role: "True when string ends with suffix",
        call: "str.ends_with(s, suffix)",
        description: "Reports whether s ends with suffix.",
        params: "s: string. suffix: expected suffix.",
        returns: "Boolean.",
        example: "/ std/str\n\n$ ok = str.ends_with(\"hello\", \"lo\")",
      },
      {
        name: "get",
        role: "UTF-8 byte at index (result-shaped)",
        call: "str.get(s, i)",
        description:
          "Result-shaped access: ok is the UTF-8 byte at index i as ui8; error is \"out of bounds\". Indices match str.len (byte length).",
        params: "s: string. i: zero-based UTF-8 byte index.",
        returns: "Result. Ok arm: byte as ui8. Err arm: \"out of bounds\".",
        example: "/ std/io\n/ std/str\n\n| str.get(\"AB\", 1) {\n    $ b {\n        io.print(str.from_int(b))\n    }\n    ! e {\n        io.print(e)\n    }\n}",
      },
      {
        name: "slice",
        role: "UTF-8 byte slice [start, end) (result-shaped)",
        call: "str.slice(s, start, end)",
        description:
          "Result-shaped half-open UTF-8 byte range [start, end). Error is \"out of bounds\". Prefer char-safe bounds for non-ASCII.",
        params: "s: string. start: inclusive byte index. end: exclusive byte index.",
        returns: "Result. Ok arm: sliced string. Err arm: \"out of bounds\".",
        example: "/ std/io\n/ std/str\n\n| str.slice(\"hello\", 1, 4) {\n    $ part {\n        io.print(part)\n    }\n    ! e {\n        io.print(e)\n    }\n}",
      },
      {
        name: "trim",
        role: "Strip leading and trailing ASCII whitespace",
        call: "str.trim(s)",
        description: "Strips leading and trailing ASCII whitespace.",
        params: "s: string to trim.",
        returns: "Trimmed string.",
        example: "/ std/io\n/ std/str\n\nio.print(str.trim(\"  hi  \"))",
      },
      {
        name: "to_lower",
        role: "ASCII lowercase",
        call: "str.to_lower(s)",
        description: "Lowercases ASCII letters in s.",
        params: "s: string.",
        returns: "Lowercased string.",
        example: "/ std/io\n/ std/str\n\nio.print(str.to_lower(\"Hi\"))",
      },
      {
        name: "to_upper",
        role: "ASCII uppercase",
        call: "str.to_upper(s)",
        description: "Uppercases ASCII letters in s.",
        params: "s: string.",
        returns: "Uppercased string.",
        example: "/ std/io\n/ std/str\n\nio.print(str.to_upper(\"Hi\"))",
      },
      {
        name: "split",
        role: "Split on separator into a list of strings",
        call: "str.split(s, sep)",
        description: "Splits s on separator sep.",
        params: "s: string. sep: separator substring.",
        returns: "List of string parts.",
        example: "/ std/str\n\n$ parts = str.split(\"a,b,c\", \",\")",
      },
      {
        name: "replace",
        role: "Replace all occurrences of a substring",
        call: "str.replace(s, from, to)",
        description: "Replaces occurrences of from with to in s.",
        params: "s: string. from: substring to replace. to: replacement.",
        returns: "String after replacements.",
        example: "/ std/io\n/ std/str\n\nio.print(str.replace(\"hello\", \"l\", \"L\"))",
      },
      {
        name: "join",
        role: "Join list of strings with a separator",
        call: "str.join(parts, sep)",
        description: "Joins string parts with separator sep.",
        params: "parts: list of strings. sep: separator between parts.",
        returns: "Joined string.",
        example: "/ std/io\n/ std/str\n\nio.print(str.join([\"a\", \"b\"], \"-\"))",
      },
      {
        name: "repeat",
        role: "Repeat a string n times",
        call: "str.repeat(s, n)",
        description: "Repeats string s exactly n times.",
        params: "s: string. n: non-negative repeat count.",
        returns: "Repeated string.",
        example: "/ std/io\n/ std/str\n\nio.print(str.repeat(\"ab\", 3))",
      },
      {
        name: "parse_int",
        role: "Parse an integer; error on failure",
        call: "str.parse_int(s)",
        description: "Parses a decimal integer string.",
        params: "s: decimal integer text.",
        returns: "Result. Ok arm: integer. Err arm: parse failure message.",
        example: "/ std/io\n/ std/str\n\n| str.parse_int(\"42\") {\n    $ n {\n        io.print(str.from_int(n))\n    }\n    ! e {\n        io.print(e)\n    }\n}",
      },
      {
        name: "parse_float",
        role: "Parse a float; error on failure",
        call: "str.parse_float(s)",
        description: "Parses a floating-point string.",
        params: "s: float text.",
        returns: "Result. Ok arm: float. Err arm: parse failure message.",
        example: "/ std/str\n\n| str.parse_float(\"3.14\") {\n    $ n { }\n    ! e { }\n}",
      }
    ],
  },
  {
    path: "std/bytes",
    name: "bytes",
    title: "Bytes",
    summary: "Byte sequences: length, slice, concat, and conversions.",
    group: "Core",
    docsPath: "/docs/std/bytes",
    exports: [
      {
        name: "len",
        role: "Length in bytes",
        call: "bytes.len(b)",
        description: "Returns the length of a bytes value.",
        params: "b: bytes value.",
        returns: "Integer length.",
        example: "/ std/bytes\n\n$ n = bytes.len(b'hi')",
      },
      {
        name: "is_empty",
        role: "True when empty",
        call: "bytes.is_empty(b)",
        description: "Reports whether a bytes value is empty.",
        params: "b: bytes value.",
        returns: "Boolean.",
        example: "/ std/bytes\n\n$ empty = bytes.is_empty(b'')",
      },
      {
        name: "get",
        role: "Bounds-checked byte access (result-shaped)",
        call: "bytes.get(b, i)",
        description: "Result-shaped: ok is the byte at index i as ui8; error is \"out of bounds\".",
        params: "b: bytes. i: zero-based index.",
        returns: "Result. Ok arm: byte as ui8. Err arm: \"out of bounds\".",
        example: "/ std/bytes\n\n| bytes.get(b'AB', 1) {\n    $ x { }\n    ! e { }\n}",
      },
      {
        name: "slice",
        role: "Half-open range extract (result-shaped)",
        call: "bytes.slice(b, start, end)",
        description: "Result-shaped half-open byte range [start, end). Error is \"out of bounds\".",
        params: "b: bytes. start: inclusive index. end: exclusive index.",
        returns: "Result. Ok arm: sliced bytes. Err arm: \"out of bounds\".",
        example: "/ std/bytes\n\n| bytes.slice(b'hello', 1, 4) {\n    $ part { }\n    ! e { }\n}",
      },
      {
        name: "cat",
        role: "Concatenate two byte sequences",
        call: "bytes.cat(a, b)",
        description: "Concatenates two byte sequences.",
        params: "a: left bytes. b: right bytes.",
        returns: "Concatenated bytes.",
        example: "/ std/bytes\n\n$ c = bytes.cat(b'a', b'b')",
      },
      {
        name: "from_int",
        role: "Pack integer as 8 little-endian bytes",
        call: "bytes.from_int(n)",
        description: "Packs an integer into bytes.",
        params: "n: integer to pack.",
        returns: "Bytes representation.",
        example: "/ std/bytes\n\n$ b = bytes.from_int(42)",
      },
      {
        name: "from_str",
        role: "UTF-8 encode a string to bytes",
        call: "bytes.from_str(s)",
        description: "Encodes a string as UTF-8 bytes.",
        params: "s: string to encode.",
        returns: "UTF-8 bytes.",
        example: "/ std/bytes\n\n$ b = bytes.from_str(\"hi\")",
      }
    ],
  },
  {
    path: "std/list",
    name: "list",
    title: "Lists",
    summary: "List helpers: length, access, sum, and sort.",
    group: "Core",
    docsPath: "/docs/std/list",
    exports: [
      {
        name: "len",
        role: "Element count",
        call: "list.len(xs)",
        description: "Returns the length of a list.",
        params: "xs: list value.",
        returns: "Integer length.",
        example: "/ std/list\n\n$ n = list.len([1, 2, 3])",
      },
      {
        name: "is_empty",
        role: "True when the list is empty",
        call: "list.is_empty(xs)",
        description: "Reports whether a list is empty.",
        params: "xs: list value.",
        returns: "Boolean.",
        example: "/ std/list\n\n$ empty = list.is_empty([])",
      },
      {
        name: "get",
        role: "Bounds-checked element access (result-shaped)",
        call: "list.get(xs, i)",
        description: "Result-shaped: ok is the element at index i; error is \"out of bounds\".",
        params: "xs: list. i: zero-based index.",
        returns: "Result. Ok arm: element. Err arm: \"out of bounds\".",
        example: "/ std/list\n\n| list.get([10, 20], 0) {\n    $ v { }\n    ! e { }\n}",
      },
      {
        name: "contains",
        role: "True when the list contains the value",
        call: "list.contains(xs, x)",
        description: "Reports whether list xs contains value x.",
        params: "xs: list. x: value to find.",
        returns: "Boolean.",
        example: "/ std/list\n\n$ ok = list.contains([1, 2], 2)",
      },
      {
        name: "sum_ints",
        role: "Sum of integer elements",
        call: "list.sum_ints(xs)",
        description: "Sums a list of integers.",
        params: "xs: list of integers.",
        returns: "Integer sum.",
        example: "/ std/list\n\n$ n = list.sum_ints([1, 2, 3])",
      },
      {
        name: "sort_ints",
        role: "Sort integers ascending",
        call: "list.sort_ints(xs)",
        description: "Returns a new list of integers sorted ascending.",
        params: "xs: list of integers.",
        returns: "Sorted integer list.",
        example: "/ std/list\n\n$ ys = list.sort_ints([3, 1, 2])",
      }
    ],
  },
  {
    path: "std/time",
    name: "time",
    title: "Time",
    summary: "Wall clock, sleep, monotonic clock, and format/parse.",
    group: "Core",
    docsPath: "/docs/std/time",
    exports: [
      {
        name: "now_ms",
        role: "Unix epoch milliseconds (UTC wall clock)",
        call: "time.now_ms()",
        description: "Wall-clock milliseconds since the Unix epoch.",
        params: "No parameters.",
        returns: "Integer milliseconds.",
        example: "/ std/time\n\n$ t = time.now_ms()",
      },
      {
        name: "sleep_ms",
        role: "Sleep at least ms milliseconds",
        call: "time.sleep_ms(ms)",
        description:
          "Sleeps at least ms milliseconds. When ms is zero or negative, the call returns immediately.",
        params: "ms: milliseconds to sleep.",
        returns: "None.",
        example: "/ std/time\n\ntime.sleep_ms(1)",
      },
      {
        name: "mono_ms",
        role: "Monotonic milliseconds since process start",
        call: "time.mono_ms()",
        description:
          "Monotonic milliseconds since process start (not wall clock). Useful for measuring intervals.",
        params: "No parameters.",
        returns: "Value produced by the call (see description).",
        example: "/ std/time\n\n$ result = time.mono_ms()",
      },
      {
        name: "format",
        role: "Format wall-ms with a strftime-like pattern",
        call: "time.format(ms, fmt)",
        description: "Formats wall milliseconds with a pattern string.",
        params: "ms: wall milliseconds since epoch. fmt: format pattern string.",
        returns: "Formatted time string.",
        example: "/ std/time\n\n$ s = time.format(0, \"%Y\")",
      },
      {
        name: "parse",
        role: "Parse text with a pattern to wall-ms",
        call: "time.parse(s, fmt)",
        description: "Parses a time string with a format pattern.",
        params: "s: text to parse. fmt: format pattern string.",
        returns: "Result. Ok arm: wall milliseconds. Err arm: parse failure.",
        example: "/ std/time\n\n| time.parse(\"1970\", \"%Y\") {\n    $ ms { }\n    ! e { }\n}",
      }
    ],
  },
  {
    path: "std/math",
    name: "math",
    title: "Math",
    summary: "Integer and floating-point math helpers.",
    group: "Core",
    docsPath: "/docs/std/math",
    exports: [
      {
        name: "abs_i",
        role: "Absolute value of an integer",
        call: "math.abs_i(n)",
        description: "Absolute value of an integer.",
        params: "n: integer.",
        returns: "Non-negative integer.",
        example: "/ std/math\n\n$ n = math.abs_i(-3)",
      },
      {
        name: "min",
        role: "Minimum of two integers",
        call: "math.min(a, b)",
        description: "Returns the smaller of two integers.",
        params: "a, b: integers.",
        returns: "Integer.",
        example: "/ std/math\n\n$ result = math.min(\"a\", \"b\")",
      },
      {
        name: "max",
        role: "Maximum of two integers",
        call: "math.max(a, b)",
        description: "Returns the larger of two integers.",
        params: "a, b: integers.",
        returns: "Integer.",
        example: "/ std/math\n\n$ result = math.max(\"a\", \"b\")",
      },
      {
        name: "sqrt",
        role: "Square root",
        call: "math.sqrt(x)",
        description: "Non-negative square root of float x.",
        params: "x: float.",
        returns: "Float square root.",
        example: "/ std/math\n\n$ y = math.sqrt(<f64>9.0)",
      },
      {
        name: "sin",
        role: "Sine",
        call: "math.sin(x)",
        description: "Sine of angle x measured in radians.",
        params: "x: float radians.",
        returns: "Float sine.",
        example: "/ std/math\n\n$ y = math.sin(<f64>0.0)",
      },
      {
        name: "cos",
        role: "Cosine",
        call: "math.cos(x)",
        description: "Cosine of x radians.",
        params: "x: float radians.",
        returns: "Float cosine.",
        example: "/ std/math\n\n$ y = math.cos(<f64>0.0)",
      },
      {
        name: "tan",
        role: "Tangent",
        call: "math.tan(x)",
        description: "Tangent of x radians.",
        params: "x: float radians.",
        returns: "Float tangent.",
        example: "/ std/math\n\n$ y = math.tan(<f64>0.0)",
      },
      {
        name: "floor",
        role: "Floor",
        call: "math.floor(x)",
        description: "Greatest integer value not greater than x, as float.",
        params: "x: float.",
        returns: "Floored float.",
        example: "/ std/math\n\n$ y = math.floor(<f64>3.7)",
      },
      {
        name: "ceil",
        role: "Ceiling",
        call: "math.ceil(x)",
        description: "Ceiling of x as float: the least integer value greater than or equal to x.",
        params: "x: float.",
        returns: "Ceiling float.",
        example: "/ std/math\n\n$ y = math.ceil(<f64>3.2)",
      },
      {
        name: "abs_f",
        role: "Absolute value of a float",
        call: "math.abs_f(x)",
        description: "Floating-point absolute value.",
        params: "x: float.",
        returns: "Integer.",
        example: "/ std/math\n\n$ result = math.abs_f(3)",
      },
      {
        name: "pow",
        role: "Power",
        call: "math.pow(a, b)",
        description: "Raises a to the power b.",
        params: "a: base float. b: exponent float.",
        returns: "Float power.",
        example: "/ std/math\n\n$ y = math.pow(<f64>2.0, <f64>3.0)",
      }
    ],
  },
  {
    path: "std/bufio",
    name: "bufio",
    title: "Buffered lines",
    summary: "Split text or files into lines.",
    group: "Core",
    docsPath: "/docs/std/bufio",
    exports: [
      {
        name: "lines",
        role: "Split text into lines on newline",
        call: "bufio.lines(s)",
        description: "Splits text into lines on newline characters.",
        params: "s: text to split.",
        returns: "List of line strings without trailing newlines.",
        example: "/ std/bufio\n\n$ lines = bufio.lines(\"a\\nb\\n\")",
      },
      {
        name: "read_lines",
        role: "Read a file and split into lines",
        call: "bufio.read_lines(path)",
        description: "Reads a file and splits it into lines.",
        params: "path: file path as string or locator.",
        returns: "List of line strings from the file.",
        example: "/ std/bufio\n\n$ lines = bufio.read_lines(p'/tmp/lines.txt')",
      }
    ],
  },
  {
    path: "std/test",
    name: "test",
    title: "Testing",
    summary: "Test registration and assertions for xo test.",
    group: "Core",
    docsPath: "/docs/std/test",
    exports: [
      {
        name: "it",
        role: "Register a test case",
        call: "test.it(name, body)",
        description: "Registers a named test case. body is a zero-arg function run by xo test.",
        params: "name: test case name. body: zero-argument function.",
        returns: "None. Registers the case for the runner.",
        example: "/ std/test\n\ntest.it(\"adds\", () {\n    test.eq(1 + 1, 2)\n})",
      },
      {
        name: "eq",
        role: "Assert deep equality",
        call: "test.eq(left, right)",
        description: "Asserts left deep-equals right; fails the current test otherwise.",
        params: "left: left value. right: right value.",
        returns: "None. Fails the current test on mismatch.",
        example: "/ std/test\n\ntest.it(\"eq\", () {\n    test.eq(2, 1 + 1)\n})",
      },
      {
        name: "ne",
        role: "Assert inequality",
        call: "test.ne(left, right)",
        description: "Asserts left is not equal to right.",
        params: "left: left value. right: right value.",
        returns: "None. Fails the current test on unexpected equality.",
        example: "/ std/test\n\ntest.it(\"ne\", () {\n    test.ne(1, 2)\n})",
      },
      {
        name: "true",
        role: "Assert truthy",
        call: "test.true(cond)",
        description: "Asserts cond is true.",
        params: "cond: boolean condition.",
        returns: "None. Fails the current test when cond is false.",
        example: "/ std/test\n\ntest.it(\"true\", () {\n    test.true(1 == 1)\n})",
      },
      {
        name: "false",
        role: "Assert falsey",
        call: "test.false(cond)",
        description: "Asserts cond is false.",
        params: "cond: boolean condition.",
        returns: "None. Fails the current test when cond is true.",
        example: "/ std/test\n\ntest.it(\"false\", () {\n    test.false(1 == 2)\n})",
      },
      {
        name: "fail",
        role: "Fail the current test with a message",
        call: "test.fail(msg)",
        description: "Fails the current test with message msg.",
        params: "msg: failure message.",
        returns: "None. Always fails the current test.",
        example: "/ std/test\n\ntest.it(\"fail\", () {\n    test.fail(\"unreachable\")\n})",
      }
    ],
  },
  {
    path: "std/reflect",
    name: "reflect",
    title: "Reflection",
    summary: "Runtime kind tags for values and collection keys.",
    group: "Core",
    docsPath: "/docs/std/reflect",
    exports: [
      {
        name: "kind",
        role: "Runtime kind tag for a value",
        call: "reflect.kind(v)",
        description: "Returns the runtime kind tag for a value.",
        params: "v: any value.",
        returns: "Integer kind tag (compare with KIND_* constants).",
        example: "/ std/reflect\n\n$ k = reflect.kind(42)",
      },
      {
        name: "kind_name",
        role: "Human-readable kind name",
        call: "reflect.kind_name(v)",
        description: "Returns a human-readable name for the runtime kind of v.",
        params: "v: any value.",
        returns: "Kind name string.",
        example: "/ std/reflect\n\n$ s = reflect.kind_name(42)",
      },
      {
        name: "key_bytes",
        role: "Stable key bytes for map and set hashing",
        call: "reflect.key_bytes(v)",
        description: "Returns a stable key encoding for value v.",
        params: "v: any value.",
        returns: "Key bytes.",
        example: "/ std/reflect\n\n$ b = reflect.key_bytes(\"a\")",
      },
      {
        name: "is_int",
        role: "True when the value kind is int",
        call: "reflect.is_int(v)",
        description: "Reports whether v is an integer.",
        params: "v: any value.",
        returns: "Boolean.",
        example: "/ std/reflect\n\n$ ok = reflect.is_int(42)",
      },
      {
        name: "is_string",
        role: "True when the value kind is string",
        call: "reflect.is_string(v)",
        description: "Reports whether v is a string.",
        params: "v: any value.",
        returns: "Boolean.",
        example: "/ std/reflect\n\n$ ok = reflect.is_string(\"a\")",
      },
      {
        name: "is_bytes",
        role: "True when the value kind is bytes",
        call: "reflect.is_bytes(v)",
        description: "Reports whether v is bytes.",
        params: "v: any value.",
        returns: "Boolean.",
        example: "/ std/reflect\n\n$ ok = reflect.is_bytes(b'a')",
      },
      {
        name: "is_list",
        role: "True when the value kind is list",
        call: "reflect.is_list(v)",
        description: "Reports whether v is a list.",
        params: "v: any value.",
        returns: "Boolean.",
        example: "/ std/reflect\n\n$ ok = reflect.is_list([1])",
      },
      {
        name: "is_float",
        role: "True when the value kind is float",
        call: "reflect.is_float(v)",
        description: "Reports whether v is a float.",
        params: "v: any value.",
        returns: "Boolean.",
        example: "/ std/reflect\n\n$ ok = reflect.is_float(<f64>1.0)",
      },
      {
        name: "is_struct",
        role: "True when the value kind is struct",
        call: "reflect.is_struct(v)",
        description: "Reports whether v is a struct.",
        params: "v: any value.",
        returns: "Boolean.",
        example: "/ std/reflect\n\n$ ok = reflect.is_struct({ x: 1 })",
      },
      {
        name: "KIND_INT",
        role: "Kind tag constant for int values",
        call: "reflect.KIND_INT",
        description: "Kind tag constant for integer values.",
        params: "No parameters. Constant export.",
        returns: "Integer kind tag for ints.",
        example: "/ std/reflect\n\n$ k = reflect.KIND_INT",
      },
      {
        name: "KIND_LIST",
        role: "Kind tag constant for list values",
        call: "reflect.KIND_LIST",
        description: "Kind tag constant for list values.",
        params: "No parameters. Constant export.",
        returns: "Integer kind tag for lists.",
        example: "/ std/reflect\n\n$ k = reflect.KIND_LIST",
      },
      {
        name: "KIND_STRING",
        role: "Kind tag constant for string values",
        call: "reflect.KIND_STRING",
        description: "Kind tag constant for string values.",
        params: "No parameters. Constant export.",
        returns: "Integer kind tag for strings.",
        example: "/ std/reflect\n\n$ k = reflect.KIND_STRING",
      },
      {
        name: "KIND_STRUCT",
        role: "Kind tag constant for struct values",
        call: "reflect.KIND_STRUCT",
        description: "Kind tag constant for struct values.",
        params: "No parameters. Constant export.",
        returns: "Integer kind tag for structs.",
        example: "/ std/reflect\n\n$ k = reflect.KIND_STRUCT",
      },
      {
        name: "KIND_FLOAT",
        role: "Kind tag constant for float values",
        call: "reflect.KIND_FLOAT",
        description: "Kind tag constant for float values.",
        params: "No parameters. Constant export.",
        returns: "Integer kind tag for floats.",
        example: "/ std/reflect\n\n$ k = reflect.KIND_FLOAT",
      },
      {
        name: "KIND_BYTES",
        role: "Kind tag constant for bytes values",
        call: "reflect.KIND_BYTES",
        description: "Kind tag constant for bytes values.",
        params: "No parameters. Constant export.",
        returns: "Integer kind tag for bytes.",
        example: "/ std/reflect\n\n$ k = reflect.KIND_BYTES",
      }
    ],
  },
  {
    path: "std/path",
    name: "path",
    title: "Path",
    summary: "Path join, clean, relative paths, and shallow walk.",
    group: "Files and process",
    docsPath: "/docs/std/path",
    exports: [
      {
        name: "join",
        role: "Join path segments with platform rules",
        call: "path.join(base, rel)",
        description: "Joins base and rel using platform path rules.",
        params: "base: base path. rel: relative segment or path.",
        returns: "Joined path string.",
        example: "/ std/path\n\n$ p = path.join(\"/tmp\", \"a.txt\")",
      },
      {
        name: "is_abs",
        role: "True for absolute paths",
        call: "path.is_abs(p)",
        description: "Reports whether path p is absolute.",
        params: "p: path string.",
        returns: "Boolean true for absolute paths.",
        example: "/ std/path\n\n$ ok = path.is_abs(\"/tmp/a\")",
      },
      {
        name: "file_name",
        role: "Final path component",
        call: "path.file_name(p)",
        description: "Returns the final component of path p.",
        params: "p: path string.",
        returns: "Final path component as a string.",
        example: "/ std/path\n\n$ name = path.file_name(\"/tmp/a.txt\")",
      },
      {
        name: "parent",
        role: "Parent directory path",
        call: "path.parent(p)",
        description: "Returns the parent directory of path p.",
        params: "p: path string.",
        returns: "Parent path string.",
        example: "/ std/path\n\n$ dir = path.parent(\"/tmp/a/b\")",
      },
      {
        name: "extension",
        role: "File extension without the dot",
        call: "path.extension(p)",
        description: "Returns the file extension of path p when present.",
        params: "p: path string.",
        returns: "Extension string, or empty when none.",
        example: "/ std/path\n\n$ ext = path.extension(\"/tmp/a.txt\")",
      },
      {
        name: "clean",
        role: "Clean . and .. path segments",
        call: "path.clean(p)",
        description: "Cleans . and .. segments in a path (POSIX-ish).",
        params: "p: path string.",
        returns: "Cleaned path string.",
        example: "/ std/path\n\n$ p = path.clean(\"/tmp/./a/../b\")",
      },
      {
        name: "rel",
        role: "Relative path from base to target",
        call: "path.rel(base, target)",
        description: "Builds a relative path from base to target.",
        params: "base: base path. target: target path.",
        returns: "Result. Ok arm: relative path string. Err arm: \"rel failed\".",
        example: "/ std/path\n\n| path.rel(\"/tmp\", \"/tmp/a/b\") {\n    $ r { }\n    ! e { }\n}",
      },
      {
        name: "walk",
        role: "List direct children under a directory",
        call: "path.walk(root)",
        description: "Lists paths for direct children of root (non-recursive).",
        params: "root: directory path as string or locator.",
        returns: "List of child path strings.",
        example: "/ std/path\n\n$ kids = path.walk(p'.')",
      }
    ],
  },
  {
    path: "std/fs",
    name: "fs",
    title: "Filesystem",
    summary: "Files, directories, metadata, streaming, and chmod.",
    group: "Files and process",
    docsPath: "/docs/std/fs",
    exports: [
      {
        name: "exists",
        role: "True if the path exists",
        call: "fs.exists(path)",
        description: "Reports whether path exists in the file system.",
        params: "path: file path as string or locator.",
        returns: "Boolean true when the path exists.",
        example: "/ std/fs\n\n$ ok = fs.exists(p'/tmp')",
      },
      {
        name: "is_file",
        role: "True if the path is a regular file",
        call: "fs.is_file(path)",
        description: "Reports whether path names a regular file.",
        params: "path: file path as string or locator.",
        returns: "Boolean true when path is a file.",
        example: "/ std/fs\n\n$ ok = fs.is_file(p'/tmp/a.txt')",
      },
      {
        name: "is_dir",
        role: "True if the path is a directory",
        call: "fs.is_dir(path)",
        description: "Reports whether path names a directory.",
        params: "path: file path as string or locator.",
        returns: "Boolean true when path is a directory.",
        example: "/ std/fs\n\n$ ok = fs.is_dir(p'/tmp')",
      },
      {
        name: "join",
        role: "Join path segments with platform rules",
        call: "fs.join(base, rel)",
        description: "Joins path segments with platform rules (same bridge as path.join).",
        params: "base: base path. rel: relative segment.",
        returns: "Joined path string.",
        example: "/ std/fs\n\n$ p = fs.join(\"/tmp\", \"a.txt\")",
      },
      {
        name: "read",
        role: "Read a whole file as bytes",
        call: "fs.read(path)",
        description: "Reads the entire file at path as bytes. Path accepts a string or locator.",
        params: "path: file path as string or locator.",
        returns: "Bytes of the file contents.",
        example: "/ std/fs\n\n$ data = fs.read(p'/tmp/echo-demo.txt')",
      },
      {
        name: "write",
        role: "Write a whole file",
        call: "fs.write(path, data)",
        description:
          "Writes data to path, creating or replacing the file. Data may be bytes or a string (UTF-8).",
        params: "path: file path as string or locator. data: bytes or string to write.",
        returns: "None on success.",
        example: "/ std/fs\n\nfs.write(p'/tmp/echo-demo.txt', \"hello\\n\")",
      },
      {
        name: "remove",
        role: "Remove a file",
        call: "fs.remove(path)",
        description: "Removes a file at path.",
        params: "path: file path as string or locator.",
        returns: "None.",
        example: "/ std/fs\n\nfs.remove(p'/tmp/echo-demo.txt')",
      },
      {
        name: "copy",
        role: "Copy a file",
        call: "fs.copy(from, to)",
        description: "Copies a file from path to to.",
        params: "path: source path. to: destination path.",
        returns: "None on success.",
        example: "/ std/fs\n\nfs.copy(p'/tmp/a', p'/tmp/b')",
      },
      {
        name: "rename",
        role: "Rename or move a path",
        call: "fs.rename(from, to)",
        description: "Renames or moves a file from path to to.",
        params: "path: source path. to: destination path.",
        returns: "None on success.",
        example: "/ std/fs\n\nfs.rename(p'/tmp/a', p'/tmp/b')",
      },
      {
        name: "create_dir",
        role: "Create a directory",
        call: "fs.create_dir(path)",
        description: "Creates a single directory at path.",
        params: "path: directory path as string or locator.",
        returns: "None on success.",
        example: "/ std/fs\n\nfs.create_dir(p'/tmp/echo-dir')",
      },
      {
        name: "create_dir_all",
        role: "Create a directory tree",
        call: "fs.create_dir_all(path)",
        description: "Creates path and any missing parent directories.",
        params: "path: directory path as string or locator.",
        returns: "None on success.",
        example: "/ std/fs\n\nfs.create_dir_all(p'/tmp/echo/nested')",
      },
      {
        name: "read_dir",
        role: "List directory entry names",
        call: "fs.read_dir(path)",
        description: "Lists immediate child names of a directory.",
        params: "path: directory path as string or locator.",
        returns: "Result. Ok arm: list of entry name strings. Err arm: failure message.",
        example: "/ std/fs\n\n| fs.read_dir(p'.') {\n    $ names { }\n    ! e { }\n}",
      },
      {
        name: "remove_dir",
        role: "Remove an empty directory",
        call: "fs.remove_dir(path)",
        description: "Removes an empty directory at path.",
        params: "path: directory path as string or locator.",
        returns: "None.",
        example: "/ std/fs\n\nfs.remove_dir(p'/tmp/echo-dir')",
      },
      {
        name: "metadata",
        role: "File metadata product",
        call: "fs.metadata(path)",
        description: "Reads metadata for path into a meta product.",
        params: "path: file path as string or locator.",
        returns: "meta product with len, is_file, is_dir, is_symlink, modified_ms.",
        example: "/ std/fs\n\n$ m = fs.metadata(p'/tmp')",
      },
      {
        name: "open",
        role: "Open a file for reading",
        call: "fs.open(path)",
        description: "Opens an existing file for streaming read and write.",
        params: "path: file path as string or locator.",
        returns: "file product with handle and methods read, write, seek, close.",
        example: "/ std/fs\n\n$ f = fs.open(p'/tmp/echo-demo.txt')",
      },
      {
        name: "create",
        role: "Create or truncate a file for writing",
        call: "fs.create(path)",
        description: "Creates or truncates a file for streaming I/O.",
        params: "path: file path as string or locator.",
        returns: "file product with handle and methods.",
        example: "/ std/fs\n\n$ f = fs.create(p'/tmp/echo-new.txt')",
      },
      {
        name: "append",
        role: "Open a file for append",
        call: "fs.append(path)",
        description: "Opens a file for append writes.",
        params: "path: file path as string or locator.",
        returns: "file product opened for append.",
        example: "/ std/fs\n\n$ f = fs.append(p'/tmp/echo-demo.txt')",
      },
      {
        name: "meta",
        role: "Metadata product shape",
        call: "fs.meta",
        description: "Metadata product shape for fs.metadata results.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/fs\n\n; shape: fs.meta\n$ m = fs.metadata(p'/tmp')",
      },
      {
        name: "file",
        role: "Streaming file handle shape",
        call: "fs.file",
        description: "Open file handle shape with read, write, seek, and close methods.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/fs\n\n; shape: fs.file\n$ f = fs.open(p'/tmp/echo-demo.txt')",
      },
      {
        name: "temp_dir",
        role: "System temporary directory path",
        call: "fs.temp_dir()",
        description: "Returns the process temporary directory path.",
        params: "No parameters.",
        returns: "Temp directory path string.",
        example: "/ std/fs\n\n$ t = fs.temp_dir()",
      },
      {
        name: "create_temp",
        role: "Create a temporary path",
        call: "fs.create_temp(prefix)",
        description: "Creates a temporary file and returns its path.",
        params: "No parameters.",
        returns: "Path string of the new temp file.",
        example: "/ std/fs\n\n$ p = fs.create_temp()",
      },
      {
        name: "symlink",
        role: "Create a symbolic link",
        call: "fs.symlink(original, link)",
        description: "Creates a symbolic link at path pointing to target.",
        params: "path: link path. target: link target path.",
        returns: "None on success.",
        example: "/ std/fs\n\nfs.symlink(p'/tmp/link', p'/tmp/a')",
      },
      {
        name: "chmod",
        role: "Set Unix file mode bits",
        call: "fs.chmod(path, mode)",
        description: "Sets permission bits on path.",
        params: "path: file path as string or locator. mode: mode bits.",
        returns: "None.",
        example: "/ std/fs\n\nfs.chmod(p'/tmp/a', 0o644)",
      }
    ],
  },
  {
    path: "std/process",
    name: "process",
    title: "Process",
    summary: "Args, environment, spawn, capture, and process pipes.",
    group: "Files and process",
    docsPath: "/docs/std/process",
    exports: [
      {
        name: "args",
        role: "Process argv as a list of strings",
        call: "process.args()",
        description: "Returns the process argument list. Index 0 is the program name when present.",
        params: "No parameters.",
        returns: "List of argument strings.",
        example: "/ std/process\n\n$ argv = process.args()",
      },
      {
        name: "env",
        role: "Look up an environment variable (option)",
        call: "process.env(name)",
        description: "Looks up an environment variable.",
        params: "name: environment variable name.",
        returns: "Option. Some arm: string value. None arm: variable unset.",
        example: "/ std/process\n\n| process.env(\"PATH\") {\n    $ v { }\n    : { }\n}",
      },
      {
        name: "env_set",
        role: "Set an environment variable",
        call: "process.env_set(name, value)",
        description: "Sets an environment variable for the process.",
        params: "name: variable name. value: string value.",
        returns: "None.",
        example: "/ std/process\n\nprocess.env_set(\"ECHO_DEMO\", \"1\")",
      },
      {
        name: "env_unset",
        role: "Unset an environment variable",
        call: "process.env_unset(name)",
        description: "Removes an environment variable from the process.",
        params: "name: variable name.",
        returns: "None.",
        example: "/ std/process\n\nprocess.env_unset(\"ECHO_DEMO\")",
      },
      {
        name: "exit",
        role: "Terminate with an exit code",
        call: "process.exit(code)",
        description: "Terminates the process with the given status code.",
        params: "code: process exit code.",
        returns: "None. Does not return on success.",
        example: "/ std/process\n\n; process.exit(0)",
      },
      {
        name: "run",
        role: "Spawn and wait for an exit code",
        call: "process.run(program, args)",
        description: "Spawns program with args and waits for exit.",
        params: "program: executable path or name. args: list of argument strings.",
        returns: "Result. Ok arm: integer exit status. Err arm: \"failed to spawn process\".",
        example: "/ std/process\n\n| process.run(\"true\", []) {\n    $ code { }\n    ! e { }\n}",
      },
      {
        name: "run_capture",
        role: "Spawn and capture stdout and stderr",
        call: "process.run_capture(program, args)",
        description: "Spawns program with args, waits, and captures stdout and stderr.",
        params: "program: executable path or name. args: list of argument strings.",
        returns: "Result. Ok arm: product with code, stdout, and stderr. Err arm: \"failed to spawn process\".",
        example: "/ std/process\n\n| process.run_capture(\"echo\", [\"hi\"]) {\n    $ r { }\n    ! e { }\n}",
      },
      {
        name: "run_cwd",
        role: "Spawn with a working directory; capture output",
        call: "process.run_cwd(program, args, cwd)",
        description: "Spawns program with args in working directory cwd and captures output.",
        params: "program: executable. args: argument list. cwd: working directory (empty inherits).",
        returns: "Result. Ok arm: product with code, stdout, stderr. Err arm: \"failed to spawn process\".",
        example: "/ std/process\n\n| process.run_cwd(\"pwd\", [], \".\") {\n    $ r { }\n    ! e { }\n}",
      },
      {
        name: "spawn_pipes",
        role: "Spawn with piped stdin, stdout, and stderr handles",
        call: "process.spawn_pipes(program, args)",
        description: "Spawns program with piped stdin, stdout, and stderr.",
        params: "program: executable. args: argument list.",
        returns: "Result. Ok arm: product with child and pipe handles. Err arm: \"failed to spawn process\".",
        example: "/ std/process\n\n| process.spawn_pipes(\"cat\", []) {\n    $ r { }\n    ! e { }\n}",
      },
      {
        name: "pipe_write",
        role: "Write to a process pipe (stdin)",
        call: "process.pipe_write(pipe, data)",
        description: "Writes data to a child pipe handle.",
        params: "handle: pipe handle. data: bytes or string.",
        returns: "Integer bytes written, or failure status.",
        example: "/ std/process\n\n$ n = process.pipe_write(handle, \"hi\\n\")",
      },
      {
        name: "pipe_read",
        role: "Read from a process pipe (stdout or stderr)",
        call: "process.pipe_read(pipe, limit)",
        description: "Reads bytes from a child pipe handle.",
        params: "handle: pipe handle. limit: maximum bytes.",
        returns: "Bytes read from the pipe.",
        example: "/ std/process\n\n$ b = process.pipe_read(handle, 4096)",
      },
      {
        name: "pipe_close",
        role: "Close one end of a process pipe",
        call: "process.pipe_close(pipe)",
        description: "Closes a child pipe handle.",
        params: "handle: pipe handle.",
        returns: "None.",
        example: "/ std/process\n\nprocess.pipe_close(handle)",
      },
      {
        name: "wait",
        role: "Wait for a child process; returns exit code",
        call: "process.wait(child)",
        description: "Waits for a spawned child to exit.",
        params: "child: child process handle.",
        returns: "Integer exit status.",
        example: "/ std/process\n\n$ code = process.wait(child)",
      }
    ],
  },
  {
    path: "std/os",
    name: "os",
    title: "OS",
    summary: "Process id, working directory, hostname, and platform.",
    group: "Files and process",
    docsPath: "/docs/std/os",
    exports: [
      {
        name: "pid",
        role: "Current process id",
        call: "os.pid()",
        description: "Returns the current process id.",
        params: "No parameters.",
        returns: "Integer process id.",
        example: "/ std/os\n\n$ id = os.pid()",
      },
      {
        name: "cwd",
        role: "Current working directory",
        call: "os.cwd()",
        description: "Returns the current working directory.",
        params: "No parameters.",
        returns: "Working directory path string.",
        example: "/ std/os\n\n$ dir = os.cwd()",
      },
      {
        name: "chdir",
        role: "Change working directory",
        call: "os.chdir(path)",
        description: "Changes the process working directory.",
        params: "path: directory path as string or locator.",
        returns: "None.",
        example: "/ std/os\n\nos.chdir(p'/tmp')",
      },
      {
        name: "hostname",
        role: "Host name string",
        call: "os.hostname()",
        description: "Returns the host name of the machine.",
        params: "No parameters.",
        returns: "Hostname string.",
        example: "/ std/os\n\n$ h = os.hostname()",
      },
      {
        name: "platform",
        role: "OS platform string",
        call: "os.platform()",
        description: "Returns a platform identifier string.",
        params: "No parameters.",
        returns: "Platform string.",
        example: "/ std/os\n\n$ p = os.platform()",
      }
    ],
  },
  {
    path: "std/json",
    name: "json",
    title: "JSON",
    summary: "Parse and stringify JSON product values.",
    group: "Data",
    docsPath: "/docs/std/json",
    exports: [
      {
        name: "parse",
        role: "Parse JSON text to a product value",
        call: "json.parse(s)",
        description: "Parses JSON text into a product value.",
        params: "s: JSON text.",
        returns: "Result. Ok arm: parsed value. Err arm: \"json parse failed\".",
        example: "/ std/json\n\n| json.parse('{\"n\":1}') {\n    $ o { }\n    ! e { }\n}",
      },
      {
        name: "stringify",
        role: "Serialize a product value to JSON text",
        call: "json.stringify(v)",
        description: "Serializes a product value to JSON text.",
        params: "v: product or value to encode.",
        returns: "Result. Ok arm: JSON string. Err arm: \"json stringify failed\".",
        example: "/ std/json\n\n| json.stringify({ n: 1 }) {\n    $ s { }\n    ! e { }\n}",
      }
    ],
  },
  {
    path: "std/encoding/hex",
    name: "hex",
    title: "Hex",
    summary: "Hex encode and decode.",
    group: "Data",
    docsPath: "/docs/std/encoding-hex",
    exports: [
      {
        name: "encode",
        role: "Encode bytes or text to a hex string",
        call: "hex.encode(b)",
        description: "Encodes bytes or text as a hex string.",
        params: "b: bytes or text to encode.",
        returns: "Hex string.",
        example: "/ std/encoding/hex\n\n$ s = hex.encode(b\"hi\")",
      },
      {
        name: "decode",
        role: "Decode a hex string to bytes",
        call: "hex.decode(s)",
        description: "Decodes a hex string to bytes.",
        params: "s: hex text.",
        returns: "Decoded bytes.",
        example: "/ std/encoding/hex\n\n$ b = hex.decode(\"6869\")",
      }
    ],
  },
  {
    path: "std/encoding/base64",
    name: "base64",
    title: "Base64",
    summary: "Base64 encode and decode.",
    group: "Data",
    docsPath: "/docs/std/encoding-base64",
    exports: [
      {
        name: "encode",
        role: "Encode bytes or text to a base64 string",
        call: "base64.encode(b)",
        description: "Encodes bytes or text as base64.",
        params: "b: bytes or text to encode.",
        returns: "Base64 string.",
        example: "/ std/encoding/base64\n\n$ s = base64.encode(b\"hi\")",
      },
      {
        name: "decode",
        role: "Decode a base64 string to bytes",
        call: "base64.decode(s)",
        description: "Decodes base64 text to bytes.",
        params: "s: base64 text.",
        returns: "Decoded bytes.",
        example: "/ std/encoding/base64\n\n$ b = base64.decode(\"aGk=\")",
      }
    ],
  },
  {
    path: "std/encoding/csv",
    name: "csv",
    title: "CSV",
    summary: "Thin CSV line and multi-line helpers.",
    group: "Data",
    docsPath: "/docs/std/encoding-csv",
    exports: [
      {
        name: "parse_line",
        role: "Split one CSV line into fields",
        call: "csv.parse_line(s)",
        description: "Splits one CSV line into fields.",
        params: "s: CSV line text.",
        returns: "List of field strings.",
        example: "/ std/encoding/csv\n\n$ fields = csv.parse_line(\"a,b,c\")",
      },
      {
        name: "parse",
        role: "Parse multi-line CSV into rows",
        call: "csv.parse(s)",
        description: "Parses multi-line CSV text into rows.",
        params: "s: CSV document text.",
        returns: "List of rows (each a list of fields).",
        example: "/ std/encoding/csv\n\n$ rows = csv.parse(\"a,b\\n1,2\\n\")",
      },
      {
        name: "format_line",
        role: "Join fields into a CSV line",
        call: "csv.format_line(fields)",
        description: "Formats a list of fields as one CSV line.",
        params: "fields: list of field strings.",
        returns: "CSV line string.",
        example: "/ std/encoding/csv\n\n$ line = csv.format_line([\"a\", \"b\"])",
      }
    ],
  },
  {
    path: "std/compress/gzip",
    name: "gzip",
    title: "gzip",
    summary: "gzip compress and decompress.",
    group: "Data",
    docsPath: "/docs/std/compress-gzip",
    exports: [
      {
        name: "compress",
        role: "Compress input to gzip bytes",
        call: "gzip.compress(data)",
        description: "Compresses input to gzip bytes.",
        params: "data: bytes or text to compress.",
        returns: "Gzip-compressed bytes.",
        example: "/ std/compress/gzip\n\n$ c = gzip.compress(b\"hello\")",
      },
      {
        name: "decompress",
        role: "Decompress gzip bytes",
        call: "gzip.decompress(data)",
        description: "Decompresses gzip bytes.",
        params: "data: gzip bytes.",
        returns: "Decompressed bytes.",
        example: "/ std/compress/gzip\n\n$ p = gzip.decompress(c)",
      }
    ],
  },
  {
    path: "std/compress/zip",
    name: "zip",
    title: "zip",
    summary: "Single-entry zip pack and unpack.",
    group: "Data",
    docsPath: "/docs/std/compress-zip",
    exports: [
      {
        name: "pack",
        role: "Pack a single named entry into a zip",
        call: "zip.pack(name, data)",
        description: "Packs a single named entry into a zip archive.",
        params: "name: entry name. data: entry bytes.",
        returns: "Zip archive bytes.",
        example: "/ std/compress/zip\n\n$ z = zip.pack(\"a.txt\", b\"hi\")",
      },
      {
        name: "unpack_first",
        role: "Unpack the first zip entry",
        call: "zip.unpack_first(data)",
        description: "Unpacks the first entry from a zip archive.",
        params: "data: zip bytes.",
        returns: "Product with name and data for the first entry.",
        example: "/ std/compress/zip\n\n$ e = zip.unpack_first(z)",
      }
    ],
  },
  {
    path: "std/collections/map",
    name: "map",
    title: "Map",
    summary: "Hash map with mixed keys.",
    group: "Collections",
    docsPath: "/docs/std/collections-map",
    exports: [
      {
        name: "map",
        role: "Map shape with put and get methods",
        call: "map.map",
        description: "Map shape with put and get methods.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/collections/map\n\n; shape: map.map\n$ m = map.make()",
      },
      {
        name: "make",
        role: "Construct an empty map",
        call: "map.make()",
        description: "Creates an empty map.",
        params: "No parameters.",
        returns: "Empty map value.",
        example: "/ std/collections/map\n\n$ m = map.make()",
      },
      {
        name: "from_indexed",
        role: "Build a map from indexed pairs",
        call: "map.from_indexed(ls)",
        description: "Builds a map from an indexed list of pairs.",
        params: "pairs: list of key/value products.",
        returns: "Map value.",
        example: "/ std/collections/map\n\n$ m = map.from_indexed([{ key: \"a\", value: 1 }])",
      }
    ],
  },
  {
    path: "std/collections/set",
    name: "set",
    title: "Set",
    summary: "Hash set with mixed members.",
    group: "Collections",
    docsPath: "/docs/std/collections-set",
    exports: [
      {
        name: "set",
        role: "Set shape with add and has methods",
        call: "set.set",
        description: "Set shape with add and has methods.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/collections/set\n\n; shape: set.set\n$ s = set.make()",
      },
      {
        name: "make",
        role: "Construct an empty set",
        call: "set.make()",
        description: "Creates an empty set.",
        params: "No parameters.",
        returns: "Empty set value.",
        example: "/ std/collections/set\n\n$ s = set.make()",
      },
      {
        name: "from_list",
        role: "Build a set from a list",
        call: "set.from_list(ls)",
        description: "Builds a set from a list of values.",
        params: "xs: list of values.",
        returns: "Set value.",
        example: "/ std/collections/set\n\n$ s = set.from_list([1, 2, 2])",
      }
    ],
  },
  {
    path: "std/collections/queue",
    name: "queue",
    title: "Queue",
    summary: "FIFO queue over a list.",
    group: "Collections",
    docsPath: "/docs/std/collections-queue",
    exports: [
      {
        name: "queue",
        role: "FIFO queue shape",
        call: "queue.queue",
        description: "FIFO queue shape used with queue.make and queue methods.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/collections/queue\n\n; shape: queue.queue\n$ q = queue.make()",
      },
      {
        name: "make",
        role: "Construct an empty queue",
        call: "queue.make()",
        description: "Creates an empty queue.",
        params: "No parameters.",
        returns: "Empty queue value.",
        example: "/ std/collections/queue\n\n$ q = queue.make()",
      }
    ],
  },
  {
    path: "std/collections/hash_table",
    name: "hash_table",
    title: "Hash table",
    summary: "Lower-level hash table.",
    group: "Collections",
    docsPath: "/docs/std/collections-hash_table",
    exports: [
      {
        name: "hash_table",
        role: "Hash table shape",
        call: "hash_table.hash_table",
        description: "Hash table shape used with hash_table.make and table methods.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/collections/hash_table\n\n; shape: hash_table.hash_table\n$ t = hash_table.make()",
      },
      {
        name: "make",
        role: "Construct an empty hash table",
        call: "hash_table.make()",
        description: "Creates an empty hash table.",
        params: "No parameters.",
        returns: "Empty hash table value.",
        example: "/ std/collections/hash_table\n\n$ t = hash_table.make()",
      }
    ],
  },
  {
    path: "std/crypto/hash",
    name: "hash",
    title: "Hash",
    summary: "SipHash, SHA-256, and SHA-512.",
    group: "Crypto and random",
    docsPath: "/docs/std/crypto-hash",
    exports: [
      {
        name: "sha256",
        role: "SHA-256 digest (32 bytes)",
        call: "hash.sha256(data)",
        description: "Computes the SHA-256 digest of data.",
        params: "data: bytes or string input.",
        returns: "32-byte digest.",
        example: "/ std/crypto/hash\n\n$ dig = hash.sha256(b\"abc\")",
      },
      {
        name: "sha512",
        role: "SHA-512 digest (64 bytes)",
        call: "hash.sha512(data)",
        description: "Computes the SHA-512 digest of data.",
        params: "data: bytes or string input.",
        returns: "64-byte digest.",
        example: "/ std/crypto/hash\n\n$ dig = hash.sha512(b\"abc\")",
      },
      {
        name: "sip",
        role: "SipHash-2-4 of a message with k0 and k1 keys",
        call: "hash.sip(k0, k1, msg)",
        description: "Computes a SipHash of data with the given key material.",
        params: "key: key bytes. data: bytes or string input.",
        returns: "Hash bytes.",
        example: "/ std/crypto/hash\n\n$ dig = hash.sip(b\"0123456789abcdef\", b\"abc\")",
      }
    ],
  },
  {
    path: "std/crypto/hmac",
    name: "hmac",
    title: "HMAC",
    summary: "HMAC-SHA256.",
    group: "Crypto and random",
    docsPath: "/docs/std/crypto-hmac",
    exports: [
      {
        name: "sha256",
        role: "HMAC-SHA256 of key and data (32 bytes)",
        call: "hmac.sha256(key, data)",
        description: "Computes HMAC-SHA256 of data under key.",
        params: "key: key bytes. data: bytes or string input.",
        returns: "32-byte MAC.",
        example: "/ std/crypto/hmac\n\n$ mac = hmac.sha256(b\"key\", b\"msg\")",
      }
    ],
  },
  {
    path: "std/crypto/aes_gcm",
    name: "aes_gcm",
    title: "AES-GCM",
    summary: "AES-256-GCM encrypt and decrypt.",
    group: "Crypto and random",
    docsPath: "/docs/std/crypto-aes_gcm",
    exports: [
      {
        name: "encrypt",
        role: "AES-256-GCM encrypt (32-byte key, 12-byte nonce)",
        call: "aes_gcm.encrypt(key, nonce, plaintext)",
        description: "Encrypts plaintext with AES-256-GCM.",
        params: "key: 32-byte key. nonce: 12-byte nonce. plaintext: bytes to encrypt.",
        returns: "Ciphertext bytes including auth tag.",
        example: "/ std/crypto/aes_gcm\n\n$ c = aes_gcm.encrypt(b\"0123456789abcdef0123456789abcdef\", b\"0123456789ab\", b\"hi\")",
      },
      {
        name: "decrypt",
        role: "AES-256-GCM decrypt",
        call: "aes_gcm.decrypt(key, nonce, ciphertext)",
        description: "Decrypts AES-256-GCM ciphertext.",
        params: "key: 32-byte key. nonce: 12-byte nonce. ciphertext: bytes to decrypt.",
        returns: "Plaintext bytes, or failure on auth error.",
        example: "/ std/crypto/aes_gcm\n\n$ p = aes_gcm.decrypt(key, nonce, ciphertext)",
      }
    ],
  },
  {
    path: "std/crypto/random",
    name: "random",
    title: "CSPRNG",
    summary: "Cryptographic random bytes and u64.",
    group: "Crypto and random",
    docsPath: "/docs/std/crypto-random",
    exports: [
      {
        name: "fill",
        role: "Fill n bytes from the CSPRNG",
        call: "random.fill(n)",
        description: "Fills n cryptographically secure random bytes.",
        params: "n: number of bytes.",
        returns: "n random bytes.",
        example: "/ std/crypto/random\n\n$ b = random.fill(16)",
      },
      {
        name: "u64",
        role: "Cryptographic random u64",
        call: "random.u64()",
        description: "Returns a cryptographically secure random u64.",
        params: "No parameters.",
        returns: "Integer random value.",
        example: "/ std/crypto/random\n\n$ n = random.u64()",
      }
    ],
  },
  {
    path: "std/random",
    name: "random",
    title: "PRNG",
    summary: "Seeded non-cryptographic PRNG.",
    group: "Crypto and random",
    docsPath: "/docs/std/random",
    exports: [
      {
        name: "seed",
        role: "Seed the non-crypto PRNG",
        call: "random.seed(s)",
        description: "Seeds the non-crypto PRNG.",
        params: "s: integer seed.",
        returns: "None.",
        example: "/ std/random\n\nrandom.seed(1)",
      },
      {
        name: "u64",
        role: "Next PRNG u64",
        call: "random.u64()",
        description: "Returns the next non-crypto PRNG integer.",
        params: "No parameters.",
        returns: "Integer random value.",
        example: "/ std/random\n\nrandom.seed(1)\n$ n = random.u64()",
      },
      {
        name: "float",
        role: "Next PRNG float in [0, 1)",
        call: "random.float()",
        description: "Returns the next non-crypto PRNG float in [0, 1).",
        params: "No parameters.",
        returns: "Float random value.",
        example: "/ std/random\n\nrandom.seed(1)\n$ x = random.float()",
      }
    ],
  },
  {
    path: "std/log",
    name: "log",
    title: "Logging",
    summary: "Leveled messages and key=value helpers.",
    group: "Crypto and random",
    docsPath: "/docs/std/log",
    exports: [
      {
        name: "emit",
        role: "Emit a message when msg_level meets min_level",
        call: "log.emit(min_level, msg_level, prefix, msg)",
        description: "Emits msg when msg_level meets min_level.",
        params: "min_level: minimum level. msg_level: message level. prefix: prefix string. msg: message body.",
        returns: "None.",
        example: "/ std/log\n\nlog.emit(1, 1, \"app\", \"ready\")",
      },
      {
        name: "debug",
        role: "Emit a debug-level message",
        call: "log.debug(min_level, msg)",
        description: "Emits a debug-level log line.",
        params: "msg: message string.",
        returns: "None.",
        example: "/ std/log\n\nlog.debug(\"trace\")",
      },
      {
        name: "info",
        role: "Emit an info-level message",
        call: "log.info(min_level, msg)",
        description: "Emits an info-level log line with the given message.",
        params: "msg: message string.",
        returns: "None.",
        example: "/ std/log\n\nlog.info(\"ready\")",
      },
      {
        name: "warn",
        role: "Emit a warning-level message",
        call: "log.warn(min_level, msg)",
        description: "Emits a warning-level log line.",
        params: "msg: message string.",
        returns: "None.",
        example: "/ std/log\n\nlog.warn(\"slow\")",
      },
      {
        name: "error",
        role: "Emit an error-level message",
        call: "log.error(min_level, msg)",
        description: "Emits an error-level log line.",
        params: "msg: message string.",
        returns: "None.",
        example: "/ std/log\n\nlog.error(\"failed\")",
      },
      {
        name: "kv",
        role: "Join key=value pairs into a string",
        call: "log.kv(pairs)",
        description: "Formats key-value fields for structured log lines.",
        params: "fields: product of fields to format.",
        returns: "Formatted fields string.",
        example: "/ std/log\n\n$ s = log.kv({ user: \"ada\" })",
      },
      {
        name: "info_kv",
        role: "Info line with key=value pairs",
        call: "log.info_kv(min_level, msg, pairs)",
        description: "Emits an info log line with a message and key-value fields.",
        params: "msg: message string. fields: product of fields.",
        returns: "None.",
        example: "/ std/log\n\nlog.info_kv(\"login\", { user: \"ada\" })",
      }
    ],
  },
  {
    path: "std/net/tcp",
    name: "tcp",
    title: "TCP",
    summary: "TCP listen, connect, read, and write.",
    group: "Network",
    docsPath: "/docs/std/net-tcp",
    exports: [
      {
        name: "conn",
        role: "TCP connection shape",
        call: "tcp.conn",
        description: "TCP connection shape.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/net/tcp\n\n; shape: tcp.conn\n$ conn = tcp.connect(\"127.0.0.1:8080\")",
      },
      {
        name: "listener",
        role: "TCP listener shape",
        call: "tcp.listener",
        description: "TCP listener shape returned by tcp.listen.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/net/tcp\n\n; shape: tcp.listener\n$ listener = tcp.listen(\"127.0.0.1:0\")",
      },
      {
        name: "listen",
        role: "Start listening; failure yields handle 0",
        call: "tcp.listen(addr)",
        description: "Binds a TCP listener on addr.",
        params: "addr: listen address string such as \"127.0.0.1:0\".",
        returns: "Listener product. Check open or handle fields for bind failure.",
        example: "/ std/net/tcp\n\n$ listener = tcp.listen(\"127.0.0.1:0\")",
      },
      {
        name: "connect",
        role: "Connect; failure yields handle 0 or a result error",
        call: "tcp.connect(addr)",
        description: "Connects to a TCP address.",
        params: "addr: remote address string.",
        returns: "Connection product. Check open or handle fields for connect failure.",
        example: "/ std/net/tcp\n\n$ conn = tcp.connect(\"127.0.0.1:8080\")",
      },
      {
        name: "accept",
        role: "Accept a connection; failure yields handle 0",
        call: "tcp.accept(lis)",
        description: "Accepts the next connection on a listener.",
        params: "listener: TCP listener value.",
        returns: "Connection product for the accepted peer.",
        example: "/ std/net/tcp\n\n$ listener = tcp.listen(\"127.0.0.1:0\")\n$ conn = tcp.accept(listener)",
      },
      {
        name: "read",
        role: "Read up to limit bytes",
        call: "tcp.read(c, limit)",
        description: "Reads up to a limit of bytes from a connection.",
        params: "conn: TCP connection. limit: maximum bytes to read.",
        returns: "Bytes read from the connection.",
        example: "/ std/net/tcp\n\n$ data = tcp.read(conn, 4096)",
      },
      {
        name: "write",
        role: "Write bytes or string data",
        call: "tcp.write(c, data)",
        description: "Writes bytes to a connection.",
        params: "conn: TCP connection. data: bytes or string to send.",
        returns: "Integer bytes written, or -1 on failure.",
        example: "/ std/net/tcp\n\n$ n = tcp.write(conn, \"hi\\n\")",
      },
      {
        name: "close",
        role: "Close the resource",
        call: "tcp.close(x)",
        description: "Closes a TCP connection or listener resource.",
        params: "resource: connection or listener to close.",
        returns: "None.",
        example: "/ std/net/tcp\n\ntcp.close(conn)",
      }
    ],
  },
  {
    path: "std/net/udp",
    name: "udp",
    title: "UDP",
    summary: "UDP bind, send, and receive.",
    group: "Network",
    docsPath: "/docs/std/net-udp",
    exports: [
      {
        name: "bind",
        role: "Bind a UDP socket",
        call: "udp.bind(addr)",
        description: "Binds a UDP socket on addr.",
        params: "addr: bind address string.",
        returns: "UDP socket product.",
        example: "/ std/net/udp\n\n$ sock = udp.bind(\"127.0.0.1:0\")",
      },
      {
        name: "send_to",
        role: "Send a datagram to an address",
        call: "udp.send_to(sock, data, addr)",
        description: "Sends a datagram to addr.",
        params: "socket: UDP socket. data: payload. addr: destination address.",
        returns: "Integer bytes sent, or -1 on failure.",
        example: "/ std/net/udp\n\n$ n = udp.send_to(sock, b\"hi\", \"127.0.0.1:9\")",
      },
      {
        name: "recv_from",
        role: "Receive a datagram with sender address",
        call: "udp.recv_from(sock, limit)",
        description: "Receives a datagram and sender metadata.",
        params: "socket: UDP socket. limit: maximum bytes.",
        returns: "Product with data and from address fields.",
        example: "/ std/net/udp\n\n$ msg = udp.recv_from(sock, 4096)",
      },
      {
        name: "close",
        role: "Close the resource",
        call: "udp.close(sock)",
        description: "Closes a UDP socket.",
        params: "socket: UDP socket.",
        returns: "None.",
        example: "/ std/net/udp\n\nudp.close(sock)",
      },
      {
        name: "socket",
        role: "UDP socket shape",
        call: "udp.socket",
        description: "UDP socket shape returned by udp.bind.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/net/udp\n\n; shape: udp.socket\n$ sock = udp.bind(\"127.0.0.1:0\")",
      }
    ],
  },
  {
    path: "std/net/unix",
    name: "unix",
    title: "Unix sockets",
    summary: "Unix domain sockets.",
    group: "Network",
    docsPath: "/docs/std/net-unix",
    exports: [
      {
        name: "listener",
        role: "Unix domain listener shape",
        call: "unix.listener",
        description: "Unix domain listener shape.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/net/unix\n\n; shape: unix.listener\n$ listener = unix.listen(p'/tmp/echo.sock')",
      },
      {
        name: "conn",
        role: "Unix stream connection shape",
        call: "unix.conn",
        description: "Unix domain connection shape.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/net/unix\n\n; shape: unix.conn\n$ conn = unix.connect(p'/tmp/echo.sock')",
      },
      {
        name: "listen",
        role: "Start listening; failure yields handle 0",
        call: "unix.listen(path)",
        description: "Binds a Unix domain listener on path.",
        params: "path: socket path.",
        returns: "Unix listener product.",
        example: "/ std/net/unix\n\n$ listener = unix.listen(p'/tmp/echo.sock')",
      },
      {
        name: "accept",
        role: "Accept a connection; failure yields handle 0",
        call: "unix.accept(lis)",
        description: "Accepts the next Unix domain connection.",
        params: "listener: Unix listener.",
        returns: "Unix connection product.",
        example: "/ std/net/unix\n\n$ conn = unix.accept(listener)",
      },
      {
        name: "connect",
        role: "Connect; failure yields handle 0 or a result error",
        call: "unix.connect(path)",
        description: "Connects to a Unix domain socket path.",
        params: "path: socket path.",
        returns: "Unix connection product.",
        example: "/ std/net/unix\n\n$ conn = unix.connect(p'/tmp/echo.sock')",
      },
      {
        name: "read",
        role: "Read up to limit bytes",
        call: "unix.read(c, limit)",
        description: "Reads bytes from a Unix domain connection.",
        params: "conn: Unix connection. limit: maximum bytes.",
        returns: "Bytes read.",
        example: "/ std/net/unix\n\n$ data = unix.read(conn, 4096)",
      },
      {
        name: "write",
        role: "Write bytes or string data",
        call: "unix.write(c, data)",
        description: "Writes bytes to a Unix domain connection.",
        params: "conn: Unix connection. data: bytes or string.",
        returns: "Integer bytes written, or -1 on failure.",
        example: "/ std/net/unix\n\n$ n = unix.write(conn, \"hi\")",
      },
      {
        name: "close",
        role: "Close the resource",
        call: "unix.close(c)",
        description: "Closes a Unix domain connection or listener.",
        params: "resource: connection or listener.",
        returns: "None.",
        example: "/ std/net/unix\n\nunix.close(conn)",
      }
    ],
  },
  {
    path: "std/net/tls",
    name: "tls",
    title: "TLS",
    summary: "TLS client and server over rustls.",
    group: "Network",
    docsPath: "/docs/std/net-tls",
    exports: [
      {
        name: "listener",
        role: "TLS listener shape",
        call: "tls.listener",
        description: "TLS listener shape returned by tls.listen.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/net/tls\n\n; shape: tls.listener\n$ listener = tls.listen(\"127.0.0.1:0\", cert)",
      },
      {
        name: "conn",
        role: "TLS connection shape",
        call: "tls.conn",
        description: "TLS connection shape.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/net/tls\n\n; shape: tls.conn\n$ conn = tls.connect(\"example.com\", 443)",
      },
      {
        name: "listen",
        role: "Start listening; failure yields handle 0",
        call: "tls.listen(addr)",
        description: "Binds a TLS listener with certificate material.",
        params: "addr: listen address. cert: certificate material.",
        returns: "TLS listener product.",
        example: "/ std/net/tls\n\n$ listener = tls.listen(\"127.0.0.1:0\", cert)",
      },
      {
        name: "accept",
        role: "Accept a connection; failure yields handle 0",
        call: "tls.accept(lis, cert_pem, key_pem)",
        description: "Accepts the next TLS connection on a listener.",
        params: "listener: TLS listener.",
        returns: "TLS connection product.",
        example: "/ std/net/tls\n\n$ conn = tls.accept(listener)",
      },
      {
        name: "connect",
        role: "Connect; failure yields handle 0 or a result error",
        call: "tls.connect(host, port, server_name, ca_pem)",
        description: "Connects a TLS client socket to host:port.",
        params: "host: host name. port: port number.",
        returns: "TLS connection product.",
        example: "/ std/net/tls\n\n$ conn = tls.connect(\"example.com\", 443)",
      },
      {
        name: "read",
        role: "Read up to limit bytes",
        call: "tls.read(c, limit)",
        description: "Reads bytes from a TLS connection.",
        params: "conn: TLS connection. limit: maximum bytes.",
        returns: "Bytes read.",
        example: "/ std/net/tls\n\n$ data = tls.read(conn, 4096)",
      },
      {
        name: "write",
        role: "Write bytes or string data",
        call: "tls.write(c, data)",
        description: "Writes bytes to a TLS connection.",
        params: "conn: TLS connection. data: bytes or string.",
        returns: "Integer bytes written, or -1 on failure.",
        example: "/ std/net/tls\n\n$ n = tls.write(conn, \"hi\")",
      },
      {
        name: "close",
        role: "Close the resource",
        call: "tls.close(c)",
        description: "Closes a TLS connection.",
        params: "conn: TLS connection.",
        returns: "None.",
        example: "/ std/net/tls\n\ntls.close(conn)",
      },
      {
        name: "close_listener",
        role: "Close a TLS listener",
        call: "tls.close_listener(lis)",
        description: "Closes a TLS listener.",
        params: "listener: TLS listener.",
        returns: "None.",
        example: "/ std/net/tls\n\ntls.close_listener(listener)",
      },
      {
        name: "load_pem",
        role: "Load a PEM file as a string",
        call: "tls.load_pem(path)",
        description: "Loads PEM certificate or key material.",
        params: "pem: PEM-encoded text.",
        returns: "Certificate material product.",
        example: "/ std/net/tls\n\n$ cert = tls.load_pem(pem_text)",
      }
    ],
  },
  {
    path: "std/net/dns",
    name: "dns",
    title: "DNS",
    summary: "Host name lookup.",
    group: "Network",
    docsPath: "/docs/std/net-dns",
    exports: [
      {
        name: "lookup",
        role: "Resolve a host name to address strings",
        call: "dns.lookup(host)",
        description: "Resolves a host name to address strings.",
        params: "host: host name.",
        returns: "List of address strings.",
        example: "/ std/net/dns\n\n$ addrs = dns.lookup(\"localhost\")",
      }
    ],
  },
  {
    path: "std/net/url",
    name: "url",
    title: "URL",
    summary: "Parse and format http(s) URLs.",
    group: "Network",
    docsPath: "/docs/std/net-url",
    exports: [
      {
        name: "parse",
        role: "Parse an http(s) URL into product fields",
        call: "url.parse(s)",
        description: "Parses an http(s) URL into product fields.",
        params: "s: URL string.",
        returns: "Product with scheme, host, path, and related fields.",
        example: "/ std/net/url\n\n$ u = url.parse(\"http://example.com/a\")",
      },
      {
        name: "format",
        role: "Build a URL string from scheme, host, port, and path",
        call: "url.format(scheme, host, port, path)",
        description: "Formats a URL product back to a string.",
        params: "u: URL product.",
        returns: "URL string.",
        example: "/ std/net/url\n\n$ s = url.format(u)",
      }
    ],
  },
  {
    path: "std/net/http",
    name: "http",
    title: "HTTP server",
    summary: "HTTP serve loop and connection handling.",
    group: "Network",
    docsPath: "/docs/std/net-http",
    exports: [
      {
        name: "request",
        role: "HTTP request shape (re-export)",
        call: "http.request",
        description: "HTTP request shape (re-export).",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/net/http\n\n; shape: http.request\n$ req = http.parse_request(data)",
      },
      {
        name: "response",
        role: "HTTP response shape (re-export)",
        call: "http.response",
        description: "HTTP response shape (re-export).",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/net/http\n\n; shape: http.response\n$ res = http.text_response(200, \"ok\")",
      },
      {
        name: "server",
        role: "HTTP server shape (re-export)",
        call: "http.server",
        description: "HTTP server shape (re-export).",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/net/http\n\n; shape: http.server\n; use http.serve for a running server",
      },
      {
        name: "text_response",
        role: "Build a text/plain response",
        call: "http.text_response(status, body)",
        description: "Builds a plain-text HTTP response product.",
        params: "status: HTTP status code. body: response body text.",
        returns: "HTTP response product.",
        example: "/ std/net/http\n\n$ res = http.text_response(200, \"ok\")",
      },
      {
        name: "html_response",
        role: "Build a text/html response",
        call: "http.html_response(status, body)",
        description: "Builds an HTML HTTP response product.",
        params: "status: HTTP status code. body: HTML text.",
        returns: "HTTP response product.",
        example: "/ std/net/http\n\n$ res = http.html_response(200, \"<p>ok</p>\")",
      },
      {
        name: "json_response",
        role: "Build an application/json response",
        call: "http.json_response(status, body)",
        description: "Builds a JSON HTTP response product.",
        params: "status: HTTP status code. body: JSON text.",
        returns: "HTTP response product.",
        example: "/ std/net/http\n\n$ res = http.json_response(200, \"{\\\"ok\\\":true}\")",
      },
      {
        name: "parse_request",
        role: "Parse raw HTTP request bytes",
        call: "http.parse_request(raw)",
        description: "Parses raw HTTP request bytes into a request product.",
        params: "data: request bytes.",
        returns: "Request product or failure shape.",
        example: "/ std/net/http\n\n$ req = http.parse_request(b\"GET / HTTP/1.1\\r\\nHost: x\\r\\n\\r\\n\")",
      },
      {
        name: "format_response",
        role: "Format a response as HTTP bytes",
        call: "http.format_response(res)",
        description: "Formats a response product as HTTP bytes.",
        params: "res: HTTP response product.",
        returns: "Response bytes.",
        example: "/ std/net/http\n\n$ b = http.format_response(res)",
      },
      {
        name: "dispatch",
        role: "Dispatch a request to matching routes",
        call: "http.dispatch(routes, req)",
        description: "Dispatches a request to the first matching route handle.",
        params: "req: HTTP request. routes: list of path/handle products.",
        returns: "HTTP response product.",
        example: "/ std/net/http\n\n$ res = http.dispatch(req, routes)",
      },
      {
        name: "handle_connection",
        role: "Handle one HTTP connection",
        call: "http.handle_connection(c, routes)",
        description: "Reads one HTTP request from conn, dispatches routes, and writes the response.",
        params: "conn: TCP connection. routes: list of path/handle products.",
        returns: "None after the response is written.",
        example: "/ std/net/http\n\nhttp.handle_connection(conn, routes)",
      },
      {
        name: "serve",
        role: "Accept loop serving routes",
        call: "http.serve(addr, routes)",
        description: "Serves routes on a TCP address until the process stops.",
        params: "addr: listen address. routes: list of path/handle products.",
        returns: "None under a long-running accept loop.",
        example: "/ std/net/http\n\n$ health = () {\n    ^ http.text_response(200, \"ok\")\n}\nhttp.serve(\"127.0.0.1:8080\", [{ path: \"/health\", handle: health }])",
      }
    ],
  },
  {
    path: "std/net/http_client",
    name: "http_client",
    title: "HTTP client",
    summary: "HTTP and HTTPS client requests.",
    group: "Network",
    docsPath: "/docs/std/net-http_client",
    exports: [
      {
        name: "get",
        role: "HTTP GET over cleartext TCP",
        call: "http_client.get(host, port, path)",
        description: "Performs an HTTP GET over cleartext TCP.",
        params: "host: host name. port: port number. path: request path.",
        returns: "Response product or failure shape (see description).",
        example: "/ std/net/http_client\n\n$ res = http_client.get(\"example.com\", 80, \"/\")",
      },
      {
        name: "request",
        role: "HTTP request with method, headers, and body",
        call: "http_client.request(method, host, port, path, headers, body)",
        description: "Performs an HTTP request over cleartext TCP.",
        params: "host: host name. port: port number. method: HTTP method. path: request path. headers: header product. body: body text.",
        returns: "Response product or failure shape.",
        example: "/ std/net/http_client\n\n$ res = http_client.request(\"example.com\", 80, \"GET\", \"/\", {}, \"\")",
      },
      {
        name: "get_tls",
        role: "HTTPS GET over TLS",
        call: "http_client.get_tls(host, port, path, server_name, ca_pem)",
        description: "Performs an HTTPS GET using TLS.",
        params: "host: host name. port: port number. path: request path.",
        returns: "Response product or failure shape.",
        example: "/ std/net/http_client\n\n$ res = http_client.get_tls(\"example.com\", 443, \"/\")",
      },
      {
        name: "request_tls",
        role: "HTTPS request over TLS",
        call: "http_client.request_tls(method, host, port, path, headers, body, server_name, ca_pem)",
        description: "Performs an HTTPS request using TLS.",
        params: "host: host name. port: port number. method: HTTP method. path: request path. headers: header product. body: body text.",
        returns: "Response product or failure shape.",
        example: "/ std/net/http_client\n\n$ res = http_client.request_tls(\"example.com\", 443, \"GET\", \"/\", {}, \"\")",
      }
    ],
  },
  {
    path: "std/net/request",
    name: "request",
    title: "HTTP request",
    summary: "HTTP request product shape.",
    group: "Network",
    docsPath: "/docs/std/net-request",
    exports: [
      {
        name: "request",
        role: "HTTP request shape and helpers",
        call: "request.request",
        description: "HTTP request shape and helpers.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/net/request\n\n; shape: request.request\n; see std/net/http parse_request",
      }
    ],
  },
  {
    path: "std/net/response",
    name: "response",
    title: "HTTP response",
    summary: "HTTP response product shape.",
    group: "Network",
    docsPath: "/docs/std/net-response",
    exports: [
      {
        name: "response",
        role: "HTTP response shape and helpers",
        call: "response.response",
        description: "HTTP response shape and helpers.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/net/response\n\n; shape: response.response\n; see std/net/http text_response",
      }
    ],
  },
  {
    path: "std/net/server",
    name: "server",
    title: "HTTP server type",
    summary: "HTTP server product shape.",
    group: "Network",
    docsPath: "/docs/std/net-server",
    exports: [
      {
        name: "server",
        role: "HTTP server shape",
        call: "server.server",
        description: "HTTP server shape used with the serve helpers.",
        params: "No parameters. Type or shape export.",
        returns: "Shape export used for literals and methods.",
        example: "/ std/net/server\n\n; shape: server.server\n; see std/net/http serve",
      }
    ],
  },
  {
    path: "std/cli",
    name: "cli",
    title: "CLI flags",
    summary: "Parse flags and positionals from argv.",
    group: "CLI",
    docsPath: "/docs/std/cli",
    exports: [
      {
        name: "parse",
        role: "Parse argv into flags and positionals",
        call: "cli.parse(argv)",
        description: "Parses an argv list into flags and positionals.",
        params: "argv: list of argument strings (often process.args()).",
        returns: "Parsed product with flag and positional fields.",
        example: "/ std/cli\n\n$ parsed = cli.parse([\"--name\", \"ada\", \"file.echo\"])",
      },
      {
        name: "has",
        role: "True if a flag is present",
        call: "cli.has(tokens, name)",
        description: "Reports whether a long flag is present on a parse result.",
        params: "parsed: value from cli.parse. flag: flag name without leading dashes.",
        returns: "Boolean true when the flag is set.",
        example: "/ std/cli\n\n$ parsed = cli.parse([\"--help\"])\n$ on = cli.has(parsed, \"help\")",
      },
      {
        name: "get",
        role: "Get a flag value",
        call: "cli.get(tokens, name)",
        description: "Reads the value of a long flag from a parse result.",
        params: "parsed: value from cli.parse. flag: flag name without leading dashes.",
        returns: "Option. Some arm: flag value string. None arm: flag absent.",
        example: "/ std/cli\n\n$ parsed = cli.parse([\"--name\", \"ada\"])\n| cli.get(parsed, \"name\") {\n    $ v { }\n    : { }\n}",
      },
      {
        name: "positionals",
        role: "Positional arguments list",
        call: "cli.positionals(tokens)",
        description: "Returns positional arguments from a parse result.",
        params: "parsed: value from cli.parse.",
        returns: "List of positional strings.",
        example: "/ std/cli\n\n$ parsed = cli.parse([\"--x\", \"1\", \"a.echo\"])\n$ rest = cli.positionals(parsed)",
      }
    ],
  }
];

export const stdModuleByPath: Record<string, StdModule> = Object.fromEntries(
  stdModules.map((m) => [m.path, m]),
);

export function stdImportLine(m: StdModule): string {
  return `/ ${m.path}`;
}

/** Stable heading title for an export section (used for fragment ids). */
export function stdExportHeading(e: StdExport): string {
  return e.name;
}

/** True when this export has full Laravel-style documentation. */
export function stdExportIsFull(e: StdExport): boolean {
  return Boolean(e.params && e.returns && e.example);
}

/** Every product module requires full per-export docs. */
export function stdModuleRequiresFull(_path: string): boolean {
  return true;
}

/**
 * Validates product std reference completeness.
 * Throws with a detailed message if any export is under-documented.
 */
export function assertStdReferenceComplete(modules: readonly StdModule[] = stdModules): void {
  const problems: string[] = [];

  for (const m of modules) {
    for (const e of m.exports) {
      if (!e.name?.trim()) {
        problems.push(`${m.path}: export missing name`);
        continue;
      }
      if (!e.call?.trim()) {
        problems.push(`${m.path}.${e.name}: missing call form`);
      }
      if (!e.description?.trim()) {
        problems.push(`${m.path}.${e.name}: missing description`);
      }
      if (!e.role?.trim()) {
        problems.push(`${m.path}.${e.name}: missing role`);
      }
      if (!e.params?.trim()) {
        problems.push(`${m.path}.${e.name}: missing parameters`);
      }
      if (!e.returns?.trim()) {
        problems.push(`${m.path}.${e.name}: missing returns`);
      }
      if (!e.example?.trim()) {
        problems.push(`${m.path}.${e.name}: missing example`);
      } else {
        if (!e.example.includes(`/ ${m.path}`)) {
          problems.push(`${m.path}.${e.name}: example must import \`/ ${m.path}\``);
        }
        if (!e.example.includes(e.name) && !e.example.includes(e.call.split("(")[0]!)) {
          problems.push(`${m.path}.${e.name}: example should mention the export`);
        }
      }
    }
  }

  if (problems.length > 0) {
    throw new Error(
      `std reference incomplete (${problems.length}):\n` + problems.slice(0, 40).join("\n"),
    );
  }
}

/** Compact listing still used by the API index overview blocks. */
export function stdExportsListing(m: StdModule): string {
  return m.exports.map((e) => `${e.name}: ${e.call}: ${e.role}`).join("\n");
}

/** Groups in nav order. */
export const stdGroups: { title: string; modules: StdModule[] }[] = [
  { title: "Core", modules: stdModules.filter((m) => m.group === "Core") },
  {
    title: "Files and process",
    modules: stdModules.filter((m) => m.group === "Files and process"),
  },
  { title: "Data", modules: stdModules.filter((m) => m.group === "Data") },
  { title: "Collections", modules: stdModules.filter((m) => m.group === "Collections") },
  {
    title: "Crypto and random",
    modules: stdModules.filter((m) => m.group === "Crypto and random"),
  },
  { title: "Network", modules: stdModules.filter((m) => m.group === "Network") },
  { title: "CLI", modules: stdModules.filter((m) => m.group === "CLI") },
];

/** Total public export count across all product modules. */
export const stdExportCount = stdModules.reduce((n, m) => n + m.exports.length, 0);
