/** Product surface derived from std module export lines.
 *  Only public exports are listed; suite-only helpers are omitted.
 */

export type StdExport = {
  name: string;
  role: string;
};

export type StdModule = {
  /** Import path without leading slash, e.g. std/io */
  path: string;
  /** Final path segment used as the bind name */
  name: string;
  title: string;
  summary: string;
  group: string;
  /** Docs page path under /docs/std/... */
  docsPath: string;
  exports: StdExport[];
};

export const stdModules: StdModule[] = [
  {
    path: "std/io",
    name: "io",
    title: "I/O",
    summary: "Print strings to stdout, log, and stderr.",
    group: "Core",
    docsPath: "/docs/std/io",
    exports: [
      { name: "print", role: "Write a string to standard output with a newline" },
      { name: "log", role: "Write a string to the log stream with a newline" },
      { name: "eprint", role: "Write a string to standard error with a newline" },
    ],
  },
  {
    path: "std/str",
    name: "str",
    title: "Strings",
    summary: "String conversion, text helpers, and number parse.",
    group: "Core",
    docsPath: "/docs/std/str",
    exports: [
      { name: "from_int", role: "Integer to decimal string" },
      { name: "from_float", role: "Float to string" },
      { name: "from_bytes", role: "UTF-8 decode bytes to string (lossy)" },
      { name: "from_duration", role: "Duration to human unit string" },
      { name: "from_locator", role: "Locator path or URI to string" },
      { name: "from_debug", role: "Shallow debug text for any value" },
      { name: "len", role: "Length (bytes for strings/bytes; elements for lists)" },
      { name: "is_empty", role: "True when the value kind is empty" },
      { name: "cat", role: "Concatenate two strings or byte sequences" },
      { name: "contains", role: "True when the value contains the needle" },
      { name: "starts_with", role: "True when the string starts with prefix" },
      { name: "ends_with", role: "True when the string ends with suffix" },
      { name: "get", role: 'result-shaped; UTF-8 **byte** at index as ui8; ! "out of bounds"' },
      {
        name: "slice",
        role: 'result-shaped; UTF-8 **byte** indices [start, end); ! "out of bounds"',
      },
      { name: "trim", role: "Strip leading and trailing ASCII whitespace" },
      { name: "to_lower", role: "ASCII lowercase" },
      { name: "to_upper", role: "ASCII uppercase" },
      { name: "split", role: "Split on separator into a list of strings" },
      { name: "replace", role: "Replace all occurrences of a substring" },
      { name: "join", role: "Join list of strings with a separator" },
      { name: "repeat", role: "Repeat a string n times" },
      { name: "parse_int", role: "Parse an integer; error on failure" },
      { name: "parse_float", role: "Parse a float; error on failure" },
    ],
  },
  {
    path: "std/bytes",
    name: "bytes",
    title: "Bytes",
    summary: "Byte sequences: length, slice, concat, and conversions.",
    group: "Core",
    docsPath: "/docs/std/bytes",
    exports: [
      { name: "len", role: "Length (bytes for strings/bytes; elements for lists)" },
      { name: "is_empty", role: "True when the value kind is empty" },
      { name: "get", role: "Bounds-checked element or byte access (result-shaped)" },
      { name: "slice", role: "Half-open range extract (result-shaped)" },
      { name: "cat", role: "Concatenate two strings or byte sequences" },
      { name: "from_int", role: "Single-byte sequence from an integer" },
      { name: "from_str", role: "UTF-8 encode a string to bytes" },
    ],
  },
  {
    path: "std/list",
    name: "list",
    title: "Lists",
    summary: "List helpers: length, access, sum, and sort.",
    group: "Core",
    docsPath: "/docs/std/list",
    exports: [
      { name: "len", role: "Length (bytes for strings/bytes; elements for lists)" },
      { name: "is_empty", role: "True when the value kind is empty" },
      { name: "get", role: "Bounds-checked element or byte access (result-shaped)" },
      { name: "contains", role: "True when the value contains the needle" },
      { name: "sum_ints", role: "Sum of integer elements" },
      { name: "sort_ints", role: "Sort integers ascending" },
    ],
  },
  {
    path: "std/time",
    name: "time",
    title: "Time",
    summary: "Wall clock, sleep, monotonic clock, and format/parse.",
    group: "Core",
    docsPath: "/docs/std/time",
    exports: [
      { name: "now_ms", role: "Unix epoch milliseconds (UTC wall clock)" },
      { name: "sleep_ms", role: "Sleep at least ms milliseconds" },
      { name: "mono_ms", role: "Monotonic milliseconds since process start" },
      { name: "format", role: "Format wall-ms with a strftime-like pattern" },
      { name: "parse", role: "Parse text with a pattern to wall-ms" },
    ],
  },
  {
    path: "std/math",
    name: "math",
    title: "Math",
    summary: "Integer and floating-point math helpers.",
    group: "Core",
    docsPath: "/docs/std/math",
    exports: [
      { name: "abs_i", role: "Absolute value of an integer" },
      { name: "min", role: "Minimum of two integers" },
      { name: "max", role: "Maximum of two integers" },
      { name: "sqrt", role: "Square root" },
      { name: "sin", role: "Sine" },
      { name: "cos", role: "Cosine" },
      { name: "tan", role: "Tangent" },
      { name: "floor", role: "Floor" },
      { name: "ceil", role: "Ceiling" },
      { name: "abs_f", role: "Absolute value of a float" },
      { name: "pow", role: "Power" },
    ],
  },
  {
    path: "std/bufio",
    name: "bufio",
    title: "Buffered lines",
    summary: "Split text or files into lines.",
    group: "Core",
    docsPath: "/docs/std/bufio",
    exports: [
      { name: "lines", role: "Split text into lines on newline" },
      { name: "read_lines", role: "Read a file and split into lines" },
    ],
  },
  {
    path: "std/test",
    name: "test",
    title: "Testing",
    summary: "Test registration and assertions for xo test.",
    group: "Core",
    docsPath: "/docs/std/test",
    exports: [
      { name: "it", role: "Register a test case" },
      { name: "eq", role: "Assert deep equality" },
      { name: "ne", role: "Assert inequality" },
      { name: "true", role: "Assert truthy" },
      { name: "false", role: "Assert falsey" },
      { name: "fail", role: "Fail the current test with a message" },
    ],
  },
  {
    path: "std/reflect",
    name: "reflect",
    title: "Reflection",
    summary: "Runtime kind tags for values and collection keys.",
    group: "Core",
    docsPath: "/docs/std/reflect",
    exports: [
      { name: "kind", role: "Runtime kind tag for a value" },
      { name: "kind_name", role: "Human-readable kind name" },
      { name: "key_bytes", role: "Stable key bytes for map and set hashing" },
      { name: "is_int", role: "True when the value kind is int" },
      { name: "is_string", role: "True when the value kind is string" },
      { name: "is_bytes", role: "True when the value kind is bytes" },
      { name: "is_list", role: "True when the value kind is list" },
      { name: "is_float", role: "True when the value kind is float" },
      { name: "is_struct", role: "True when the value kind is struct" },
      { name: "KIND_INT", role: "Kind tag constant for int values" },
      { name: "KIND_LIST", role: "Kind tag constant for list values" },
      { name: "KIND_STRING", role: "Kind tag constant for string values" },
      { name: "KIND_STRUCT", role: "Kind tag constant for struct values" },
      { name: "KIND_FLOAT", role: "Kind tag constant for float values" },
      { name: "KIND_BYTES", role: "Kind tag constant for bytes values" },
    ],
  },
  {
    path: "std/path",
    name: "path",
    title: "Path",
    summary: "Path join, clean, relative paths, and shallow walk.",
    group: "Files and process",
    docsPath: "/docs/std/path",
    exports: [
      { name: "join", role: "Join path segments with platform rules" },
      { name: "is_abs", role: "True for absolute paths" },
      { name: "file_name", role: "Final path component" },
      { name: "parent", role: "Parent directory path" },
      { name: "extension", role: "File extension without the dot" },
      { name: "clean", role: "Clean . and .. path segments" },
      { name: "rel", role: "Relative path from base to target" },
      { name: "walk", role: "List direct children under a directory" },
    ],
  },
  {
    path: "std/fs",
    name: "fs",
    title: "Filesystem",
    summary: "Files, directories, metadata, streaming, and chmod.",
    group: "Files and process",
    docsPath: "/docs/std/fs",
    exports: [
      { name: "exists", role: "True if the path exists" },
      { name: "is_file", role: "True if the path is a regular file" },
      { name: "is_dir", role: "True if the path is a directory" },
      { name: "join", role: "Join path segments with platform rules" },
      { name: "read", role: "Read a whole file as bytes" },
      { name: "write", role: "Write a whole file" },
      { name: "remove", role: "Remove a file" },
      { name: "copy", role: "Copy a file" },
      { name: "rename", role: "Rename or move a path" },
      { name: "create_dir", role: "Create a directory" },
      { name: "create_dir_all", role: "Create a directory tree" },
      { name: "read_dir", role: "List directory entry names" },
      { name: "remove_dir", role: "Remove an empty directory" },
      { name: "metadata", role: "File metadata product" },
      { name: "open", role: "Open a file for reading" },
      { name: "create", role: "Create or truncate a file for writing" },
      { name: "append", role: "Open a file for append" },
      { name: "meta", role: "Metadata product shape" },
      { name: "file", role: "Streaming file handle shape" },
      { name: "temp_dir", role: "System temporary directory path" },
      { name: "create_temp", role: "Create a temporary path" },
      { name: "symlink", role: "Create a symbolic link" },
      { name: "chmod", role: "Set Unix file mode bits" },
    ],
  },
  {
    path: "std/process",
    name: "process",
    title: "Process",
    summary: "Args, environment, spawn, capture, and process pipes.",
    group: "Files and process",
    docsPath: "/docs/std/process",
    exports: [
      { name: "args", role: "Process argv as a list of strings" },
      { name: "env", role: "Look up an environment variable (option)" },
      { name: "env_set", role: "Set an environment variable" },
      { name: "env_unset", role: "Unset an environment variable" },
      { name: "exit", role: "Terminate with an exit code" },
      { name: "run", role: "Spawn and wait for an exit code" },
      { name: "run_capture", role: "Spawn and capture stdout and stderr" },
      { name: "run_cwd", role: "Spawn with a working directory; capture output" },
      { name: "spawn_pipes", role: "Spawn with piped stdin, stdout, and stderr handles" },
      { name: "pipe_write", role: "Write to a process pipe (stdin)" },
      { name: "pipe_read", role: "Read from a process pipe (stdout or stderr)" },
      { name: "pipe_close", role: "Close one end of a process pipe" },
      { name: "wait", role: "Wait for a child process; returns exit code" },
    ],
  },
  {
    path: "std/os",
    name: "os",
    title: "OS",
    summary: "Process id, working directory, hostname, and platform.",
    group: "Files and process",
    docsPath: "/docs/std/os",
    exports: [
      { name: "pid", role: "Current process id" },
      { name: "cwd", role: "Current working directory" },
      { name: "chdir", role: "Change working directory" },
      { name: "hostname", role: "Host name string" },
      { name: "platform", role: "OS platform string" },
    ],
  },
  {
    path: "std/json",
    name: "json",
    title: "JSON",
    summary: "Parse and stringify JSON product values.",
    group: "Data",
    docsPath: "/docs/std/json",
    exports: [
      { name: "parse", role: "Parse JSON text to a product value" },
      { name: "stringify", role: "Serialize a product value to JSON text" },
    ],
  },
  {
    path: "std/encoding/hex",
    name: "hex",
    title: "Hex",
    summary: "Hex encode and decode.",
    group: "Data",
    docsPath: "/docs/std/encoding-hex",
    exports: [
      { name: "encode", role: "Encode bytes or text to a string form" },
      { name: "decode", role: "Decode a string form to bytes" },
    ],
  },
  {
    path: "std/encoding/base64",
    name: "base64",
    title: "Base64",
    summary: "Base64 encode and decode.",
    group: "Data",
    docsPath: "/docs/std/encoding-base64",
    exports: [
      { name: "encode", role: "Encode bytes or text to a string form" },
      { name: "decode", role: "Decode a string form to bytes" },
    ],
  },
  {
    path: "std/encoding/csv",
    name: "csv",
    title: "CSV",
    summary: "Thin CSV line and multi-line helpers.",
    group: "Data",
    docsPath: "/docs/std/encoding-csv",
    exports: [
      { name: "parse_line", role: "Split one CSV line into fields" },
      { name: "parse", role: "Parse multi-line CSV into rows" },
      { name: "format_line", role: "Join fields into a CSV line" },
    ],
  },
  {
    path: "std/compress/gzip",
    name: "gzip",
    title: "gzip",
    summary: "gzip compress and decompress.",
    group: "Data",
    docsPath: "/docs/std/compress-gzip",
    exports: [
      { name: "compress", role: "Compress input to bytes" },
      { name: "decompress", role: "Decompress bytes" },
    ],
  },
  {
    path: "std/compress/zip",
    name: "zip",
    title: "zip",
    summary: "Single-entry zip pack and unpack.",
    group: "Data",
    docsPath: "/docs/std/compress-zip",
    exports: [
      { name: "pack", role: "Pack a single named entry into a zip" },
      { name: "unpack_first", role: "Unpack the first zip entry" },
    ],
  },
  {
    path: "std/collections/map",
    name: "map",
    title: "Map",
    summary: "Hash map with mixed keys.",
    group: "Collections",
    docsPath: "/docs/std/collections-map",
    exports: [
      { name: "map", role: "Map shape with put and get methods" },
      { name: "make", role: "Construct an empty or default instance" },
      { name: "from_indexed", role: "Build a map from indexed pairs" },
    ],
  },
  {
    path: "std/collections/set",
    name: "set",
    title: "Set",
    summary: "Hash set with mixed members.",
    group: "Collections",
    docsPath: "/docs/std/collections-set",
    exports: [
      { name: "set", role: "Set shape with add and has methods" },
      { name: "make", role: "Construct an empty or default instance" },
      { name: "from_list", role: "Build a set from a list" },
    ],
  },
  {
    path: "std/collections/queue",
    name: "queue",
    title: "Queue",
    summary: "FIFO queue over a list.",
    group: "Collections",
    docsPath: "/docs/std/collections-queue",
    exports: [
      { name: "queue", role: "FIFO queue shape" },
      { name: "make", role: "Construct an empty or default instance" },
    ],
  },
  {
    path: "std/collections/hash_table",
    name: "hash_table",
    title: "Hash table",
    summary: "Lower-level hash table.",
    group: "Collections",
    docsPath: "/docs/std/collections-hash_table",
    exports: [
      { name: "hash_table", role: "Hash table shape" },
      { name: "make", role: "Construct an empty or default instance" },
    ],
  },
  {
    path: "std/crypto/hash",
    name: "hash",
    title: "Hash",
    summary: "SipHash, SHA-256, and SHA-512.",
    group: "Crypto and random",
    docsPath: "/docs/std/crypto-hash",
    exports: [
      { name: "sha256", role: "SHA-256 digest (32 bytes)" },
      { name: "sha512", role: "SHA-512 digest (64 bytes)" },
      { name: "sip", role: "SipHash-2-4 of a message with k0 and k1 keys" },
    ],
  },
  {
    path: "std/crypto/hmac",
    name: "hmac",
    title: "HMAC",
    summary: "HMAC-SHA256.",
    group: "Crypto and random",
    docsPath: "/docs/std/crypto-hmac",
    exports: [{ name: "sha256", role: "HMAC-SHA256 of key and data (32 bytes)" }],
  },
  {
    path: "std/crypto/aes_gcm",
    name: "aes_gcm",
    title: "AES-GCM",
    summary: "AES-256-GCM encrypt and decrypt.",
    group: "Crypto and random",
    docsPath: "/docs/std/crypto-aes_gcm",
    exports: [
      { name: "encrypt", role: "AES-256-GCM encrypt (32-byte key, 12-byte nonce)" },
      { name: "decrypt", role: "AES-256-GCM decrypt" },
    ],
  },
  {
    path: "std/crypto/random",
    name: "random",
    title: "CSPRNG",
    summary: "Cryptographic random bytes and u64.",
    group: "Crypto and random",
    docsPath: "/docs/std/crypto-random",
    exports: [
      { name: "fill", role: "Fill n bytes from the CSPRNG" },
      { name: "u64", role: "Cryptographic random u64" },
    ],
  },
  {
    path: "std/random",
    name: "random",
    title: "PRNG",
    summary: "Seeded non-cryptographic PRNG.",
    group: "Crypto and random",
    docsPath: "/docs/std/random",
    exports: [
      { name: "seed", role: "Seed the non-crypto PRNG" },
      { name: "u64", role: "Next PRNG u64" },
      { name: "float", role: "Next PRNG float in [0, 1)" },
    ],
  },
  {
    path: "std/log",
    name: "log",
    title: "Logging",
    summary: "Leveled messages and key=value helpers.",
    group: "Crypto and random",
    docsPath: "/docs/std/log",
    exports: [
      { name: "emit", role: "Emit a message when msg_level meets min_level" },
      { name: "debug", role: "Emit a debug-level message" },
      { name: "info", role: "Emit an info-level message" },
      { name: "warn", role: "Emit a warning-level message" },
      { name: "error", role: "Emit an error-level message" },
      { name: "kv", role: "Join key=value pairs into a string" },
      { name: "info_kv", role: "Info line with key=value pairs" },
    ],
  },
  {
    path: "std/net/tcp",
    name: "tcp",
    title: "TCP",
    summary: "TCP listen, connect, read, and write.",
    group: "Network",
    docsPath: "/docs/std/net-tcp",
    exports: [
      { name: "conn", role: "TCP connection shape" },
      { name: "listener", role: "TCP listener shape" },
      { name: "listen", role: "Start listening; failure yields handle 0" },
      { name: "connect", role: "Connect; failure yields handle 0 or a result error" },
      { name: "accept", role: "Accept a connection; failure yields handle 0" },
      { name: "read", role: "Read up to limit bytes" },
      { name: "write", role: "Write bytes or string data" },
      { name: "close", role: "Close the resource" },
    ],
  },
  {
    path: "std/net/udp",
    name: "udp",
    title: "UDP",
    summary: "UDP bind, send, and receive.",
    group: "Network",
    docsPath: "/docs/std/net-udp",
    exports: [
      { name: "bind", role: "Bind a UDP socket" },
      { name: "send_to", role: "Send a datagram to an address" },
      { name: "recv_from", role: "Receive a datagram with sender address" },
      { name: "close", role: "Close the resource" },
      { name: "socket", role: "UDP socket shape" },
    ],
  },
  {
    path: "std/net/unix",
    name: "unix",
    title: "Unix sockets",
    summary: "Unix domain sockets.",
    group: "Network",
    docsPath: "/docs/std/net-unix",
    exports: [
      { name: "listener", role: "Unix domain listener shape" },
      { name: "conn", role: "Unix stream connection shape" },
      { name: "listen", role: "Start listening; failure yields handle 0" },
      { name: "accept", role: "Accept a connection; failure yields handle 0" },
      { name: "connect", role: "Connect; failure yields handle 0 or a result error" },
      { name: "read", role: "Read up to limit bytes" },
      { name: "write", role: "Write bytes or string data" },
      { name: "close", role: "Close the resource" },
    ],
  },
  {
    path: "std/net/tls",
    name: "tls",
    title: "TLS",
    summary: "TLS client and server over rustls.",
    group: "Network",
    docsPath: "/docs/std/net-tls",
    exports: [
      { name: "listener", role: "TLS listener shape" },
      { name: "conn", role: "TLS connection shape" },
      { name: "listen", role: "Start listening; failure yields handle 0" },
      { name: "accept", role: "Accept a connection; failure yields handle 0" },
      { name: "connect", role: "Connect; failure yields handle 0 or a result error" },
      { name: "read", role: "Read up to limit bytes" },
      { name: "write", role: "Write bytes or string data" },
      { name: "close", role: "Close the resource" },
      { name: "close_listener", role: "Close a TLS listener" },
      { name: "load_pem", role: "Load a PEM file as a string" },
    ],
  },
  {
    path: "std/net/dns",
    name: "dns",
    title: "DNS",
    summary: "Host name lookup.",
    group: "Network",
    docsPath: "/docs/std/net-dns",
    exports: [{ name: "lookup", role: "Resolve a host name to address strings" }],
  },
  {
    path: "std/net/url",
    name: "url",
    title: "URL",
    summary: "Parse and format http(s) URLs.",
    group: "Network",
    docsPath: "/docs/std/net-url",
    exports: [
      { name: "parse", role: "Parse an http(s) URL into product fields" },
      { name: "format", role: "Build a URL string from scheme, host, port, and path" },
    ],
  },
  {
    path: "std/net/http",
    name: "http",
    title: "HTTP server",
    summary: "HTTP serve loop and connection handling.",
    group: "Network",
    docsPath: "/docs/std/net-http",
    exports: [
      { name: "request", role: "HTTP request shape (re-export)" },
      { name: "response", role: "HTTP response shape (re-export)" },
      { name: "server", role: "HTTP server shape (re-export)" },
      { name: "text_response", role: "Build a text/plain response" },
      { name: "html_response", role: "Build a text/html response" },
      { name: "json_response", role: "Build an application/json response" },
      { name: "parse_request", role: "Parse raw HTTP request bytes" },
      { name: "format_response", role: "Format a response as HTTP bytes" },
      { name: "dispatch", role: "Dispatch a request to matching routes" },
      { name: "handle_connection", role: "Handle one HTTP connection" },
      { name: "serve", role: "Accept loop serving routes" },
    ],
  },
  {
    path: "std/net/http_client",
    name: "http_client",
    title: "HTTP client",
    summary: "HTTP and HTTPS client requests.",
    group: "Network",
    docsPath: "/docs/std/net-http_client",
    exports: [
      { name: "get", role: "HTTP GET over cleartext TCP" },
      { name: "request", role: "HTTP request with method, headers, and body" },
      { name: "get_tls", role: "HTTPS GET over TLS" },
      { name: "request_tls", role: "HTTPS request over TLS" },
    ],
  },
  {
    path: "std/net/request",
    name: "request",
    title: "HTTP request",
    summary: "HTTP request product shape.",
    group: "Network",
    docsPath: "/docs/std/net-request",
    exports: [{ name: "request", role: "HTTP request shape and helpers" }],
  },
  {
    path: "std/net/response",
    name: "response",
    title: "HTTP response",
    summary: "HTTP response product shape.",
    group: "Network",
    docsPath: "/docs/std/net-response",
    exports: [{ name: "response", role: "HTTP response shape and helpers" }],
  },
  {
    path: "std/net/server",
    name: "server",
    title: "HTTP server type",
    summary: "HTTP server product shape.",
    group: "Network",
    docsPath: "/docs/std/net-server",
    exports: [{ name: "server", role: "HTTP server shape" }],
  },
  {
    path: "std/cli",
    name: "cli",
    title: "CLI flags",
    summary: "Parse flags and positionals from argv.",
    group: "CLI",
    docsPath: "/docs/std/cli",
    exports: [
      { name: "parse", role: "Parse argv into flags and positionals" },
      { name: "has", role: "True if a flag is present" },
      { name: "get", role: "Get a flag value" },
      { name: "positionals", role: "Positional arguments list" },
    ],
  },
];

export const stdModuleByPath: Record<string, StdModule> = Object.fromEntries(
  stdModules.map((m) => [m.path, m]),
);

export function stdImportLine(m: StdModule): string {
  return `/ ${m.path}`;
}

export function stdExportsListing(m: StdModule): string {
  return m.exports.map((e) => `${e.name}  —  ${e.role}`).join("\n");
}

/** Groups in nav order. */
export const stdGroups: { title: string; modules: StdModule[] }[] = [
  { title: "Core", modules: stdModules.filter((m) => m.group === "Core") },
  {
    title: "Files and process",
    modules: stdModules.filter((m) => m.group === "Files and process"),
  },
  { title: "Data", modules: stdModules.filter((m) => m.group === "Data") },
  { title: "Collections", modules: stdModules.filter((m) => m.group === "Collections") },
  {
    title: "Crypto and random",
    modules: stdModules.filter((m) => m.group === "Crypto and random"),
  },
  { title: "Network", modules: stdModules.filter((m) => m.group === "Network") },
  { title: "CLI", modules: stdModules.filter((m) => m.group === "CLI") },
];

/** Total public export count across all product modules. */
export const stdExportCount = stdModules.reduce((n, m) => n + m.exports.length, 0);
