use super::RuntimeSignature;
use std::sync::LazyLock;

mod array_entries;
mod filesystem_entries;
mod math_entries;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuiltinLowering {
    DirectRuntimeCall,
    #[allow(dead_code)]
    GenericRuntimeCall,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuiltinCodegen {
    ArrayKeys,
    ArrayMerge,
    ArrayReplace,
    ArrayReverse,
    ArraySlice,
    Basename,
    Dirname,
    ChunkSplit,
    Getenv,
    InArray,
    Implode,
    Log,
    Nl2br,
    ObStart,
    StrPad,
    StrSplit,
    VoidStatement,
    VoidUnaryStatement,
    BoolStatement,
    ValueExpression,
    ValueUnaryExpression,
    ValueBinaryExpression,
    ValueUnaryOptionalContextExpression,
    ValueBinaryOptionalContextExpression,
    ValueUnaryOptionalBoolExpression,
    ValueUnaryOptionalBoolContextExpression,
    ValueTernaryExpression,
    FileGetContents,
    FilePutContents,
    Mkdir,
    Touch,
    Uniqid,
    Explode,
    SubstrCompare,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PhpBuiltin {
    pub php_name: &'static str,
    pub symbol: &'static str,
    pub helper_symbol: Option<&'static str>,
    pub signature: RuntimeSignature,
    pub lowering: BuiltinLowering,
    pub codegen: BuiltinCodegen,
}

impl PhpBuiltin {
    pub fn llvm_decl(self) -> String {
        self.signature.llvm_decl(self.symbol)
    }
}

pub const PHP_RUNTIME_HELPERS: &[(&str, RuntimeSignature)] =
    &[("echo_php_ob_start_value", RuntimeSignature::BoolEchoValue)];

pub static PHP_BUILTINS: LazyLock<Vec<PhpBuiltin>> = LazyLock::new(|| {
    let mut builtins = vec![
        PhpBuiltin {
            php_name: "abs",
            symbol: "echo_php_abs",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "flush",
            symbol: "echo_php_flush",
            helper_symbol: None,
            signature: RuntimeSignature::VoidNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::VoidStatement,
        },
        PhpBuiltin {
            php_name: "define",
            symbol: "echo_php_define",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "microtime",
            symbol: "echo_php_microtime",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "getenv",
            symbol: "echo_php_getenv",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::Getenv,
        },
        PhpBuiltin {
            php_name: "gethostname",
            symbol: "echo_php_gethostname",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "getmypid",
            symbol: "echo_php_getmypid",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "putenv",
            symbol: "echo_php_putenv",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "ob_implicit_flush",
            symbol: "echo_php_ob_implicit_flush",
            helper_symbol: None,
            signature: RuntimeSignature::VoidEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::VoidUnaryStatement,
        },
        PhpBuiltin {
            php_name: "ob_start",
            symbol: "echo_php_ob_start",
            helper_symbol: Some("echo_php_ob_start_value"),
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ObStart,
        },
        PhpBuiltin {
            php_name: "ob_flush",
            symbol: "echo_php_ob_flush",
            helper_symbol: None,
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::BoolStatement,
        },
        PhpBuiltin {
            php_name: "ob_clean",
            symbol: "echo_php_ob_clean",
            helper_symbol: None,
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::BoolStatement,
        },
        PhpBuiltin {
            php_name: "ob_end_flush",
            symbol: "echo_php_ob_end_flush",
            helper_symbol: None,
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::BoolStatement,
        },
        PhpBuiltin {
            php_name: "ob_end_clean",
            symbol: "echo_php_ob_end_clean",
            helper_symbol: None,
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::BoolStatement,
        },
        PhpBuiltin {
            php_name: "ob_get_clean",
            symbol: "echo_php_ob_get_clean",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "ob_get_contents",
            symbol: "echo_php_ob_get_contents",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "ob_get_flush",
            symbol: "echo_php_ob_get_flush",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "ob_get_length",
            symbol: "echo_php_ob_get_length",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "ob_get_level",
            symbol: "echo_php_ob_get_level",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "strlen",
            symbol: "echo_php_strlen",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
    ];
    builtins.extend_from_slice(array_entries::ARRAY_BUILTINS);
    builtins.extend_from_slice(filesystem_entries::FILESYSTEM_BUILTINS);
    builtins.extend_from_slice(&[
        PhpBuiltin {
            php_name: "function_exists",
            symbol: "echo_php_function_exists",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "gettype",
            symbol: "echo_php_gettype",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "array_is_list",
            symbol: "echo_php_array_is_list",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_array",
            symbol: "echo_php_is_array",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_countable",
            symbol: "echo_php_is_countable",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_iterable",
            symbol: "echo_php_is_iterable",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_numeric",
            symbol: "echo_php_is_numeric",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_null",
            symbol: "echo_php_is_null",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_bool",
            symbol: "echo_php_is_bool",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_callable",
            symbol: "echo_php_is_callable",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_int",
            symbol: "echo_php_is_int",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_integer",
            symbol: "echo_php_is_int",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_long",
            symbol: "echo_php_is_int",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_float",
            symbol: "echo_php_is_float",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_double",
            symbol: "echo_php_is_float",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_finite",
            symbol: "echo_php_is_finite",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_infinite",
            symbol: "echo_php_is_infinite",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_nan",
            symbol: "echo_php_is_nan",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_object",
            symbol: "echo_php_is_object",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_resource",
            symbol: "echo_php_is_resource",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_string",
            symbol: "echo_php_is_string",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_scalar",
            symbol: "echo_php_is_scalar",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "strval",
            symbol: "echo_php_strval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "boolval",
            symbol: "echo_php_boolval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "intval",
            symbol: "echo_php_intval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "floatval",
            symbol: "echo_php_floatval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "doubleval",
            symbol: "echo_php_floatval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "strtoupper",
            symbol: "echo_php_strtoupper",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "strtolower",
            symbol: "echo_php_strtolower",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "ucwords",
            symbol: "echo_php_ucwords",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "strrev",
            symbol: "echo_php_strrev",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "ucfirst",
            symbol: "echo_php_ucfirst",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "lcfirst",
            symbol: "echo_php_lcfirst",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "ord",
            symbol: "echo_php_ord",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "str_rot13",
            symbol: "echo_php_str_rot13",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "chr",
            symbol: "echo_php_chr",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
    ]);
    builtins.extend_from_slice(math_entries::MATH_BUILTINS);
    builtins.extend_from_slice(&[
        PhpBuiltin {
            php_name: "bin2hex",
            symbol: "echo_php_bin2hex",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "md5",
            symbol: "echo_php_md5",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryOptionalBoolExpression,
        },
        PhpBuiltin {
            php_name: "sha1",
            symbol: "echo_php_sha1",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryOptionalBoolExpression,
        },
        PhpBuiltin {
            php_name: "base64_encode",
            symbol: "echo_php_base64_encode",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "base64_decode",
            symbol: "echo_php_base64_decode",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "rawurlencode",
            symbol: "echo_php_rawurlencode",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "rawurldecode",
            symbol: "echo_php_rawurldecode",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "urlencode",
            symbol: "echo_php_urlencode",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "urldecode",
            symbol: "echo_php_urldecode",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "hex2bin",
            symbol: "echo_php_hex2bin",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "escapeshellarg",
            symbol: "echo_php_escapeshellarg",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "escapeshellcmd",
            symbol: "echo_php_escapeshellcmd",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "explode",
            symbol: "echo_php_explode",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::Explode,
        },
        PhpBuiltin {
            php_name: "implode",
            symbol: "echo_php_implode",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::Implode,
        },
        PhpBuiltin {
            php_name: "join",
            symbol: "echo_php_implode",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::Implode,
        },
        PhpBuiltin {
            php_name: "trim",
            symbol: "echo_php_trim",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "ltrim",
            symbol: "echo_php_ltrim",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "rtrim",
            symbol: "echo_php_rtrim",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "chop",
            symbol: "echo_php_rtrim",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "addslashes",
            symbol: "echo_php_addslashes",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "stripslashes",
            symbol: "echo_php_stripslashes",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "quotemeta",
            symbol: "echo_php_quotemeta",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "quoted_printable_encode",
            symbol: "echo_php_quoted_printable_encode",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "quoted_printable_decode",
            symbol: "echo_php_quoted_printable_decode",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "nl2br",
            symbol: "echo_php_nl2br",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::Nl2br,
        },
        PhpBuiltin {
            php_name: "str_contains",
            symbol: "echo_php_str_contains",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "str_starts_with",
            symbol: "echo_php_str_starts_with",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "str_ends_with",
            symbol: "echo_php_str_ends_with",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "str_replace",
            symbol: "echo_php_str_replace",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueTernaryExpression,
        },
        PhpBuiltin {
            php_name: "str_ireplace",
            symbol: "echo_php_str_ireplace",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueTernaryExpression,
        },
        PhpBuiltin {
            php_name: "strtr",
            symbol: "echo_php_strtr",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueTernaryExpression,
        },
        PhpBuiltin {
            php_name: "str_repeat",
            symbol: "echo_php_str_repeat",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "str_pad",
            symbol: "echo_php_str_pad",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::StrPad,
        },
        PhpBuiltin {
            php_name: "str_split",
            symbol: "echo_php_str_split",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::StrSplit,
        },
        PhpBuiltin {
            php_name: "chunk_split",
            symbol: "echo_php_chunk_split",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ChunkSplit,
        },
        PhpBuiltin {
            php_name: "substr",
            symbol: "echo_php_substr",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "strpos",
            symbol: "echo_php_strpos",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "stripos",
            symbol: "echo_php_stripos",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "strrpos",
            symbol: "echo_php_strrpos",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "strripos",
            symbol: "echo_php_strripos",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "strstr",
            symbol: "echo_php_strstr",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "strchr",
            symbol: "echo_php_strstr",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "stristr",
            symbol: "echo_php_stristr",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "strrchr",
            symbol: "echo_php_strrchr",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "strpbrk",
            symbol: "echo_php_strpbrk",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "strspn",
            symbol: "echo_php_strspn",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "strcspn",
            symbol: "echo_php_strcspn",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "substr_count",
            symbol: "echo_php_substr_count",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "substr_compare",
            symbol: "echo_php_substr_compare",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::SubstrCompare,
        },
        PhpBuiltin {
            php_name: "strcmp",
            symbol: "echo_php_strcmp",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "strcasecmp",
            symbol: "echo_php_strcasecmp",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "strncmp",
            symbol: "echo_php_strncmp",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueTernaryExpression,
        },
        PhpBuiltin {
            php_name: "strncasecmp",
            symbol: "echo_php_strncasecmp",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueTernaryExpression,
        },
    ]);
    builtins
});

pub fn php_builtin(name: &str) -> Option<PhpBuiltin> {
    PHP_BUILTINS
        .iter()
        .copied()
        .find(|builtin| builtin.php_name == name)
}
