use super::RuntimeSignature;
use std::sync::LazyLock;

mod array_entries;
mod filesystem_entries;
mod math_entries;
mod string_entries;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuiltinLowering {
    DirectRuntimeCall,
    #[allow(dead_code)]
    GenericRuntimeCall,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuiltinCodegen {
    ArrayKeys,
    ArrayMerge,
    ArrayReplace,
    ArrayReverse,
    ArraySlice,
    Basename,
    Dirname,
    ChunkSplit,
    Getenv,
    GetLoadedExtensions,
    InArray,
    Implode,
    Levenshtein,
    Log,
    Nl2br,
    NumberFormat,
    PhpVersion,
    Round,
    ObStart,
    StrPad,
    StrSplit,
    VoidStatement,
    VoidUnaryStatement,
    BoolStatement,
    ValueExpression,
    ValueUnaryExpression,
    ValueBinaryExpression,
    ValueUnaryOptionalContextExpression,
    ValueBinaryOptionalContextExpression,
    ValueUnaryOptionalBoolExpression,
    ValueUnaryOptionalBoolContextExpression,
    ValueTernaryExpression,
    FileGetContents,
    FilePutContents,
    Mkdir,
    Touch,
    Uniqid,
    Explode,
    SubstrCompare,
    SubstrReplace,
    Wordwrap,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PhpBuiltin {
    pub php_name: &'static str,
    pub symbol: &'static str,
    pub helper_symbol: Option<&'static str>,
    pub signature: RuntimeSignature,
    pub lowering: BuiltinLowering,
    pub codegen: BuiltinCodegen,
}

impl PhpBuiltin {
    pub fn llvm_decl(self) -> String {
        self.signature.llvm_decl(self.symbol)
    }
}

pub const PHP_RUNTIME_HELPERS: &[(&str, RuntimeSignature)] =
    &[("echo_php_ob_start_value", RuntimeSignature::BoolEchoValue)];

pub static PHP_BUILTINS: LazyLock<Vec<PhpBuiltin>> = LazyLock::new(|| {
    let mut builtins = vec![
        PhpBuiltin {
            php_name: "abs",
            symbol: "echo_php_abs",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "flush",
            symbol: "echo_php_flush",
            helper_symbol: None,
            signature: RuntimeSignature::VoidNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::VoidStatement,
        },
        PhpBuiltin {
            php_name: "define",
            symbol: "echo_php_define",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "microtime",
            symbol: "echo_php_microtime",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "phpversion",
            symbol: "echo_php_phpversion",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::PhpVersion,
        },
        PhpBuiltin {
            php_name: "php_sapi_name",
            symbol: "echo_php_php_sapi_name",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "zend_version",
            symbol: "echo_php_zend_version",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "extension_loaded",
            symbol: "echo_php_extension_loaded",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "get_loaded_extensions",
            symbol: "echo_php_get_loaded_extensions",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::GetLoadedExtensions,
        },
        PhpBuiltin {
            php_name: "get_extension_funcs",
            symbol: "echo_php_get_extension_funcs",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "get_cfg_var",
            symbol: "echo_php_get_cfg_var",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "ini_get",
            symbol: "echo_php_ini_get",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "ini_set",
            symbol: "echo_php_ini_set",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "ini_alter",
            symbol: "echo_php_ini_alter",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "ini_restore",
            symbol: "echo_php_ini_restore",
            helper_symbol: None,
            signature: RuntimeSignature::VoidEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::VoidUnaryStatement,
        },
        PhpBuiltin {
            php_name: "php_ini_loaded_file",
            symbol: "echo_php_php_ini_loaded_file",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "php_ini_scanned_files",
            symbol: "echo_php_php_ini_scanned_files",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "getenv",
            symbol: "echo_php_getenv",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::Getenv,
        },
        PhpBuiltin {
            php_name: "gethostname",
            symbol: "echo_php_gethostname",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "getmypid",
            symbol: "echo_php_getmypid",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "putenv",
            symbol: "echo_php_putenv",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "ob_implicit_flush",
            symbol: "echo_php_ob_implicit_flush",
            helper_symbol: None,
            signature: RuntimeSignature::VoidEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::VoidUnaryStatement,
        },
        PhpBuiltin {
            php_name: "ob_start",
            symbol: "echo_php_ob_start",
            helper_symbol: Some("echo_php_ob_start_value"),
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ObStart,
        },
        PhpBuiltin {
            php_name: "ob_flush",
            symbol: "echo_php_ob_flush",
            helper_symbol: None,
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::BoolStatement,
        },
        PhpBuiltin {
            php_name: "ob_clean",
            symbol: "echo_php_ob_clean",
            helper_symbol: None,
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::BoolStatement,
        },
        PhpBuiltin {
            php_name: "ob_end_flush",
            symbol: "echo_php_ob_end_flush",
            helper_symbol: None,
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::BoolStatement,
        },
        PhpBuiltin {
            php_name: "ob_end_clean",
            symbol: "echo_php_ob_end_clean",
            helper_symbol: None,
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::BoolStatement,
        },
        PhpBuiltin {
            php_name: "ob_get_clean",
            symbol: "echo_php_ob_get_clean",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "ob_get_contents",
            symbol: "echo_php_ob_get_contents",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "ob_get_flush",
            symbol: "echo_php_ob_get_flush",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "ob_get_length",
            symbol: "echo_php_ob_get_length",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "ob_get_level",
            symbol: "echo_php_ob_get_level",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
    ];
    builtins.extend_from_slice(array_entries::ARRAY_BUILTINS);
    builtins.extend_from_slice(filesystem_entries::FILESYSTEM_BUILTINS);
    builtins.extend_from_slice(&[
        PhpBuiltin {
            php_name: "function_exists",
            symbol: "echo_php_function_exists",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "gettype",
            symbol: "echo_php_gettype",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "array_is_list",
            symbol: "echo_php_array_is_list",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_array",
            symbol: "echo_php_is_array",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_countable",
            symbol: "echo_php_is_countable",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_iterable",
            symbol: "echo_php_is_iterable",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_numeric",
            symbol: "echo_php_is_numeric",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_null",
            symbol: "echo_php_is_null",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_bool",
            symbol: "echo_php_is_bool",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_callable",
            symbol: "echo_php_is_callable",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_int",
            symbol: "echo_php_is_int",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_integer",
            symbol: "echo_php_is_int",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_long",
            symbol: "echo_php_is_int",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_float",
            symbol: "echo_php_is_float",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_double",
            symbol: "echo_php_is_float",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_finite",
            symbol: "echo_php_is_finite",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_infinite",
            symbol: "echo_php_is_infinite",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_nan",
            symbol: "echo_php_is_nan",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_object",
            symbol: "echo_php_is_object",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_resource",
            symbol: "echo_php_is_resource",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_string",
            symbol: "echo_php_is_string",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_scalar",
            symbol: "echo_php_is_scalar",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "strval",
            symbol: "echo_php_strval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "boolval",
            symbol: "echo_php_boolval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "intval",
            symbol: "echo_php_intval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "floatval",
            symbol: "echo_php_floatval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "doubleval",
            symbol: "echo_php_floatval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
    ]);
    builtins.extend_from_slice(math_entries::MATH_BUILTINS);
    builtins.extend_from_slice(string_entries::STRING_BUILTINS);
    builtins
});

pub fn php_builtin(name: &str) -> Option<PhpBuiltin> {
    PHP_BUILTINS
        .iter()
        .copied()
        .find(|builtin| builtin.php_name == name)
}
