use super::{BuiltinCodegen, BuiltinLowering, PhpBuiltin};
use crate::RuntimeSignature;

pub(super) const FILESYSTEM_BUILTINS: &[PhpBuiltin] = &[
    PhpBuiltin {
        php_name: "basename",
        symbol: "echo_php_basename",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Basename,
    },
    PhpBuiltin {
        php_name: "dirname",
        symbol: "echo_php_dirname",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Dirname,
    },
    PhpBuiltin {
        php_name: "pathinfo",
        symbol: "echo_php_pathinfo",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Pathinfo,
    },
    PhpBuiltin {
        php_name: "file_exists",
        symbol: "echo_php_file_exists",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "fnmatch",
        symbol: "echo_php_fnmatch",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "chdir",
        symbol: "echo_php_chdir",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "chmod",
        symbol: "echo_php_chmod",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "getcwd",
        symbol: "echo_php_getcwd",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueExpression,
    },
    PhpBuiltin {
        php_name: "clearstatcache",
        symbol: "echo_php_clearstatcache",
        helper_symbol: None,
        signature: RuntimeSignature::VoidEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Clearstatcache,
    },
    PhpBuiltin {
        php_name: "realpath_cache_size",
        symbol: "echo_php_realpath_cache_size",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueExpression,
    },
    PhpBuiltin {
        php_name: "realpath_cache_get",
        symbol: "echo_php_realpath_cache_get",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueExpression,
    },
    PhpBuiltin {
        php_name: "is_dir",
        symbol: "echo_php_is_dir",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_file",
        symbol: "echo_php_is_file",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_link",
        symbol: "echo_php_is_link",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_readable",
        symbol: "echo_php_is_readable",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_writable",
        symbol: "echo_php_is_writable",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_writeable",
        symbol: "echo_php_is_writable",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_executable",
        symbol: "echo_php_is_executable",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "filesize",
        symbol: "echo_php_filesize",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "fileatime",
        symbol: "echo_php_fileatime",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "filectime",
        symbol: "echo_php_filectime",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "filemtime",
        symbol: "echo_php_filemtime",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "fileinode",
        symbol: "echo_php_fileinode",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "fileowner",
        symbol: "echo_php_fileowner",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "filegroup",
        symbol: "echo_php_filegroup",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "fileperms",
        symbol: "echo_php_fileperms",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "filetype",
        symbol: "echo_php_filetype",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "lstat",
        symbol: "echo_php_lstat",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "stat",
        symbol: "echo_php_stat",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "file_get_contents",
        symbol: "echo_php_file_get_contents",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::FileGetContents,
    },
    PhpBuiltin {
        php_name: "file_put_contents",
        symbol: "echo_php_file_put_contents",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::FilePutContents,
    },
    PhpBuiltin {
        php_name: "fopen",
        symbol: "echo_php_fopen",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "fread",
        symbol: "echo_php_fread",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "fgetc",
        symbol: "echo_php_fgetc",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "fgets",
        symbol: "echo_php_fgets",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryOptionalNullExpression,
    },
    PhpBuiltin {
        php_name: "feof",
        symbol: "echo_php_feof",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "fflush",
        symbol: "echo_php_fflush",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "fclose",
        symbol: "echo_php_fclose",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "ftell",
        symbol: "echo_php_ftell",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "fseek",
        symbol: "echo_php_fseek",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "rewind",
        symbol: "echo_php_rewind",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "stream_get_contents",
        symbol: "echo_php_stream_get_contents",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "tmpfile",
        symbol: "echo_php_tmpfile",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueExpression,
    },
    PhpBuiltin {
        php_name: "readfile",
        symbol: "echo_php_readfile",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryOptionalBoolContextExpression,
    },
    PhpBuiltin {
        php_name: "readlink",
        symbol: "echo_php_readlink",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "link",
        symbol: "echo_php_link",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "symlink",
        symbol: "echo_php_symlink",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "sys_get_temp_dir",
        symbol: "echo_php_sys_get_temp_dir",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueExpression,
    },
    PhpBuiltin {
        php_name: "tempnam",
        symbol: "echo_php_tempnam",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "uniqid",
        symbol: "echo_php_uniqid",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Uniqid,
    },
    PhpBuiltin {
        php_name: "touch",
        symbol: "echo_php_touch",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Touch,
    },
    PhpBuiltin {
        php_name: "copy",
        symbol: "echo_php_copy",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryOptionalContextExpression,
    },
    PhpBuiltin {
        php_name: "rename",
        symbol: "echo_php_rename",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryOptionalContextExpression,
    },
    PhpBuiltin {
        php_name: "unlink",
        symbol: "echo_php_unlink",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryOptionalContextExpression,
    },
    PhpBuiltin {
        php_name: "mkdir",
        symbol: "echo_php_mkdir",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Mkdir,
    },
    PhpBuiltin {
        php_name: "rmdir",
        symbol: "echo_php_rmdir",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryOptionalContextExpression,
    },
    PhpBuiltin {
        php_name: "realpath",
        symbol: "echo_php_realpath",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
];
