//! Compiler-facing runtime ABI policy.
//!
//! `echo_*` symbols are the small core compiler/runtime ABI used for language
//! semantics such as output writes and shutdown.
//! `echo_php_*` symbols are PHP builtin implementations used when codegen can
//! statically resolve a PHP function call.
//! `echo_ext_*` is reserved for a future extension/module ABI.
//! `echo_internal_*` symbols are runtime-private implementation details and must
//! not be emitted by codegen.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CoreRuntimeSymbol {
    Write,
    WriteValue,
    ValueString,
    ValueAdd,
    ValueSub,
    ValueMul,
    ValueDiv,
    ValueMod,
    ValuePow,
    ValueUnaryPlus,
    ValueUnaryMinus,
    ValueBool,
    ValueConcat,
    ValueListNew,
    ValueListAppend,
    ValueArrayNew,
    ValueArrayAppend,
    ValueArraySet,
    ValueIndexGet,
    ValueObjectNew,
    ValueObjectSet,
    ValueObjectGet,
    TaskDefer,
    TaskRun,
    TaskJoin,
    TaskGroupNew,
    TaskGroupAdd,
    TaskGroupRunAndJoin,
    ThreadFork,
    ThreadForkTask,
    ThreadJoin,
    ProcessSpawn,
    ProcessJoin,
    Join,
    Require,
    RequireOnce,
    TaskSleepCurrent,
    TimeSleep,
    CallFunction,
    RegisterFunction,
    Shutdown,
}

impl CoreRuntimeSymbol {
    pub const ALL: &'static [Self] = &[
        Self::Write,
        Self::WriteValue,
        Self::ValueString,
        Self::ValueAdd,
        Self::ValueSub,
        Self::ValueMul,
        Self::ValueDiv,
        Self::ValueMod,
        Self::ValuePow,
        Self::ValueUnaryPlus,
        Self::ValueUnaryMinus,
        Self::ValueBool,
        Self::ValueConcat,
        Self::ValueListNew,
        Self::ValueListAppend,
        Self::ValueArrayNew,
        Self::ValueArrayAppend,
        Self::ValueArraySet,
        Self::ValueIndexGet,
        Self::ValueObjectNew,
        Self::ValueObjectSet,
        Self::ValueObjectGet,
        Self::TaskDefer,
        Self::TaskRun,
        Self::TaskJoin,
        Self::TaskGroupNew,
        Self::TaskGroupAdd,
        Self::TaskGroupRunAndJoin,
        Self::ThreadFork,
        Self::ThreadForkTask,
        Self::ThreadJoin,
        Self::ProcessSpawn,
        Self::ProcessJoin,
        Self::Join,
        Self::Require,
        Self::RequireOnce,
        Self::TaskSleepCurrent,
        Self::TimeSleep,
        Self::CallFunction,
        Self::RegisterFunction,
        Self::Shutdown,
    ];

    pub const fn symbol(self) -> &'static str {
        match self {
            Self::Write => "echo_write",
            Self::WriteValue => "echo_write_value",
            Self::ValueString => "echo_value_string",
            Self::ValueAdd => "echo_value_add",
            Self::ValueSub => "echo_value_sub",
            Self::ValueMul => "echo_value_mul",
            Self::ValueDiv => "echo_value_div",
            Self::ValueMod => "echo_value_mod",
            Self::ValuePow => "echo_value_pow",
            Self::ValueUnaryPlus => "echo_value_unary_plus",
            Self::ValueUnaryMinus => "echo_value_unary_minus",
            Self::ValueBool => "echo_value_bool",
            Self::ValueConcat => "echo_value_concat",
            Self::ValueListNew => "echo_value_list_new",
            Self::ValueListAppend => "echo_value_list_append",
            Self::ValueArrayNew => "echo_value_array_new",
            Self::ValueArrayAppend => "echo_value_array_append",
            Self::ValueArraySet => "echo_value_array_set",
            Self::ValueIndexGet => "echo_value_index_get",
            Self::ValueObjectNew => "echo_value_object_new",
            Self::ValueObjectSet => "echo_value_object_set",
            Self::ValueObjectGet => "echo_value_object_get",
            Self::TaskDefer => "echo_task_defer",
            Self::TaskRun => "echo_task_run",
            Self::TaskJoin => "echo_task_join",
            Self::TaskGroupNew => "echo_task_group_new",
            Self::TaskGroupAdd => "echo_task_group_add",
            Self::TaskGroupRunAndJoin => "echo_task_group_run_and_join",
            Self::ThreadFork => "echo_thread_fork",
            Self::ThreadForkTask => "echo_thread_fork_task",
            Self::ThreadJoin => "echo_thread_join",
            Self::ProcessSpawn => "echo_process_spawn",
            Self::ProcessJoin => "echo_process_join",
            Self::Join => "echo_join",
            Self::Require => "echo_php_require",
            Self::RequireOnce => "echo_php_require_once",
            Self::TaskSleepCurrent => "echo_task_sleep_current",
            Self::TimeSleep => "echo_time_sleep",
            Self::CallFunction => "echo_call_function",
            Self::RegisterFunction => "echo_reflection_register_function",
            Self::Shutdown => "echo_shutdown",
        }
    }

    pub const fn signature(self) -> RuntimeSignature {
        match self {
            Self::Write => RuntimeSignature::VoidPtrI64,
            Self::WriteValue => RuntimeSignature::VoidEchoValue,
            Self::ValueString => RuntimeSignature::EchoValuePtrI64,
            Self::ValueAdd => RuntimeSignature::EchoValueEchoValueEchoValue,
            Self::ValueSub => RuntimeSignature::EchoValueEchoValueEchoValue,
            Self::ValueMul => RuntimeSignature::EchoValueEchoValueEchoValue,
            Self::ValueDiv => RuntimeSignature::EchoValueEchoValueEchoValue,
            Self::ValueMod => RuntimeSignature::EchoValueEchoValueEchoValue,
            Self::ValuePow => RuntimeSignature::EchoValueEchoValueEchoValue,
            Self::ValueUnaryPlus => RuntimeSignature::EchoValueEchoValue,
            Self::ValueUnaryMinus => RuntimeSignature::EchoValueEchoValue,
            Self::ValueBool => RuntimeSignature::BoolEchoValue,
            Self::ValueConcat => RuntimeSignature::EchoValueEchoValueEchoValue,
            Self::ValueListNew => RuntimeSignature::EchoValueNoArgs,
            Self::ValueListAppend => RuntimeSignature::EchoValueEchoValueEchoValue,
            Self::ValueArrayNew => RuntimeSignature::EchoValueNoArgs,
            Self::ValueArrayAppend => RuntimeSignature::EchoValueEchoValueEchoValue,
            Self::ValueArraySet => RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
            Self::ValueIndexGet => RuntimeSignature::EchoValueEchoValueEchoValue,
            Self::ValueObjectNew => RuntimeSignature::EchoValueNoArgs,
            Self::ValueObjectSet => RuntimeSignature::EchoValueEchoValuePtrI64EchoValue,
            Self::ValueObjectGet => RuntimeSignature::EchoValueEchoValuePtrI64,
            Self::TaskDefer => RuntimeSignature::EchoValuePtr,
            Self::TaskRun => RuntimeSignature::EchoValueEchoValue,
            Self::TaskJoin => RuntimeSignature::EchoValueEchoValue,
            Self::TaskGroupNew => RuntimeSignature::EchoValueNoArgs,
            Self::TaskGroupAdd => RuntimeSignature::EchoValueEchoValueEchoValue,
            Self::TaskGroupRunAndJoin => RuntimeSignature::EchoValueEchoValue,
            Self::ThreadFork => RuntimeSignature::EchoValuePtr,
            Self::ThreadForkTask => RuntimeSignature::EchoValueEchoValue,
            Self::ThreadJoin => RuntimeSignature::EchoValueEchoValue,
            Self::ProcessSpawn => RuntimeSignature::EchoValueEchoValue,
            Self::ProcessJoin => RuntimeSignature::EchoValueEchoValue,
            Self::Join => RuntimeSignature::EchoValueEchoValue,
            Self::Require => RuntimeSignature::EchoValueEchoValue,
            Self::RequireOnce => RuntimeSignature::EchoValueEchoValue,
            Self::TaskSleepCurrent => RuntimeSignature::EchoValueI64Ptr,
            Self::TimeSleep => RuntimeSignature::VoidI64,
            Self::CallFunction => RuntimeSignature::EchoValuePtrI64,
            Self::RegisterFunction => RuntimeSignature::VoidPtrI64PtrI64PtrI64I32,
            Self::Shutdown => RuntimeSignature::VoidNoArgs,
        }
    }

    pub fn llvm_decl(self) -> String {
        self.signature().llvm_decl(self.symbol())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RuntimeSignature {
    VoidNoArgs,
    VoidI64,
    VoidPtrI64,
    VoidPtrI64PtrI64PtrI64I32,
    VoidEchoValue,
    BoolNoArgs,
    BoolEchoValue,
    EchoValueNoArgs,
    EchoValueI64Ptr,
    EchoValuePtr,
    EchoValuePtrI64,
    EchoValueEchoValue,
    EchoValueEchoValuePtrI64,
    EchoValueEchoValueEchoValue,
    EchoValueEchoValueEchoValueEchoValue,
    EchoValueEchoValueEchoValueEchoValueEchoValue,
    EchoValueEchoValueEchoValueEchoValueEchoValueEchoValue,
    EchoValueEchoValuePtrI64EchoValue,
}

impl RuntimeSignature {
    pub fn llvm_decl(self, symbol: &str) -> String {
        match self {
            Self::VoidNoArgs => format!("declare void @{symbol}()"),
            Self::VoidI64 => format!("declare void @{symbol}(i64)"),
            Self::VoidPtrI64 => format!("declare void @{symbol}(ptr, i64)"),
            Self::VoidPtrI64PtrI64PtrI64I32 => {
                format!("declare void @{symbol}(ptr, i64, ptr, i64, ptr, i64, i32)")
            }
            Self::VoidEchoValue => format!("declare void @{symbol}(%EchoValue)"),
            Self::BoolNoArgs => format!("declare i1 @{symbol}()"),
            Self::BoolEchoValue => format!("declare i1 @{symbol}(%EchoValue)"),
            Self::EchoValueNoArgs => format!("declare %EchoValue @{symbol}()"),
            Self::EchoValueI64Ptr => format!("declare %EchoValue @{symbol}(i64, ptr)"),
            Self::EchoValuePtr => format!("declare %EchoValue @{symbol}(ptr)"),
            Self::EchoValuePtrI64 => format!("declare %EchoValue @{symbol}(ptr, i64)"),
            Self::EchoValueEchoValue => format!("declare %EchoValue @{symbol}(%EchoValue)"),
            Self::EchoValueEchoValuePtrI64 => {
                format!("declare %EchoValue @{symbol}(%EchoValue, ptr, i64)")
            }
            Self::EchoValueEchoValueEchoValue => {
                format!("declare %EchoValue @{symbol}(%EchoValue, %EchoValue)")
            }
            Self::EchoValueEchoValueEchoValueEchoValue => {
                format!("declare %EchoValue @{symbol}(%EchoValue, %EchoValue, %EchoValue)")
            }
            Self::EchoValueEchoValueEchoValueEchoValueEchoValue => {
                format!(
                    "declare %EchoValue @{symbol}(%EchoValue, %EchoValue, %EchoValue, %EchoValue)"
                )
            }
            Self::EchoValueEchoValueEchoValueEchoValueEchoValueEchoValue => {
                format!(
                    "declare %EchoValue @{symbol}(%EchoValue, %EchoValue, %EchoValue, %EchoValue, %EchoValue)"
                )
            }
            Self::EchoValueEchoValuePtrI64EchoValue => {
                format!("declare %EchoValue @{symbol}(%EchoValue, ptr, i64, %EchoValue)")
            }
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuiltinLowering {
    DirectRuntimeCall,
    #[allow(dead_code)]
    GenericRuntimeCall,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StdIntrinsic {
    pub echo_name: &'static str,
    pub symbol: &'static str,
    pub signature: RuntimeSignature,
    pub arity: usize,
}

impl StdIntrinsic {
    pub fn llvm_decl(self) -> String {
        self.signature.llvm_decl(self.symbol)
    }
}

pub const STD_INTRINSICS: &[StdIntrinsic] = &[
    StdIntrinsic {
        echo_name: "assert.ok",
        symbol: "echo_std_assert_ok",
        signature: RuntimeSignature::EchoValueEchoValue,
        arity: 1,
    },
    StdIntrinsic {
        echo_name: "assert.equals",
        symbol: "echo_std_assert_equals",
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        arity: 2,
    },
    StdIntrinsic {
        echo_name: "http.responseText",
        symbol: "echo_std_http_response_text",
        signature: RuntimeSignature::EchoValueEchoValue,
        arity: 1,
    },
    StdIntrinsic {
        echo_name: "http.readRequest",
        symbol: "echo_std_http_read_request",
        signature: RuntimeSignature::EchoValueEchoValue,
        arity: 1,
    },
    StdIntrinsic {
        echo_name: "net.listen",
        symbol: "echo_std_net_listen",
        signature: RuntimeSignature::EchoValueEchoValue,
        arity: 1,
    },
    StdIntrinsic {
        echo_name: "net.connect",
        symbol: "echo_std_net_connect",
        signature: RuntimeSignature::EchoValueEchoValue,
        arity: 1,
    },
    StdIntrinsic {
        echo_name: "net.accept",
        symbol: "echo_std_net_accept",
        signature: RuntimeSignature::EchoValueEchoValue,
        arity: 1,
    },
    StdIntrinsic {
        echo_name: "net.read",
        symbol: "echo_std_net_read",
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        arity: 2,
    },
    StdIntrinsic {
        echo_name: "net.write",
        symbol: "echo_std_net_write",
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        arity: 2,
    },
    StdIntrinsic {
        echo_name: "net.close",
        symbol: "echo_std_net_close",
        signature: RuntimeSignature::EchoValueEchoValue,
        arity: 1,
    },
    StdIntrinsic {
        echo_name: "reflect.exists",
        symbol: "echo_std_reflect_exists",
        signature: RuntimeSignature::EchoValueEchoValue,
        arity: 1,
    },
    StdIntrinsic {
        echo_name: "reflect.params",
        symbol: "echo_std_reflect_params",
        signature: RuntimeSignature::EchoValueEchoValue,
        arity: 1,
    },
    StdIntrinsic {
        echo_name: "reflect.returnType",
        symbol: "echo_std_reflect_return_type",
        signature: RuntimeSignature::EchoValueEchoValue,
        arity: 1,
    },
    StdIntrinsic {
        echo_name: "reflect.typeOf",
        symbol: "echo_std_reflect_type_of",
        signature: RuntimeSignature::EchoValueEchoValue,
        arity: 1,
    },
];

pub fn std_intrinsic(name: &str) -> Option<StdIntrinsic> {
    STD_INTRINSICS
        .iter()
        .copied()
        .find(|intrinsic| intrinsic.echo_name == name)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuiltinCodegen {
    ArrayKeys,
    ArrayMerge,
    ArrayReplace,
    ArrayReverse,
    ArraySlice,
    Basename,
    Dirname,
    ChunkSplit,
    InArray,
    Implode,
    Log,
    ObStart,
    StrPad,
    StrSplit,
    VoidStatement,
    VoidUnaryStatement,
    BoolStatement,
    ValueExpression,
    ValueUnaryExpression,
    ValueBinaryExpression,
    ValueUnaryOptionalContextExpression,
    ValueBinaryOptionalContextExpression,
    ValueUnaryOptionalBoolExpression,
    ValueTernaryExpression,
    Mkdir,
    Touch,
    Explode,
    SubstrCompare,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PhpBuiltin {
    pub php_name: &'static str,
    pub symbol: &'static str,
    pub helper_symbol: Option<&'static str>,
    pub signature: RuntimeSignature,
    pub lowering: BuiltinLowering,
    pub codegen: BuiltinCodegen,
}

impl PhpBuiltin {
    pub fn llvm_decl(self) -> String {
        self.signature.llvm_decl(self.symbol)
    }
}

pub const PHP_RUNTIME_HELPERS: &[(&str, RuntimeSignature)] =
    &[("echo_php_ob_start_value", RuntimeSignature::BoolEchoValue)];

pub const PHP_BUILTINS: &[PhpBuiltin] = &[
    PhpBuiltin {
        php_name: "abs",
        symbol: "echo_php_abs",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "flush",
        symbol: "echo_php_flush",
        helper_symbol: None,
        signature: RuntimeSignature::VoidNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::VoidStatement,
    },
    PhpBuiltin {
        php_name: "define",
        symbol: "echo_php_define",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "microtime",
        symbol: "echo_php_microtime",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "ob_implicit_flush",
        symbol: "echo_php_ob_implicit_flush",
        helper_symbol: None,
        signature: RuntimeSignature::VoidEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::VoidUnaryStatement,
    },
    PhpBuiltin {
        php_name: "ob_start",
        symbol: "echo_php_ob_start",
        helper_symbol: Some("echo_php_ob_start_value"),
        signature: RuntimeSignature::BoolNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ObStart,
    },
    PhpBuiltin {
        php_name: "ob_flush",
        symbol: "echo_php_ob_flush",
        helper_symbol: None,
        signature: RuntimeSignature::BoolNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::BoolStatement,
    },
    PhpBuiltin {
        php_name: "ob_clean",
        symbol: "echo_php_ob_clean",
        helper_symbol: None,
        signature: RuntimeSignature::BoolNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::BoolStatement,
    },
    PhpBuiltin {
        php_name: "ob_end_flush",
        symbol: "echo_php_ob_end_flush",
        helper_symbol: None,
        signature: RuntimeSignature::BoolNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::BoolStatement,
    },
    PhpBuiltin {
        php_name: "ob_end_clean",
        symbol: "echo_php_ob_end_clean",
        helper_symbol: None,
        signature: RuntimeSignature::BoolNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::BoolStatement,
    },
    PhpBuiltin {
        php_name: "ob_get_clean",
        symbol: "echo_php_ob_get_clean",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueExpression,
    },
    PhpBuiltin {
        php_name: "ob_get_contents",
        symbol: "echo_php_ob_get_contents",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueExpression,
    },
    PhpBuiltin {
        php_name: "ob_get_flush",
        symbol: "echo_php_ob_get_flush",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueExpression,
    },
    PhpBuiltin {
        php_name: "ob_get_length",
        symbol: "echo_php_ob_get_length",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueExpression,
    },
    PhpBuiltin {
        php_name: "ob_get_level",
        symbol: "echo_php_ob_get_level",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueExpression,
    },
    PhpBuiltin {
        php_name: "strlen",
        symbol: "echo_php_strlen",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "count",
        symbol: "echo_php_count",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "array_values",
        symbol: "echo_php_array_values",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "array_keys",
        symbol: "echo_php_array_keys",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ArrayKeys,
    },
    PhpBuiltin {
        php_name: "array_fill",
        symbol: "echo_php_array_fill",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueTernaryExpression,
    },
    PhpBuiltin {
        php_name: "array_fill_keys",
        symbol: "echo_php_array_fill_keys",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "array_combine",
        symbol: "echo_php_array_combine",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "array_pad",
        symbol: "echo_php_array_pad",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueTernaryExpression,
    },
    PhpBuiltin {
        php_name: "array_slice",
        symbol: "echo_php_array_slice",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ArraySlice,
    },
    PhpBuiltin {
        php_name: "array_chunk",
        symbol: "echo_php_array_chunk",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::InArray,
    },
    PhpBuiltin {
        php_name: "array_merge",
        symbol: "echo_php_array_merge",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ArrayMerge,
    },
    PhpBuiltin {
        php_name: "array_replace",
        symbol: "echo_php_array_replace",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ArrayReplace,
    },
    PhpBuiltin {
        php_name: "array_reverse",
        symbol: "echo_php_array_reverse",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ArrayReverse,
    },
    PhpBuiltin {
        php_name: "array_flip",
        symbol: "echo_php_array_flip",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "array_count_values",
        symbol: "echo_php_array_count_values",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "array_key_exists",
        symbol: "echo_php_array_key_exists",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "key_exists",
        symbol: "echo_php_array_key_exists",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "array_key_first",
        symbol: "echo_php_array_key_first",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "array_key_last",
        symbol: "echo_php_array_key_last",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "in_array",
        symbol: "echo_php_in_array",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::InArray,
    },
    PhpBuiltin {
        php_name: "array_search",
        symbol: "echo_php_array_search",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::InArray,
    },
    PhpBuiltin {
        php_name: "array_sum",
        symbol: "echo_php_array_sum",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "array_product",
        symbol: "echo_php_array_product",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "sizeof",
        symbol: "echo_php_count",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "function_exists",
        symbol: "echo_php_function_exists",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "gettype",
        symbol: "echo_php_gettype",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "array_is_list",
        symbol: "echo_php_array_is_list",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_array",
        symbol: "echo_php_is_array",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_countable",
        symbol: "echo_php_is_countable",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_iterable",
        symbol: "echo_php_is_iterable",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_numeric",
        symbol: "echo_php_is_numeric",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_null",
        symbol: "echo_php_is_null",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_bool",
        symbol: "echo_php_is_bool",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_callable",
        symbol: "echo_php_is_callable",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_int",
        symbol: "echo_php_is_int",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_integer",
        symbol: "echo_php_is_int",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_long",
        symbol: "echo_php_is_int",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_float",
        symbol: "echo_php_is_float",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_double",
        symbol: "echo_php_is_float",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_finite",
        symbol: "echo_php_is_finite",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_infinite",
        symbol: "echo_php_is_infinite",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_nan",
        symbol: "echo_php_is_nan",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_object",
        symbol: "echo_php_is_object",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_resource",
        symbol: "echo_php_is_resource",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_string",
        symbol: "echo_php_is_string",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_scalar",
        symbol: "echo_php_is_scalar",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "strval",
        symbol: "echo_php_strval",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "boolval",
        symbol: "echo_php_boolval",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "intval",
        symbol: "echo_php_intval",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "floatval",
        symbol: "echo_php_floatval",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "doubleval",
        symbol: "echo_php_floatval",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "strtoupper",
        symbol: "echo_php_strtoupper",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "strtolower",
        symbol: "echo_php_strtolower",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "ucwords",
        symbol: "echo_php_ucwords",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "strrev",
        symbol: "echo_php_strrev",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "ucfirst",
        symbol: "echo_php_ucfirst",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "lcfirst",
        symbol: "echo_php_lcfirst",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "ord",
        symbol: "echo_php_ord",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "str_rot13",
        symbol: "echo_php_str_rot13",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "chr",
        symbol: "echo_php_chr",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "decbin",
        symbol: "echo_php_decbin",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "dechex",
        symbol: "echo_php_dechex",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "decoct",
        symbol: "echo_php_decoct",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "crc32",
        symbol: "echo_php_crc32",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "bindec",
        symbol: "echo_php_bindec",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "hexdec",
        symbol: "echo_php_hexdec",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "octdec",
        symbol: "echo_php_octdec",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "base_convert",
        symbol: "echo_php_base_convert",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueTernaryExpression,
    },
    PhpBuiltin {
        php_name: "deg2rad",
        symbol: "echo_php_deg2rad",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "rad2deg",
        symbol: "echo_php_rad2deg",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "sin",
        symbol: "echo_php_sin",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "cos",
        symbol: "echo_php_cos",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "tan",
        symbol: "echo_php_tan",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "asin",
        symbol: "echo_php_asin",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "acos",
        symbol: "echo_php_acos",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "atan",
        symbol: "echo_php_atan",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "atan2",
        symbol: "echo_php_atan2",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "sinh",
        symbol: "echo_php_sinh",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "cosh",
        symbol: "echo_php_cosh",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "tanh",
        symbol: "echo_php_tanh",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "asinh",
        symbol: "echo_php_asinh",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "acosh",
        symbol: "echo_php_acosh",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "atanh",
        symbol: "echo_php_atanh",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "ceil",
        symbol: "echo_php_ceil",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "floor",
        symbol: "echo_php_floor",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "sqrt",
        symbol: "echo_php_sqrt",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "exp",
        symbol: "echo_php_exp",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "expm1",
        symbol: "echo_php_expm1",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "log",
        symbol: "echo_php_log",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Log,
    },
    PhpBuiltin {
        php_name: "log10",
        symbol: "echo_php_log10",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "log1p",
        symbol: "echo_php_log1p",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "pow",
        symbol: "echo_php_pow",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "hypot",
        symbol: "echo_php_hypot",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "pi",
        symbol: "echo_php_pi",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueExpression,
    },
    PhpBuiltin {
        php_name: "fmod",
        symbol: "echo_php_fmod",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "bin2hex",
        symbol: "echo_php_bin2hex",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "md5",
        symbol: "echo_php_md5",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryOptionalBoolExpression,
    },
    PhpBuiltin {
        php_name: "sha1",
        symbol: "echo_php_sha1",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryOptionalBoolExpression,
    },
    PhpBuiltin {
        php_name: "base64_encode",
        symbol: "echo_php_base64_encode",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "base64_decode",
        symbol: "echo_php_base64_decode",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "rawurlencode",
        symbol: "echo_php_rawurlencode",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "rawurldecode",
        symbol: "echo_php_rawurldecode",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "urlencode",
        symbol: "echo_php_urlencode",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "urldecode",
        symbol: "echo_php_urldecode",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "basename",
        symbol: "echo_php_basename",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Basename,
    },
    PhpBuiltin {
        php_name: "dirname",
        symbol: "echo_php_dirname",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Dirname,
    },
    PhpBuiltin {
        php_name: "hex2bin",
        symbol: "echo_php_hex2bin",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "escapeshellarg",
        symbol: "echo_php_escapeshellarg",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "escapeshellcmd",
        symbol: "echo_php_escapeshellcmd",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "explode",
        symbol: "echo_php_explode",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Explode,
    },
    PhpBuiltin {
        php_name: "implode",
        symbol: "echo_php_implode",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Implode,
    },
    PhpBuiltin {
        php_name: "join",
        symbol: "echo_php_implode",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Implode,
    },
    PhpBuiltin {
        php_name: "file_exists",
        symbol: "echo_php_file_exists",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "chdir",
        symbol: "echo_php_chdir",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "getcwd",
        symbol: "echo_php_getcwd",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueNoArgs,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueExpression,
    },
    PhpBuiltin {
        php_name: "is_dir",
        symbol: "echo_php_is_dir",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_file",
        symbol: "echo_php_is_file",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_link",
        symbol: "echo_php_is_link",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_readable",
        symbol: "echo_php_is_readable",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_writable",
        symbol: "echo_php_is_writable",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_writeable",
        symbol: "echo_php_is_writable",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "is_executable",
        symbol: "echo_php_is_executable",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "filesize",
        symbol: "echo_php_filesize",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "fileatime",
        symbol: "echo_php_fileatime",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "filectime",
        symbol: "echo_php_filectime",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "filemtime",
        symbol: "echo_php_filemtime",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "fileinode",
        symbol: "echo_php_fileinode",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "fileowner",
        symbol: "echo_php_fileowner",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "filegroup",
        symbol: "echo_php_filegroup",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "fileperms",
        symbol: "echo_php_fileperms",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "filetype",
        symbol: "echo_php_filetype",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "touch",
        symbol: "echo_php_touch",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Touch,
    },
    PhpBuiltin {
        php_name: "copy",
        symbol: "echo_php_copy",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryOptionalContextExpression,
    },
    PhpBuiltin {
        php_name: "rename",
        symbol: "echo_php_rename",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryOptionalContextExpression,
    },
    PhpBuiltin {
        php_name: "unlink",
        symbol: "echo_php_unlink",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryOptionalContextExpression,
    },
    PhpBuiltin {
        php_name: "mkdir",
        symbol: "echo_php_mkdir",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::Mkdir,
    },
    PhpBuiltin {
        php_name: "rmdir",
        symbol: "echo_php_rmdir",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryOptionalContextExpression,
    },
    PhpBuiltin {
        php_name: "realpath",
        symbol: "echo_php_realpath",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "trim",
        symbol: "echo_php_trim",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "ltrim",
        symbol: "echo_php_ltrim",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "rtrim",
        symbol: "echo_php_rtrim",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "addslashes",
        symbol: "echo_php_addslashes",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "stripslashes",
        symbol: "echo_php_stripslashes",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "quotemeta",
        symbol: "echo_php_quotemeta",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueUnaryExpression,
    },
    PhpBuiltin {
        php_name: "str_contains",
        symbol: "echo_php_str_contains",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "str_starts_with",
        symbol: "echo_php_str_starts_with",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "str_ends_with",
        symbol: "echo_php_str_ends_with",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "str_repeat",
        symbol: "echo_php_str_repeat",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "str_pad",
        symbol: "echo_php_str_pad",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::StrPad,
    },
    PhpBuiltin {
        php_name: "str_split",
        symbol: "echo_php_str_split",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::StrSplit,
    },
    PhpBuiltin {
        php_name: "chunk_split",
        symbol: "echo_php_chunk_split",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ChunkSplit,
    },
    PhpBuiltin {
        php_name: "substr",
        symbol: "echo_php_substr",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "strpos",
        symbol: "echo_php_strpos",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "stripos",
        symbol: "echo_php_stripos",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "strrpos",
        symbol: "echo_php_strrpos",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "strripos",
        symbol: "echo_php_strripos",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "strstr",
        symbol: "echo_php_strstr",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "strchr",
        symbol: "echo_php_strstr",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "stristr",
        symbol: "echo_php_stristr",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "strrchr",
        symbol: "echo_php_strrchr",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "strpbrk",
        symbol: "echo_php_strpbrk",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "strspn",
        symbol: "echo_php_strspn",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "strcspn",
        symbol: "echo_php_strcspn",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "substr_count",
        symbol: "echo_php_substr_count",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "substr_compare",
        symbol: "echo_php_substr_compare",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::SubstrCompare,
    },
    PhpBuiltin {
        php_name: "strcmp",
        symbol: "echo_php_strcmp",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "strcasecmp",
        symbol: "echo_php_strcasecmp",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueBinaryExpression,
    },
    PhpBuiltin {
        php_name: "strncmp",
        symbol: "echo_php_strncmp",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueTernaryExpression,
    },
    PhpBuiltin {
        php_name: "strncasecmp",
        symbol: "echo_php_strncasecmp",
        helper_symbol: None,
        signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
        lowering: BuiltinLowering::DirectRuntimeCall,
        codegen: BuiltinCodegen::ValueTernaryExpression,
    },
];

pub fn php_builtin(name: &str) -> Option<PhpBuiltin> {
    PHP_BUILTINS
        .iter()
        .copied()
        .find(|builtin| builtin.php_name == name)
}
