use super::RuntimeSignature;
use std::sync::LazyLock;

mod array_entries;
mod crypto_entries;
mod filesystem_entries;
mod math_entries;
mod string_entries;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuiltinLowering {
    DirectRuntimeCall,
    #[allow(dead_code)]
    GenericRuntimeCall,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuiltinCodegen {
    ArrayKeys,
    ArrayMerge,
    ArrayReplace,
    ArrayReverse,
    ArraySlice,
    Basename,
    Clearstatcache,
    Dirname,
    ChunkSplit,
    Getenv,
    Gettimeofday,
    Header,
    HeaderRemove,
    Hrtime,
    HttpResponseCode,
    IgnoreUserAbort,
    IniGetAll,
    ValueOptionalBoolExpression,
    InArray,
    Implode,
    Levenshtein,
    Log,
    Nl2br,
    NumberFormat,
    Pathinfo,
    PhpVersion,
    Round,
    ObStart,
    StrPad,
    StrSplit,
    StreamGetContents,
    VoidStatement,
    VoidUnaryStatement,
    BoolStatement,
    ValueExpression,
    ValueOptionalNullExpression,
    ValueUnaryExpression,
    ValueUnaryOptionalNullExpression,
    ValueBinaryExpression,
    ValueBinaryOptionalNullExpression,
    ValueBinaryOptionalIntOneExpression,
    ValueBinaryOptionalBoolExpression,
    ValueUnaryOptionalContextExpression,
    ValueBinaryOptionalContextExpression,
    ValueUnaryOptionalBoolExpression,
    ValueUnaryOptionalTrueBoolExpression,
    ValueTernaryOptionalBoolExpression,
    ValueUnaryOptionalBoolContextExpression,
    ValueTernaryExpression,
    ValueQuinaryOptionalBoolExpression,
    ValueQuaternaryExpression,
    ValueQuinaryExpression,
    ValueSixExpression,
    FileGetContents,
    FilePutContents,
    Mkdir,
    Touch,
    Uniqid,
    Explode,
    SubstrCompare,
    SubstrReplace,
    Wordwrap,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PhpBuiltin {
    pub php_name: &'static str,
    pub symbol: &'static str,
    pub helper_symbol: Option<&'static str>,
    pub signature: RuntimeSignature,
    pub lowering: BuiltinLowering,
    pub codegen: BuiltinCodegen,
}

impl PhpBuiltin {
    pub fn llvm_decl(self) -> String {
        self.signature.llvm_decl(self.symbol)
    }
}

pub const PHP_RUNTIME_HELPERS: &[(&str, RuntimeSignature)] = &[
    (
        "echo_php_register_included_file",
        RuntimeSignature::VoidEchoValue,
    ),
    ("echo_php_ob_start_value", RuntimeSignature::BoolEchoValue),
];

pub static PHP_BUILTINS: LazyLock<Vec<PhpBuiltin>> = LazyLock::new(|| {
    let mut builtins = vec![
        PhpBuiltin {
            php_name: "abs",
            symbol: "echo_php_abs",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "flush",
            symbol: "echo_php_flush",
            helper_symbol: None,
            signature: RuntimeSignature::VoidNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::VoidStatement,
        },
        PhpBuiltin {
            php_name: "constant",
            symbol: "echo_php_constant",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "define",
            symbol: "echo_php_define",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "defined",
            symbol: "echo_php_defined",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "gettimeofday",
            symbol: "echo_php_gettimeofday",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::Gettimeofday,
        },
        PhpBuiltin {
            php_name: "get_error_handler",
            symbol: "echo_php_get_error_handler",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "get_exception_handler",
            symbol: "echo_php_get_exception_handler",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "set_error_handler",
            symbol: "echo_php_set_error_handler",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "restore_error_handler",
            symbol: "echo_php_restore_error_handler",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "set_exception_handler",
            symbol: "echo_php_set_exception_handler",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "restore_exception_handler",
            symbol: "echo_php_restore_exception_handler",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "microtime",
            symbol: "echo_php_microtime",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "sleep",
            symbol: "echo_php_sleep",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "usleep",
            symbol: "echo_php_usleep",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "time_nanosleep",
            symbol: "echo_php_time_nanosleep",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "time_sleep_until",
            symbol: "echo_php_time_sleep_until",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "set_time_limit",
            symbol: "echo_php_set_time_limit",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "sys_getloadavg",
            symbol: "echo_php_sys_getloadavg",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "hrtime",
            symbol: "echo_php_hrtime",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::Hrtime,
        },
        PhpBuiltin {
            php_name: "cli_get_process_title",
            symbol: "echo_php_cli_get_process_title",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "cli_set_process_title",
            symbol: "echo_php_cli_set_process_title",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "phpversion",
            symbol: "echo_php_phpversion",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::PhpVersion,
        },
        PhpBuiltin {
            php_name: "php_sapi_name",
            symbol: "echo_php_php_sapi_name",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "phpcredits",
            symbol: "echo_php_phpcredits",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "phpinfo",
            symbol: "echo_php_phpinfo",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "php_uname",
            symbol: "echo_php_php_uname",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "zend_version",
            symbol: "echo_php_zend_version",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "dl",
            symbol: "echo_php_dl",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "extension_loaded",
            symbol: "echo_php_extension_loaded",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "get_loaded_extensions",
            symbol: "echo_php_get_loaded_extensions",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueOptionalBoolExpression,
        },
        PhpBuiltin {
            php_name: "get_extension_funcs",
            symbol: "echo_php_get_extension_funcs",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "get_cfg_var",
            symbol: "echo_php_get_cfg_var",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "ini_get",
            symbol: "echo_php_ini_get",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "ini_get_all",
            symbol: "echo_php_ini_get_all",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::IniGetAll,
        },
        PhpBuiltin {
            php_name: "ini_parse_quantity",
            symbol: "echo_php_ini_parse_quantity",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "get_include_path",
            symbol: "echo_php_get_include_path",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "set_include_path",
            symbol: "echo_php_set_include_path",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "get_included_files",
            symbol: "echo_php_get_included_files",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "get_required_files",
            symbol: "echo_php_get_required_files",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "connection_aborted",
            symbol: "echo_php_connection_aborted",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "connection_status",
            symbol: "echo_php_connection_status",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "ignore_user_abort",
            symbol: "echo_php_ignore_user_abort",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::IgnoreUserAbort,
        },
        PhpBuiltin {
            php_name: "headers_list",
            symbol: "echo_php_headers_list",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "headers_sent",
            symbol: "echo_php_headers_sent",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "http_get_last_response_headers",
            symbol: "echo_php_http_get_last_response_headers",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "http_clear_last_response_headers",
            symbol: "echo_php_http_clear_last_response_headers",
            helper_symbol: None,
            signature: RuntimeSignature::VoidNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::VoidStatement,
        },
        PhpBuiltin {
            php_name: "header",
            symbol: "echo_php_header",
            helper_symbol: None,
            signature: RuntimeSignature::VoidEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::Header,
        },
        PhpBuiltin {
            php_name: "header_remove",
            symbol: "echo_php_header_remove",
            helper_symbol: None,
            signature: RuntimeSignature::VoidEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::HeaderRemove,
        },
        PhpBuiltin {
            php_name: "http_response_code",
            symbol: "echo_php_http_response_code",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::HttpResponseCode,
        },
        PhpBuiltin {
            php_name: "http_build_query",
            symbol: "echo_php_http_build_query",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueQuaternaryExpression,
        },
        PhpBuiltin {
            php_name: "mail",
            symbol: "echo_php_mail",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueTernaryExpression,
        },
        PhpBuiltin {
            php_name: "ip2long",
            symbol: "echo_php_ip2long",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "long2ip",
            symbol: "echo_php_long2ip",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "inet_pton",
            symbol: "echo_php_inet_pton",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "inet_ntop",
            symbol: "echo_php_inet_ntop",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "image_type_to_extension",
            symbol: "echo_php_image_type_to_extension",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryOptionalTrueBoolExpression,
        },
        PhpBuiltin {
            php_name: "image_type_to_mime_type",
            symbol: "echo_php_image_type_to_mime_type",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "ini_set",
            symbol: "echo_php_ini_set",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "ini_alter",
            symbol: "echo_php_ini_alter",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "ini_restore",
            symbol: "echo_php_ini_restore",
            helper_symbol: None,
            signature: RuntimeSignature::VoidEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::VoidUnaryStatement,
        },
        PhpBuiltin {
            php_name: "php_ini_loaded_file",
            symbol: "echo_php_php_ini_loaded_file",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "php_ini_scanned_files",
            symbol: "echo_php_php_ini_scanned_files",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "getenv",
            symbol: "echo_php_getenv",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::Getenv,
        },
        PhpBuiltin {
            php_name: "openlog",
            symbol: "echo_php_openlog",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueTernaryExpression,
        },
        PhpBuiltin {
            php_name: "syslog",
            symbol: "echo_php_syslog",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "closelog",
            symbol: "echo_php_closelog",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "gethostname",
            symbol: "echo_php_gethostname",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "gethostbyname",
            symbol: "echo_php_gethostbyname",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "gethostbynamel",
            symbol: "echo_php_gethostbynamel",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "gethostbyaddr",
            symbol: "echo_php_gethostbyaddr",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "getprotobyname",
            symbol: "echo_php_getprotobyname",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "getprotobynumber",
            symbol: "echo_php_getprotobynumber",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "getservbyname",
            symbol: "echo_php_getservbyname",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "getservbyport",
            symbol: "echo_php_getservbyport",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "getrusage",
            symbol: "echo_php_getrusage",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "memory_get_usage",
            symbol: "echo_php_memory_get_usage",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "memory_get_peak_usage",
            symbol: "echo_php_memory_get_peak_usage",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "memory_reset_peak_usage",
            symbol: "echo_php_memory_reset_peak_usage",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "get_current_user",
            symbol: "echo_php_get_current_user",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "getmypid",
            symbol: "echo_php_getmypid",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "getmyuid",
            symbol: "echo_php_getmyuid",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "getmygid",
            symbol: "echo_php_getmygid",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "getmyinode",
            symbol: "echo_php_getmyinode",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "getlastmod",
            symbol: "echo_php_getlastmod",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "putenv",
            symbol: "echo_php_putenv",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "ob_implicit_flush",
            symbol: "echo_php_ob_implicit_flush",
            helper_symbol: None,
            signature: RuntimeSignature::VoidEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::VoidUnaryStatement,
        },
        PhpBuiltin {
            php_name: "ob_start",
            symbol: "echo_php_ob_start",
            helper_symbol: Some("echo_php_ob_start_value"),
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ObStart,
        },
        PhpBuiltin {
            php_name: "ob_flush",
            symbol: "echo_php_ob_flush",
            helper_symbol: None,
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::BoolStatement,
        },
        PhpBuiltin {
            php_name: "ob_clean",
            symbol: "echo_php_ob_clean",
            helper_symbol: None,
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::BoolStatement,
        },
        PhpBuiltin {
            php_name: "ob_end_flush",
            symbol: "echo_php_ob_end_flush",
            helper_symbol: None,
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::BoolStatement,
        },
        PhpBuiltin {
            php_name: "ob_end_clean",
            symbol: "echo_php_ob_end_clean",
            helper_symbol: None,
            signature: RuntimeSignature::BoolNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::BoolStatement,
        },
        PhpBuiltin {
            php_name: "ob_get_clean",
            symbol: "echo_php_ob_get_clean",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "ob_get_contents",
            symbol: "echo_php_ob_get_contents",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "ob_get_flush",
            symbol: "echo_php_ob_get_flush",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "ob_get_length",
            symbol: "echo_php_ob_get_length",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "ob_get_level",
            symbol: "echo_php_ob_get_level",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "ob_get_status",
            symbol: "echo_php_ob_get_status",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueOptionalBoolExpression,
        },
        PhpBuiltin {
            php_name: "ob_list_handlers",
            symbol: "echo_php_ob_list_handlers",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "output_reset_rewrite_vars",
            symbol: "echo_php_output_reset_rewrite_vars",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "output_add_rewrite_var",
            symbol: "echo_php_output_add_rewrite_var",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
    ];
    builtins.extend_from_slice(array_entries::ARRAY_BUILTINS);
    builtins.extend_from_slice(filesystem_entries::FILESYSTEM_BUILTINS);
    builtins.extend_from_slice(crypto_entries::CRYPTO_BUILTINS);
    builtins.extend_from_slice(&[
        PhpBuiltin {
            php_name: "error_reporting",
            symbol: "echo_php_error_reporting",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueOptionalNullExpression,
        },
        PhpBuiltin {
            php_name: "error_get_last",
            symbol: "echo_php_error_get_last",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "error_clear_last",
            symbol: "echo_php_error_clear_last",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "error_log",
            symbol: "echo_php_error_log",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "trigger_error",
            symbol: "echo_php_trigger_error",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "user_error",
            symbol: "echo_php_user_error",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "gc_collect_cycles",
            symbol: "echo_php_gc_collect_cycles",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "gc_disable",
            symbol: "echo_php_gc_disable",
            helper_symbol: None,
            signature: RuntimeSignature::VoidNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::VoidStatement,
        },
        PhpBuiltin {
            php_name: "gc_enable",
            symbol: "echo_php_gc_enable",
            helper_symbol: None,
            signature: RuntimeSignature::VoidNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::VoidStatement,
        },
        PhpBuiltin {
            php_name: "gc_enabled",
            symbol: "echo_php_gc_enabled",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "gc_mem_caches",
            symbol: "echo_php_gc_mem_caches",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "gc_status",
            symbol: "echo_php_gc_status",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "class_exists",
            symbol: "echo_php_class_exists",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryOptionalBoolExpression,
        },
        PhpBuiltin {
            php_name: "interface_exists",
            symbol: "echo_php_interface_exists",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryOptionalBoolExpression,
        },
        PhpBuiltin {
            php_name: "trait_exists",
            symbol: "echo_php_trait_exists",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryOptionalBoolExpression,
        },
        PhpBuiltin {
            php_name: "enum_exists",
            symbol: "echo_php_enum_exists",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryOptionalBoolExpression,
        },
        PhpBuiltin {
            php_name: "method_exists",
            symbol: "echo_php_method_exists",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "property_exists",
            symbol: "echo_php_property_exists",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryExpression,
        },
        PhpBuiltin {
            php_name: "is_a",
            symbol: "echo_php_is_a",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryOptionalBoolExpression,
        },
        PhpBuiltin {
            php_name: "is_subclass_of",
            symbol: "echo_php_is_subclass_of",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValueEchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueBinaryOptionalBoolExpression,
        },
        PhpBuiltin {
            php_name: "function_exists",
            symbol: "echo_php_function_exists",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "get_declared_classes",
            symbol: "echo_php_get_declared_classes",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "get_declared_interfaces",
            symbol: "echo_php_get_declared_interfaces",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "get_declared_traits",
            symbol: "echo_php_get_declared_traits",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "debug_backtrace",
            symbol: "echo_php_debug_backtrace",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueExpression,
        },
        PhpBuiltin {
            php_name: "debug_print_backtrace",
            symbol: "echo_php_debug_print_backtrace",
            helper_symbol: None,
            signature: RuntimeSignature::VoidNoArgs,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::VoidStatement,
        },
        PhpBuiltin {
            php_name: "get_defined_constants",
            symbol: "echo_php_get_defined_constants",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueOptionalBoolExpression,
        },
        PhpBuiltin {
            php_name: "get_defined_functions",
            symbol: "echo_php_get_defined_functions",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueOptionalBoolExpression,
        },
        PhpBuiltin {
            php_name: "gettype",
            symbol: "echo_php_gettype",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "get_debug_type",
            symbol: "echo_php_get_debug_type",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "array_is_list",
            symbol: "echo_php_array_is_list",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_array",
            symbol: "echo_php_is_array",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_countable",
            symbol: "echo_php_is_countable",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_iterable",
            symbol: "echo_php_is_iterable",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_numeric",
            symbol: "echo_php_is_numeric",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_null",
            symbol: "echo_php_is_null",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_bool",
            symbol: "echo_php_is_bool",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_callable",
            symbol: "echo_php_is_callable",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_int",
            symbol: "echo_php_is_int",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_integer",
            symbol: "echo_php_is_int",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_long",
            symbol: "echo_php_is_int",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_float",
            symbol: "echo_php_is_float",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_double",
            symbol: "echo_php_is_float",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_finite",
            symbol: "echo_php_is_finite",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_infinite",
            symbol: "echo_php_is_infinite",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_nan",
            symbol: "echo_php_is_nan",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_object",
            symbol: "echo_php_is_object",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_resource",
            symbol: "echo_php_is_resource",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "get_resource_type",
            symbol: "echo_php_get_resource_type",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "get_resource_id",
            symbol: "echo_php_get_resource_id",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "get_resources",
            symbol: "echo_php_get_resources",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueOptionalNullExpression,
        },
        PhpBuiltin {
            php_name: "serialize",
            symbol: "echo_php_serialize",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_string",
            symbol: "echo_php_is_string",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "is_scalar",
            symbol: "echo_php_is_scalar",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "strval",
            symbol: "echo_php_strval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "boolval",
            symbol: "echo_php_boolval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "intval",
            symbol: "echo_php_intval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "floatval",
            symbol: "echo_php_floatval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
        PhpBuiltin {
            php_name: "doubleval",
            symbol: "echo_php_floatval",
            helper_symbol: None,
            signature: RuntimeSignature::EchoValueEchoValue,
            lowering: BuiltinLowering::DirectRuntimeCall,
            codegen: BuiltinCodegen::ValueUnaryExpression,
        },
    ]);
    builtins.extend_from_slice(math_entries::MATH_BUILTINS);
    builtins.extend_from_slice(string_entries::STRING_BUILTINS);
    builtins
});

pub fn php_builtin(name: &str) -> Option<PhpBuiltin> {
    PHP_BUILTINS
        .iter()
        .copied()
        .find(|builtin| builtin.php_name == name)
}
