#!/usr/bin/env bash
# Build the browser check host (echo_wasm) and emit JS bindings for www.
#
# This is the compiler frontend only (lex → parse → resolve → semantics).
# It does not ship LLVM or execute Echo in the browser.
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT_DIR="${ECHO_WASM_OUT:-$ROOT/www/public/echo-wasm}"
PROFILE="${ECHO_WASM_PROFILE:-release}"
TARGET="wasm32-unknown-unknown"
PKG="echo_wasm"

if ! command -v rustup >/dev/null 2>&1; then
  echo "build-wasm: rustup is required to add $TARGET" >&2
  exit 1
fi

if ! rustup target list --installed | grep -qx "$TARGET"; then
  echo "build-wasm: rustup target add $TARGET" >&2
  rustup target add "$TARGET"
fi

echo "build-wasm: cargo build -p $PKG --target $TARGET --$PROFILE" >&2
cargo build -p "$PKG" --target "$TARGET" --"$PROFILE"

WASM_IN="$ROOT/target/$TARGET/$PROFILE/${PKG}.wasm"
if [[ ! -f "$WASM_IN" ]]; then
  echo "build-wasm: missing $WASM_IN" >&2
  exit 1
fi

# wasm-bindgen CLI must match the crate version used to compile.
BINDGEN_VERSION="$(
  python3 - <<'PY'
import pathlib
text = pathlib.Path("Cargo.lock").read_text()
blocks = text.split("[[package]]")
for block in blocks:
    name = None
    version = None
    for line in block.splitlines():
        line = line.strip()
        if line.startswith("name = "):
            name = line.split("=", 1)[1].strip().strip('"')
        elif line.startswith("version = ") and version is None:
            version = line.split("=", 1)[1].strip().strip('"')
    if name == "wasm-bindgen" and version:
        print(version)
        break
else:
    raise SystemExit("wasm-bindgen version not found in Cargo.lock")
PY
)"

need_install=0
if ! command -v wasm-bindgen >/dev/null 2>&1; then
  need_install=1
else
  have="$(wasm-bindgen --version | awk '{print $NF}')"
  if [[ "$have" != "$BINDGEN_VERSION" ]]; then
    echo "build-wasm: wasm-bindgen $have != crate $BINDGEN_VERSION" >&2
    need_install=1
  fi
fi

if [[ "$need_install" -eq 1 ]]; then
  echo "build-wasm: cargo install wasm-bindgen-cli --version $BINDGEN_VERSION --locked" >&2
  cargo install wasm-bindgen-cli --version "$BINDGEN_VERSION" --locked --force
fi

mkdir -p "$OUT_DIR"
# Drop previous bindings so renamed artifacts cannot linger.
rm -f "$OUT_DIR"/*.js "$OUT_DIR"/*.d.ts "$OUT_DIR"/*.wasm "$OUT_DIR"/*.json

echo "build-wasm: wasm-bindgen --target web → $OUT_DIR" >&2
wasm-bindgen "$WASM_IN" \
  --target web \
  --out-dir "$OUT_DIR" \
  --out-name echo_wasm

test -f "$OUT_DIR/echo_wasm.js"
test -f "$OUT_DIR/echo_wasm_bg.wasm"

# Tiny loader note used by the site when someone opens the directory.
cat > "$OUT_DIR/README.md" <<'EOF'
Generated by `just wasm` / `scripts/build-wasm.sh`. Do not edit.
Browser check host (frontend only). Reload `/try` after rebuilding.
EOF

python3 - <<PY
from pathlib import Path
root = Path("$OUT_DIR")
total = sum(p.stat().st_size for p in root.iterdir() if p.is_file())
print(f"build-wasm: ok  {root}  ({total / (1024 * 1024):.1f} MiB)")
PY
