use crate::{FunctionReflection, FunctionSource, ParamReflection};

pub(crate) fn reflections() -> Vec<FunctionReflection> {
    [
        php_builtin_reflection("abs", &[("num", Some("int|float"))], Some("int|float")),
        php_builtin_reflection(
            "array_change_key_case",
            &[("array", Some("array")), ("case", Some("int"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_diff",
            &[("array", Some("array")), ("arrays", Some("array"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_diff_assoc",
            &[("array", Some("array")), ("arrays", Some("array"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_column",
            &[
                ("array", Some("array")),
                ("column_key", Some("int|string|null")),
                ("index_key", Some("int|string|null")),
            ],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_filter",
            &[
                ("array", Some("array")),
                ("callback", Some("?callable")),
                ("mode", Some("int")),
            ],
            Some("array"),
        ),
        php_builtin_reflection("array_pop", &[("array", Some("array"))], Some("mixed")),
        php_builtin_reflection("current", &[("array", Some("array"))], Some("mixed")),
        php_builtin_reflection("pos", &[("array", Some("array"))], Some("mixed")),
        php_builtin_reflection("end", &[("array", Some("array"))], Some("mixed")),
        php_builtin_reflection("key", &[("array", Some("array"))], Some("int|string|null")),
        php_builtin_reflection("next", &[("array", Some("array"))], Some("mixed")),
        php_builtin_reflection("prev", &[("array", Some("array"))], Some("mixed")),
        php_builtin_reflection("reset", &[("array", Some("array"))], Some("mixed")),
        php_builtin_reflection(
            "array_push",
            &[("array", Some("array")), ("values", Some("mixed"))],
            Some("int"),
        ),
        php_builtin_reflection("array_shift", &[("array", Some("array"))], Some("mixed")),
        php_builtin_reflection(
            "array_unshift",
            &[("array", Some("array")), ("values", Some("mixed"))],
            Some("int"),
        ),
        php_builtin_reflection(
            "array_intersect",
            &[("array", Some("array")), ("arrays", Some("array"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_intersect_assoc",
            &[("array", Some("array")), ("arrays", Some("array"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_diff_key",
            &[("array", Some("array")), ("arrays", Some("array"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_intersect_key",
            &[("array", Some("array")), ("arrays", Some("array"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_unique",
            &[("array", Some("array")), ("flags", Some("int"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "debug_backtrace",
            &[("options", Some("int")), ("limit", Some("int"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "debug_print_backtrace",
            &[("options", Some("int")), ("limit", Some("int"))],
            Some("void"),
        ),
        php_builtin_reflection("flush", &[], Some("void")),
        php_builtin_reflection("constant", &[("name", Some("string"))], Some("mixed")),
        php_builtin_reflection(
            "define",
            &[("constant_name", Some("string")), ("value", Some("mixed"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "trigger_error",
            &[("message", Some("string")), ("error_level", Some("int"))],
            Some("true"),
        ),
        php_builtin_reflection(
            "user_error",
            &[("message", Some("string")), ("error_level", Some("int"))],
            Some("true"),
        ),
        php_builtin_reflection(
            "defined",
            &[("constant_name", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "crypt",
            &[("str", Some("string")), ("salt", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "hash",
            &[
                ("algo", Some("string")),
                ("data", Some("string")),
                ("raw_output", Some("bool")),
            ],
            Some("string|false"),
        ),
        php_builtin_reflection("hash_algos", &[], Some("array")),
        php_builtin_reflection(
            "hash_copy",
            &[("context", Some("object"))],
            Some("object|false"),
        ),
        php_builtin_reflection(
            "hash_equals",
            &[
                ("known_string", Some("string")),
                ("user_string", Some("string")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection(
            "hash_file",
            &[
                ("algo", Some("string")),
                ("filename", Some("string")),
                ("raw_output", Some("bool")),
            ],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "hash_final",
            &[("context", Some("object")), ("raw_output", Some("bool"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "hash_hkdf",
            &[
                ("algo", Some("string")),
                ("input_key_material", Some("string")),
                ("length", Some("int")),
                ("info", Some("string")),
                ("salt", Some("string")),
                ("raw_output", Some("bool")),
            ],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "hash_hmac",
            &[
                ("algo", Some("string")),
                ("data", Some("string")),
                ("key", Some("string")),
                ("raw_output", Some("bool")),
            ],
            Some("string|false"),
        ),
        php_builtin_reflection("hash_hmac_algos", &[], Some("array")),
        php_builtin_reflection(
            "hash_hmac_file",
            &[
                ("algo", Some("string")),
                ("filename", Some("string")),
                ("key", Some("string")),
                ("raw_output", Some("bool")),
            ],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "hash_init",
            &[
                ("algo", Some("string")),
                ("options", Some("int")),
                ("key", Some("string")),
            ],
            Some("object|false"),
        ),
        php_builtin_reflection(
            "hash_pbkdf2",
            &[
                ("algo", Some("string")),
                ("password", Some("string")),
                ("salt", Some("string")),
                ("iterations", Some("int")),
                ("length", Some("int")),
                ("raw_output", Some("bool")),
            ],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "hash_update",
            &[("context", Some("object")), ("data", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "hash_update_file",
            &[
                ("context", Some("object")),
                ("filename", Some("string")),
                ("context_resource", Some("resource")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection(
            "hash_update_stream",
            &[
                ("context", Some("object")),
                ("stream", Some("resource")),
                ("max_length", Some("?int")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection(
            "md5_file",
            &[
                ("filename", Some("string")),
                ("raw", Some("bool")),
                ("context", Some("resource")),
            ],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "sha1_file",
            &[
                ("filename", Some("string")),
                ("raw", Some("bool")),
                ("context", Some("resource")),
            ],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "microtime",
            &[("as_float", Some("bool"))],
            Some("string|float"),
        ),
        php_builtin_reflection("sleep", &[("seconds", Some("int"))], Some("int")),
        php_builtin_reflection("usleep", &[("microseconds", Some("int"))], Some("void")),
        php_builtin_reflection(
            "time_nanosleep",
            &[("seconds", Some("int")), ("nanoseconds", Some("int"))],
            Some("array|bool"),
        ),
        php_builtin_reflection(
            "time_sleep_until",
            &[("timestamp", Some("float"))],
            Some("bool"),
        ),
        php_builtin_reflection("set_time_limit", &[("seconds", Some("int"))], Some("bool")),
        php_builtin_reflection("sys_getloadavg", &[], Some("array|false")),
        php_builtin_reflection(
            "gettimeofday",
            &[("as_float", Some("bool"))],
            Some("array|float"),
        ),
        php_builtin_reflection("get_error_handler", &[], Some("?callable")),
        php_builtin_reflection("get_exception_handler", &[], Some("?callable")),
        php_builtin_reflection(
            "error_reporting",
            &[("error_level", Some("?int"))],
            Some("int"),
        ),
        php_builtin_reflection("error_get_last", &[], Some("?array")),
        php_builtin_reflection("error_clear_last", &[], Some("void")),
        php_builtin_reflection("error_log", &[("message", Some("string"))], Some("bool")),
        php_builtin_reflection("gc_collect_cycles", &[], Some("int")),
        php_builtin_reflection("gc_disable", &[], Some("void")),
        php_builtin_reflection("gc_enable", &[], Some("void")),
        php_builtin_reflection("gc_enabled", &[], Some("bool")),
        php_builtin_reflection("gc_mem_caches", &[], Some("int")),
        php_builtin_reflection("gc_status", &[], Some("array")),
        php_builtin_reflection(
            "class_exists",
            &[("class", Some("string")), ("autoload", Some("bool"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "interface_exists",
            &[("interface", Some("string")), ("autoload", Some("bool"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "trait_exists",
            &[("trait", Some("string")), ("autoload", Some("bool"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "enum_exists",
            &[("enum", Some("string")), ("autoload", Some("bool"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "method_exists",
            &[
                ("object_or_class", Some("object|string")),
                ("method", Some("string")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection(
            "property_exists",
            &[
                ("object_or_class", Some("object|string")),
                ("property", Some("string")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection(
            "is_a",
            &[
                ("object_or_class", Some("object|string")),
                ("class", Some("string")),
                ("allow_string", Some("bool")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection(
            "is_subclass_of",
            &[
                ("object_or_class", Some("object|string")),
                ("class", Some("string")),
                ("allow_string", Some("bool")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection(
            "set_error_handler",
            &[("callback", Some("?callable"))],
            Some("?callable"),
        ),
        php_builtin_reflection("restore_error_handler", &[], Some("bool")),
        php_builtin_reflection(
            "set_exception_handler",
            &[("callback", Some("?callable"))],
            Some("?callable"),
        ),
        php_builtin_reflection("restore_exception_handler", &[], Some("bool")),
        php_builtin_reflection(
            "get_defined_constants",
            &[("categorize", Some("bool"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "get_defined_functions",
            &[("exclude_disabled", Some("bool"))],
            Some("array"),
        ),
        php_builtin_reflection("get_declared_classes", &[], Some("array")),
        php_builtin_reflection("get_declared_interfaces", &[], Some("array")),
        php_builtin_reflection("get_declared_traits", &[], Some("array")),
        php_builtin_reflection(
            "hrtime",
            &[("as_number", Some("bool"))],
            Some("array|int|float"),
        ),
        php_builtin_reflection(
            "getenv",
            &[("name", Some("?string")), ("local_only", Some("bool"))],
            Some("string|array|false"),
        ),
        php_builtin_reflection(
            "openlog",
            &[
                ("prefix", Some("string")),
                ("flags", Some("int")),
                ("facility", Some("int")),
            ],
            Some("true"),
        ),
        php_builtin_reflection(
            "syslog",
            &[("priority", Some("int")), ("message", Some("string"))],
            Some("true"),
        ),
        php_builtin_reflection("closelog", &[], Some("true")),
        php_builtin_reflection("gethostname", &[], Some("string|false")),
        php_builtin_reflection(
            "gethostbyname",
            &[("hostname", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "gethostbynamel",
            &[("hostname", Some("string"))],
            Some("array|false"),
        ),
        php_builtin_reflection(
            "gethostbyaddr",
            &[("ip", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "getprotobyname",
            &[("protocol", Some("string"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "getprotobynumber",
            &[("protocol", Some("int"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "getservbyname",
            &[("service", Some("string")), ("protocol", Some("string"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "getservbyport",
            &[("port", Some("int")), ("protocol", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection("getrusage", &[], Some("array|false")),
        php_builtin_reflection("memory_get_usage", &[], Some("int")),
        php_builtin_reflection("memory_get_peak_usage", &[], Some("int")),
        php_builtin_reflection("memory_reset_peak_usage", &[], Some("void")),
        php_builtin_reflection("get_current_user", &[], Some("string")),
        php_builtin_reflection("getmypid", &[], Some("int|false")),
        php_builtin_reflection("getmyuid", &[], Some("int|false")),
        php_builtin_reflection("getmygid", &[], Some("int|false")),
        php_builtin_reflection("getmyinode", &[], Some("int|false")),
        php_builtin_reflection("getlastmod", &[], Some("int|false")),
        php_builtin_reflection("cli_get_process_title", &[], Some("?string")),
        php_builtin_reflection(
            "cli_set_process_title",
            &[("title", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "phpversion",
            &[("extension", Some("?string"))],
            Some("string|false"),
        ),
        php_builtin_reflection("php_sapi_name", &[], Some("string|false")),
        php_builtin_reflection("php_uname", &[("mode", Some("string"))], Some("string")),
        php_builtin_reflection("zend_version", &[], Some("string")),
        php_builtin_reflection(
            "dl",
            &[("extension_filename", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "extension_loaded",
            &[("extension", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "get_loaded_extensions",
            &[("zend_extensions", Some("bool"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "get_extension_funcs",
            &[("extension", Some("string"))],
            Some("array|false"),
        ),
        php_builtin_reflection(
            "get_cfg_var",
            &[("option", Some("string"))],
            Some("string|array|false"),
        ),
        php_builtin_reflection(
            "ini_get",
            &[("option", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "ini_get_all",
            &[("extension", Some("?string")), ("details", Some("bool"))],
            Some("array|false"),
        ),
        php_builtin_reflection(
            "ini_parse_quantity",
            &[("shorthand", Some("string"))],
            Some("int"),
        ),
        php_builtin_reflection("get_include_path", &[], Some("string|false")),
        php_builtin_reflection(
            "set_include_path",
            &[("include_path", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection("get_included_files", &[], Some("array")),
        php_builtin_reflection("get_required_files", &[], Some("array")),
        php_builtin_reflection("connection_aborted", &[], Some("int")),
        php_builtin_reflection("connection_status", &[], Some("int")),
        php_builtin_reflection(
            "ignore_user_abort",
            &[("enable", Some("?bool"))],
            Some("int"),
        ),
        php_builtin_reflection("headers_list", &[], Some("array")),
        php_builtin_reflection("headers_sent", &[], Some("bool")),
        php_builtin_reflection(
            "header",
            &[
                ("header", Some("string")),
                ("replace", Some("bool")),
                ("response_code", Some("int")),
            ],
            Some("void"),
        ),
        php_builtin_reflection("header_remove", &[("name", Some("?string"))], Some("void")),
        php_builtin_reflection(
            "http_response_code",
            &[("response_code", Some("int"))],
            Some("int|bool"),
        ),
        php_builtin_reflection(
            "mail",
            &[
                ("to", Some("string")),
                ("subject", Some("string")),
                ("message", Some("string")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection("ip2long", &[("ip", Some("string"))], Some("int|false")),
        php_builtin_reflection("long2ip", &[("ip", Some("int"))], Some("string")),
        php_builtin_reflection("inet_pton", &[("ip", Some("string"))], Some("string|false")),
        php_builtin_reflection("inet_ntop", &[("ip", Some("string"))], Some("string|false")),
        php_builtin_reflection(
            "ini_set",
            &[("option", Some("string")), ("value", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "ini_alter",
            &[("option", Some("string")), ("value", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection("ini_restore", &[("option", Some("string"))], Some("void")),
        php_builtin_reflection("php_ini_loaded_file", &[], Some("string|false")),
        php_builtin_reflection("php_ini_scanned_files", &[], Some("string|false")),
        php_builtin_reflection("putenv", &[("assignment", Some("string"))], Some("bool")),
        php_builtin_reflection(
            "ob_implicit_flush",
            &[("enable", Some("bool"))],
            Some("void"),
        ),
        php_builtin_reflection("ob_start", &[], Some("bool")),
        php_builtin_reflection("ob_flush", &[], Some("bool")),
        php_builtin_reflection("ob_clean", &[], Some("bool")),
        php_builtin_reflection("ob_end_flush", &[], Some("bool")),
        php_builtin_reflection("ob_end_clean", &[], Some("bool")),
        php_builtin_reflection("ob_get_clean", &[], Some("string|false")),
        php_builtin_reflection("ob_get_contents", &[], Some("string|false")),
        php_builtin_reflection("ob_get_flush", &[], Some("string|false")),
        php_builtin_reflection("ob_get_length", &[], Some("int|false")),
        php_builtin_reflection("ob_get_level", &[], Some("int")),
        php_builtin_reflection("ob_list_handlers", &[], Some("array")),
        php_builtin_reflection("strlen", &[("string", Some("string"))], Some("int")),
        php_builtin_reflection("str_word_count", &[("string", Some("string"))], Some("int")),
        php_builtin_reflection(
            "count_chars",
            &[("string", Some("string")), ("mode", Some("int"))],
            Some("array|string"),
        ),
        php_builtin_reflection(
            "basename",
            &[("path", Some("string")), ("suffix", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "dirname",
            &[("path", Some("string")), ("levels", Some("int"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "pathinfo",
            &[("path", Some("string")), ("flags", Some("int"))],
            Some("array|string"),
        ),
        php_builtin_reflection("count", &[("value", Some("Countable|array"))], Some("int")),
        php_builtin_reflection("sizeof", &[("value", Some("Countable|array"))], Some("int")),
        php_builtin_reflection("array_values", &[("array", Some("array"))], Some("array")),
        php_builtin_reflection(
            "array_keys",
            &[
                ("array", Some("array")),
                ("filter_value", Some("mixed")),
                ("strict", Some("bool")),
            ],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_fill",
            &[
                ("start_index", Some("int")),
                ("count", Some("int")),
                ("value", Some("mixed")),
            ],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_fill_keys",
            &[("keys", Some("array")), ("value", Some("mixed"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_combine",
            &[("keys", Some("array")), ("values", Some("array"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_pad",
            &[
                ("array", Some("array")),
                ("length", Some("int")),
                ("value", Some("mixed")),
            ],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_slice",
            &[
                ("array", Some("array")),
                ("offset", Some("int")),
                ("length", Some("?int")),
                ("preserve_keys", Some("bool")),
            ],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_splice",
            &[
                ("array", Some("array")),
                ("offset", Some("int")),
                ("length", Some("?int")),
                ("replacement", Some("mixed")),
            ],
            Some("array"),
        ),
        php_builtin_reflection(
            "sort",
            &[("array", Some("array")), ("flags", Some("int"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "rsort",
            &[("array", Some("array")), ("flags", Some("int"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "asort",
            &[("array", Some("array")), ("flags", Some("int"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "arsort",
            &[("array", Some("array")), ("flags", Some("int"))],
            Some("bool"),
        ),
        php_builtin_reflection("natsort", &[("array", Some("array"))], Some("bool")),
        php_builtin_reflection("natcasesort", &[("array", Some("array"))], Some("bool")),
        php_builtin_reflection(
            "ksort",
            &[("array", Some("array")), ("flags", Some("int"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "krsort",
            &[("array", Some("array")), ("flags", Some("int"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "array_chunk",
            &[
                ("array", Some("array")),
                ("length", Some("int")),
                ("preserve_keys", Some("bool")),
            ],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_merge",
            &[("...arrays", Some("array"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_replace",
            &[("array", Some("array")), ("...replacements", Some("array"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_reverse",
            &[("array", Some("array")), ("preserve_keys", Some("bool"))],
            Some("array"),
        ),
        php_builtin_reflection("array_flip", &[("array", Some("array"))], Some("array")),
        php_builtin_reflection(
            "array_count_values",
            &[("array", Some("array"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "array_key_exists",
            &[("key", Some("mixed")), ("array", Some("array"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "key_exists",
            &[("key", Some("mixed")), ("array", Some("array"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "array_key_first",
            &[("array", Some("array"))],
            Some("int|string|null"),
        ),
        php_builtin_reflection(
            "array_key_last",
            &[("array", Some("array"))],
            Some("int|string|null"),
        ),
        php_builtin_reflection("array_first", &[("array", Some("array"))], Some("mixed")),
        php_builtin_reflection("array_last", &[("array", Some("array"))], Some("mixed")),
        php_builtin_reflection(
            "in_array",
            &[
                ("needle", Some("mixed")),
                ("haystack", Some("array")),
                ("strict", Some("bool")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection(
            "array_search",
            &[
                ("needle", Some("mixed")),
                ("haystack", Some("array")),
                ("strict", Some("bool")),
            ],
            Some("int|string|false"),
        ),
        php_builtin_reflection("array_sum", &[("array", Some("array"))], Some("int|float")),
        php_builtin_reflection(
            "array_product",
            &[("array", Some("array"))],
            Some("int|float"),
        ),
        php_builtin_reflection(
            "function_exists",
            &[("function", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection("gettype", &[("value", Some("mixed"))], Some("string")),
        php_builtin_reflection(
            "get_debug_type",
            &[("value", Some("mixed"))],
            Some("string"),
        ),
        php_builtin_reflection("array_is_list", &[("array", Some("array"))], Some("bool")),
        php_builtin_reflection("is_array", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("is_countable", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("is_iterable", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("is_numeric", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("is_null", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("is_bool", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("is_callable", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("is_int", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("is_integer", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("is_long", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("is_float", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("is_double", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("is_finite", &[("num", Some("float"))], Some("bool")),
        php_builtin_reflection("is_infinite", &[("num", Some("float"))], Some("bool")),
        php_builtin_reflection("is_nan", &[("num", Some("float"))], Some("bool")),
        php_builtin_reflection("exp", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("expm1", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection(
            "log",
            &[("num", Some("float")), ("base", Some("float"))],
            Some("float"),
        ),
        php_builtin_reflection("log10", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("log1p", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection(
            "pow",
            &[("num", Some("mixed")), ("exponent", Some("mixed"))],
            Some("int|float|object"),
        ),
        php_builtin_reflection(
            "fdiv",
            &[("num1", Some("float")), ("num2", Some("float"))],
            Some("float"),
        ),
        php_builtin_reflection(
            "fpow",
            &[("num", Some("float")), ("exponent", Some("float"))],
            Some("float"),
        ),
        php_builtin_reflection("is_object", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("is_resource", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection(
            "get_resource_type",
            &[("resource", Some("resource"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "get_resource_id",
            &[("resource", Some("resource"))],
            Some("int"),
        ),
        php_builtin_reflection("get_resources", &[("type", Some("?string"))], Some("array")),
        php_builtin_reflection("is_string", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("is_scalar", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("strval", &[("value", Some("mixed"))], Some("string")),
        php_builtin_reflection("boolval", &[("value", Some("mixed"))], Some("bool")),
        php_builtin_reflection("intval", &[("value", Some("mixed"))], Some("int")),
        php_builtin_reflection("strtoupper", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection("strtolower", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection("ucwords", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection("strrev", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection("ucfirst", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection("lcfirst", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection("ord", &[("character", Some("string"))], Some("int")),
        php_builtin_reflection("str_rot13", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection(
            "str_increment",
            &[("string", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "str_decrement",
            &[("string", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection("hebrev", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection("soundex", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection(
            "similar_text",
            &[("string1", Some("string")), ("string2", Some("string"))],
            Some("int"),
        ),
        php_builtin_reflection(
            "wordwrap",
            &[
                ("string", Some("string")),
                ("width", Some("int")),
                ("break", Some("string")),
                ("cut_long_words", Some("bool")),
            ],
            Some("string"),
        ),
        php_builtin_reflection("chr", &[("codepoint", Some("int"))], Some("string")),
        php_builtin_reflection("decbin", &[("num", Some("int"))], Some("string")),
        php_builtin_reflection("dechex", &[("num", Some("int"))], Some("string")),
        php_builtin_reflection("decoct", &[("num", Some("int"))], Some("string")),
        php_builtin_reflection("crc32", &[("string", Some("string"))], Some("int")),
        php_builtin_reflection(
            "bindec",
            &[("binary_string", Some("string"))],
            Some("int|float"),
        ),
        php_builtin_reflection(
            "hexdec",
            &[("hex_string", Some("string"))],
            Some("int|float"),
        ),
        php_builtin_reflection(
            "octdec",
            &[("octal_string", Some("string"))],
            Some("int|float"),
        ),
        php_builtin_reflection(
            "base_convert",
            &[
                ("num", Some("string")),
                ("from_base", Some("int")),
                ("to_base", Some("int")),
            ],
            Some("string"),
        ),
        php_builtin_reflection("deg2rad", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("rad2deg", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("sin", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("cos", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("tan", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("asin", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("acos", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("atan", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection(
            "atan2",
            &[("y", Some("float")), ("x", Some("float"))],
            Some("float"),
        ),
        php_builtin_reflection(
            "intdiv",
            &[("num1", Some("int")), ("num2", Some("int"))],
            Some("int"),
        ),
        php_builtin_reflection(
            "max",
            &[("value", Some("mixed")), ("other", Some("mixed"))],
            Some("mixed"),
        ),
        php_builtin_reflection(
            "min",
            &[("value", Some("mixed")), ("other", Some("mixed"))],
            Some("mixed"),
        ),
        php_builtin_reflection("sinh", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("cosh", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("tanh", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("asinh", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("acosh", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("atanh", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection("ceil", &[("num", Some("int|float"))], Some("float")),
        php_builtin_reflection("floor", &[("num", Some("int|float"))], Some("float")),
        php_builtin_reflection(
            "round",
            &[("num", Some("int|float")), ("precision", Some("int"))],
            Some("float"),
        ),
        php_builtin_reflection(
            "number_format",
            &[
                ("num", Some("float")),
                ("decimals", Some("int")),
                ("decimal_separator", Some("?string")),
                ("thousands_separator", Some("?string")),
            ],
            Some("string"),
        ),
        php_builtin_reflection("sqrt", &[("num", Some("float"))], Some("float")),
        php_builtin_reflection(
            "hypot",
            &[("x", Some("float")), ("y", Some("float"))],
            Some("float"),
        ),
        php_builtin_reflection("pi", &[], Some("float")),
        php_builtin_reflection(
            "fmod",
            &[("num1", Some("float")), ("num2", Some("float"))],
            Some("float"),
        ),
        php_builtin_reflection("floatval", &[("value", Some("mixed"))], Some("float")),
        php_builtin_reflection("doubleval", &[("value", Some("mixed"))], Some("float")),
        php_builtin_reflection("bin2hex", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection(
            "md5",
            &[("string", Some("string")), ("binary", Some("bool"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "sha1",
            &[("string", Some("string")), ("binary", Some("bool"))],
            Some("string"),
        ),
        php_builtin_reflection("password_algos", &[], Some("array")),
        php_builtin_reflection(
            "password_get_info",
            &[("hash", Some("string"))],
            Some("array"),
        ),
        php_builtin_reflection(
            "password_hash",
            &[
                ("password", Some("string")),
                ("algo", Some("string|int|null")),
                ("options", Some("array")),
            ],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "password_needs_rehash",
            &[
                ("hash", Some("string")),
                ("algo", Some("string|int|null")),
                ("options", Some("array")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection(
            "password_verify",
            &[("password", Some("string")), ("hash", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "random_bytes",
            &[("length", Some("int"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "random_int",
            &[("min", Some("int")), ("max", Some("int"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "base64_encode",
            &[("string", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "convert_uuencode",
            &[("string", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "convert_uudecode",
            &[("string", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "base64_decode",
            &[("string", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "rawurlencode",
            &[("string", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "rawurldecode",
            &[("string", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection("urlencode", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection(
            "http_build_query",
            &[
                ("data", Some("array|object")),
                ("numeric_prefix", Some("string")),
                ("arg_separator", Some("?string")),
                ("encoding_type", Some("int")),
            ],
            Some("string"),
        ),
        php_builtin_reflection("urldecode", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection(
            "hex2bin",
            &[("string", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection("escapeshellarg", &[("arg", Some("string"))], Some("string")),
        php_builtin_reflection(
            "escapeshellcmd",
            &[("command", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "explode",
            &[
                ("separator", Some("string")),
                ("string", Some("string")),
                ("limit", Some("int")),
            ],
            Some("array"),
        ),
        php_builtin_reflection(
            "implode",
            &[("separator", Some("string")), ("array", Some("array"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "join",
            &[("separator", Some("string")), ("array", Some("array"))],
            Some("string"),
        ),
        php_builtin_reflection("chdir", &[("directory", Some("string"))], Some("bool")),
        php_builtin_reflection(
            "chmod",
            &[("filename", Some("string")), ("permissions", Some("int"))],
            Some("bool"),
        ),
        php_builtin_reflection("getcwd", &[], Some("string|false")),
        php_builtin_reflection(
            "clearstatcache",
            &[
                ("clear_realpath_cache", Some("bool")),
                ("filename", Some("?string")),
            ],
            Some("void"),
        ),
        php_builtin_reflection("file_exists", &[("filename", Some("string"))], Some("bool")),
        php_builtin_reflection(
            "fnmatch",
            &[("pattern", Some("string")), ("filename", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection("is_dir", &[("filename", Some("string"))], Some("bool")),
        php_builtin_reflection("is_file", &[("filename", Some("string"))], Some("bool")),
        php_builtin_reflection("is_link", &[("filename", Some("string"))], Some("bool")),
        php_builtin_reflection("is_readable", &[("filename", Some("string"))], Some("bool")),
        php_builtin_reflection("is_writable", &[("filename", Some("string"))], Some("bool")),
        php_builtin_reflection(
            "is_writeable",
            &[("filename", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "is_executable",
            &[("filename", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "is_uploaded_file",
            &[("filename", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "filesize",
            &[("filename", Some("string"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "fileatime",
            &[("filename", Some("string"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "filectime",
            &[("filename", Some("string"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "filemtime",
            &[("filename", Some("string"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "fileinode",
            &[("filename", Some("string"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "fileowner",
            &[("filename", Some("string"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "filegroup",
            &[("filename", Some("string"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "fileperms",
            &[("filename", Some("string"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "filetype",
            &[("filename", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "lstat",
            &[("filename", Some("string"))],
            Some("array|false"),
        ),
        php_builtin_reflection("stat", &[("filename", Some("string"))], Some("array|false")),
        php_builtin_reflection(
            "file_get_contents",
            &[
                ("filename", Some("string")),
                ("use_include_path", Some("bool")),
                ("context", Some("?resource")),
                ("offset", Some("int")),
                ("length", Some("?int")),
            ],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "file_put_contents",
            &[
                ("filename", Some("string")),
                ("data", Some("mixed")),
                ("flags", Some("int")),
                ("context", Some("?resource")),
            ],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "move_uploaded_file",
            &[("from", Some("string")), ("to", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "fopen",
            &[
                ("filename", Some("string")),
                ("mode", Some("string")),
                ("use_include_path", Some("bool")),
                ("context", Some("?resource")),
            ],
            Some("resource|false"),
        ),
        php_builtin_reflection(
            "fread",
            &[("stream", Some("resource")), ("length", Some("int"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "fgetc",
            &[("stream", Some("resource"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "fgets",
            &[("stream", Some("resource")), ("length", Some("?int"))],
            Some("string|false"),
        ),
        php_builtin_reflection("feof", &[("stream", Some("resource"))], Some("bool")),
        php_builtin_reflection("fflush", &[("stream", Some("resource"))], Some("bool")),
        php_builtin_reflection(
            "fwrite",
            &[
                ("stream", Some("resource")),
                ("data", Some("string")),
                ("length", Some("?int")),
            ],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "fputs",
            &[
                ("stream", Some("resource")),
                ("data", Some("string")),
                ("length", Some("?int")),
            ],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "glob",
            &[("pattern", Some("string")), ("flags", Some("int"))],
            Some("array|false"),
        ),
        php_builtin_reflection("fpassthru", &[("stream", Some("resource"))], Some("int")),
        php_builtin_reflection(
            "fstat",
            &[("stream", Some("resource"))],
            Some("array|false"),
        ),
        php_builtin_reflection("fclose", &[("stream", Some("resource"))], Some("bool")),
        php_builtin_reflection("fdatasync", &[("stream", Some("resource"))], Some("bool")),
        php_builtin_reflection("ftell", &[("stream", Some("resource"))], Some("int|false")),
        php_builtin_reflection(
            "fseek",
            &[("stream", Some("resource")), ("offset", Some("int"))],
            Some("int"),
        ),
        php_builtin_reflection("rewind", &[("stream", Some("resource"))], Some("bool")),
        php_builtin_reflection("fsync", &[("stream", Some("resource"))], Some("bool")),
        php_builtin_reflection(
            "ftruncate",
            &[("stream", Some("resource")), ("size", Some("int"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "stream_get_contents",
            &[
                ("stream", Some("resource")),
                ("length", Some("?int")),
                ("offset", Some("int")),
            ],
            Some("string|false"),
        ),
        php_builtin_reflection("tmpfile", &[], Some("resource|false")),
        php_builtin_reflection(
            "readfile",
            &[
                ("filename", Some("string")),
                ("use_include_path", Some("bool")),
                ("context", Some("?resource")),
            ],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "readlink",
            &[("path", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection("linkinfo", &[("path", Some("string"))], Some("int|false")),
        php_builtin_reflection(
            "link",
            &[("target", Some("string")), ("link", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "symlink",
            &[("target", Some("string")), ("link", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection("sys_get_temp_dir", &[], Some("string")),
        php_builtin_reflection(
            "tempnam",
            &[("directory", Some("string")), ("prefix", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "uniqid",
            &[("prefix", Some("string")), ("more_entropy", Some("bool"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "touch",
            &[
                ("filename", Some("string")),
                ("mtime", Some("?int")),
                ("atime", Some("?int")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection(
            "copy",
            &[
                ("from", Some("string")),
                ("to", Some("string")),
                ("context", Some("?resource")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection(
            "rename",
            &[
                ("from", Some("string")),
                ("to", Some("string")),
                ("context", Some("?resource")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection(
            "unlink",
            &[("filename", Some("string")), ("context", Some("?resource"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "mkdir",
            &[
                ("directory", Some("string")),
                ("permissions", Some("int")),
                ("recursive", Some("bool")),
                ("context", Some("?resource")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection(
            "rmdir",
            &[
                ("directory", Some("string")),
                ("context", Some("?resource")),
            ],
            Some("bool"),
        ),
        php_builtin_reflection(
            "realpath",
            &[("path", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection("realpath_cache_get", &[], Some("array")),
        php_builtin_reflection("realpath_cache_size", &[], Some("int")),
        php_builtin_reflection("trim", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection("ltrim", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection("rtrim", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection("chop", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection("addslashes", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection(
            "addcslashes",
            &[("string", Some("string")), ("characters", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "stripslashes",
            &[("string", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "stripcslashes",
            &[("string", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "quoted_printable_encode",
            &[("string", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "quoted_printable_decode",
            &[("string", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "htmlspecialchars",
            &[("string", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "htmlentities",
            &[("string", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "htmlspecialchars_decode",
            &[("string", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "html_entity_decode",
            &[("string", Some("string"))],
            Some("string"),
        ),
        php_builtin_reflection("strip_tags", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection(
            "nl2br",
            &[("string", Some("string")), ("use_xhtml", Some("bool"))],
            Some("string"),
        ),
        php_builtin_reflection("quotemeta", &[("string", Some("string"))], Some("string")),
        php_builtin_reflection(
            "str_contains",
            &[("haystack", Some("string")), ("needle", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "str_starts_with",
            &[("haystack", Some("string")), ("needle", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "str_ends_with",
            &[("haystack", Some("string")), ("needle", Some("string"))],
            Some("bool"),
        ),
        php_builtin_reflection(
            "str_replace",
            &[
                ("search", Some("array|string")),
                ("replace", Some("array|string")),
                ("subject", Some("string|array")),
                ("count", Some("int")),
            ],
            Some("string|array"),
        ),
        php_builtin_reflection(
            "str_ireplace",
            &[
                ("search", Some("array|string")),
                ("replace", Some("array|string")),
                ("subject", Some("string|array")),
                ("count", Some("int")),
            ],
            Some("string|array"),
        ),
        php_builtin_reflection(
            "strtr",
            &[
                ("string", Some("string")),
                ("from", Some("string")),
                ("to", Some("string")),
            ],
            Some("string"),
        ),
        php_builtin_reflection(
            "str_repeat",
            &[("string", Some("string")), ("times", Some("int"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "str_pad",
            &[
                ("string", Some("string")),
                ("length", Some("int")),
                ("pad_string", Some("string")),
                ("pad_type", Some("int")),
            ],
            Some("string"),
        ),
        php_builtin_reflection(
            "str_split",
            &[("string", Some("string")), ("length", Some("int"))],
            Some("array"),
        ),
        php_builtin_reflection("str_getcsv", &[("string", Some("string"))], Some("array")),
        php_builtin_reflection(
            "chunk_split",
            &[
                ("string", Some("string")),
                ("length", Some("int")),
                ("separator", Some("string")),
            ],
            Some("string"),
        ),
        php_builtin_reflection(
            "substr",
            &[("string", Some("string")), ("offset", Some("int"))],
            Some("string"),
        ),
        php_builtin_reflection(
            "strpos",
            &[("haystack", Some("string")), ("needle", Some("string"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "stripos",
            &[("haystack", Some("string")), ("needle", Some("string"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "strrpos",
            &[("haystack", Some("string")), ("needle", Some("string"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "strripos",
            &[("haystack", Some("string")), ("needle", Some("string"))],
            Some("int|false"),
        ),
        php_builtin_reflection(
            "strstr",
            &[("haystack", Some("string")), ("needle", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "strchr",
            &[("haystack", Some("string")), ("needle", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "stristr",
            &[("haystack", Some("string")), ("needle", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "strrchr",
            &[("haystack", Some("string")), ("needle", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "strpbrk",
            &[("string", Some("string")), ("characters", Some("string"))],
            Some("string|false"),
        ),
        php_builtin_reflection(
            "strspn",
            &[("string", Some("string")), ("characters", Some("string"))],
            Some("int"),
        ),
        php_builtin_reflection(
            "strcspn",
            &[("string", Some("string")), ("characters", Some("string"))],
            Some("int"),
        ),
        php_builtin_reflection(
            "substr_count",
            &[("haystack", Some("string")), ("needle", Some("string"))],
            Some("int"),
        ),
        php_builtin_reflection(
            "substr_replace",
            &[
                ("string", Some("string")),
                ("replace", Some("string")),
                ("offset", Some("int")),
                ("length", Some("int|null")),
            ],
            Some("string"),
        ),
        php_builtin_reflection(
            "substr_compare",
            &[
                ("haystack", Some("string")),
                ("needle", Some("string")),
                ("offset", Some("int")),
                ("length", Some("int|null")),
                ("case_insensitive", Some("bool")),
            ],
            Some("int"),
        ),
        php_builtin_reflection(
            "strcmp",
            &[("string1", Some("string")), ("string2", Some("string"))],
            Some("int"),
        ),
        php_builtin_reflection(
            "strcasecmp",
            &[("string1", Some("string")), ("string2", Some("string"))],
            Some("int"),
        ),
        php_builtin_reflection(
            "strnatcmp",
            &[("string1", Some("string")), ("string2", Some("string"))],
            Some("int"),
        ),
        php_builtin_reflection(
            "strnatcasecmp",
            &[("string1", Some("string")), ("string2", Some("string"))],
            Some("int"),
        ),
        php_builtin_reflection(
            "levenshtein",
            &[
                ("string1", Some("string")),
                ("string2", Some("string")),
                ("insertion_cost", Some("int")),
                ("replacement_cost", Some("int")),
                ("deletion_cost", Some("int")),
            ],
            Some("int"),
        ),
        php_builtin_reflection(
            "strncmp",
            &[
                ("string1", Some("string")),
                ("string2", Some("string")),
                ("length", Some("int")),
            ],
            Some("int"),
        ),
        php_builtin_reflection(
            "strncasecmp",
            &[
                ("string1", Some("string")),
                ("string2", Some("string")),
                ("length", Some("int")),
            ],
            Some("int"),
        ),
    ]
    .into()
}

fn php_builtin_reflection(
    name: &str,
    params: &[(&str, Option<&str>)],
    return_type: Option<&str>,
) -> FunctionReflection {
    FunctionReflection {
        name: name.to_string(),
        qualified_name: name.to_string(),
        source: FunctionSource::PhpBuiltin,
        params: params
            .iter()
            .map(|(name, ty)| ParamReflection {
                name: (*name).to_string(),
                ty: ty.map(str::to_string),
            })
            .collect(),
        return_type: return_type.map(str::to_string),
        is_intrinsic: true,
    }
}
