[package]
name = "echo_mir"
version = "0.0.1"
edition = "2024"
license.workspace = true
publish = false

[dependencies]
echo_ast = { path = "../echo_ast" }
echo_diagnostics = { path = "../echo_diagnostics" }
echo_hir = { path = "../echo_hir" }
echo_semantics = { path = "../echo_semantics" }
echo_source = { path = "../echo_source" }
echo_std = { path = "../echo_std" }
echo_syntax = { path = "../echo_syntax" }
