pub mod grammar {
    pub mod tree_sitter {
        use std::fs;
        use std::io;
        use std::path::Path;

        use echo_syntax::{SyntaxRuleKind, keywords, operators, rules, tree_sitter};

        pub fn generate(output: &Path) -> io::Result<()> {
            fs::create_dir_all(output.join("queries"))?;
            fs::write(output.join("grammar.js"), grammar_js())?;
            fs::write(output.join("package.json"), package_json())?;
            fs::write(output.join("tree-sitter.json"), tree_sitter_json())?;
            fs::write(
                output.join("queries").join("highlights.scm"),
                highlights_scm(),
            )?;
            fs::write(output.join("queries").join("folds.scm"), folds_scm())?;
            fs::write(output.join("queries").join("tags.scm"), tags_scm())?;
            Ok(())
        }

        fn grammar_js() -> String {
            let keyword_choices = keyword_choices();
            let operator_precedence = operator_precedence();
            let grammar_rules = grammar_rules(&keyword_choices);

            format!(
                r##"// Generated by `xo tools grammar tree-sitter`.
// Source facts live in crates/echo_syntax.

const PREC = {{
{operator_precedence}
  statement: 1,
}};

module.exports = grammar({{
  name: "echo",

  extras: $ => [
    /\s/,
    $.comment,
  ],

  word: $ => $.identifier,

  conflicts: $ => [
    [$.facet_declaration, $.module_path],
  ],

  rules: {{
{grammar_rules}
  }},
}});

function commaSep(rule) {{
  return optional(commaSep1(rule));
}}

function commaSep1(rule) {{
  return seq(rule, repeat(seq(",", rule)), optional(","));
}}
"##
            )
        }

        fn grammar_rules(keyword_choices: &str) -> String {
            tree_sitter::RULES
                .iter()
                .map(|rule| {
                    let body = if rule.body == "__ECHO_KEYWORD_CHOICE__" {
                        format!("choice(\n{keyword_choices}\n    )")
                    } else {
                        rule.body.to_string()
                    };

                    let parameter = if matches!(
                        rule.name,
                        "php_open_tag"
                            | "boolean"
                            | "null"
                            | "variable"
                            | "identifier"
                            | "string"
                            | "number"
                            | "comment"
                            | "terminator"
                            | "keyword"
                    ) {
                        "_"
                    } else {
                        "$"
                    };

                    format!("    {}: {} => {},", rule.name, parameter, body)
                })
                .collect::<Vec<_>>()
                .join("\n\n")
        }

        fn package_json() -> String {
            r#"{
  "name": "tree-sitter-echo",
  "version": "0.0.0",
  "description": "Echo grammar for tree-sitter",
  "main": "bindings/node",
  "keywords": [
    "parser",
    "tree-sitter",
    "echo"
  ],
  "license": "MIT",
  "tree-sitter": [
    {
      "scope": "source.echo",
      "file-types": [
        "echo"
      ]
    }
  ],
  "devDependencies": {
    "tree-sitter-cli": "^0.23.0"
  }
}
"#
            .to_string()
        }

        fn tree_sitter_json() -> String {
            r#"{
  "grammars": [
    {
      "name": "echo",
      "scope": "source.echo",
      "path": ".",
      "file-types": [
        "echo"
      ]
    }
  ],
  "metadata": {
    "version": "0.0.0",
    "license": "MIT",
    "description": "Echo grammar for tree-sitter",
    "authors": [
      {
        "name": "Modoterra"
      }
    ]
  }
}
"#
            .to_string()
        }

        fn highlights_scm() -> String {
            let mut output = String::from(
                "; Generated by `xo tools grammar tree-sitter`.\n; Source facts live in crates/echo_syntax.\n\n",
            );
            let keyword_literals = highlight_keyword_literals();

            if !keyword_literals.is_empty() {
                output.push_str("[\n");
                output.push_str(&keyword_literals.join("\n"));
                output.push_str("\n] @keyword\n\n");
            }

            output.push_str(
                r#"(comment) @comment
(string) @string
(number) @number
(boolean) @boolean
(null) @constant.builtin
(magic_constant) @constant.builtin
(variable) @variable

(function_declaration name: (identifier) @function)
(method_declaration name: (identifier) @function.method)
(class_declaration name: (identifier) @type)
(class_declaration superclass: (identifier) @type)
(class_declaration superclass: (dotted_name) @type)
(class_declaration superclass: (qualified_name) @type)
(type_declaration name: (identifier) @type)
(call_expression function: (identifier) @function)
(call_expression function: (dotted_name) @function)
(module_declaration path: (module_path) @namespace)
(namespace_declaration path: (qualified_name) @namespace)
"#,
            );

            output.push_str(
                r#"
(use_declaration path: (module_path) @namespace)
(use_declaration path: (qualified_name) @namespace)
"#,
            );

            output
        }

        fn highlight_keyword_literals() -> Vec<String> {
            keywords::ALL
                .iter()
                .filter(|keyword| {
                    let literal = format!("\"{}\"", keyword.text);
                    tree_sitter::RULES
                        .iter()
                        .filter(|rule| rule.name != "keyword")
                        .any(|rule| rule.body.contains(&literal))
                })
                .map(|keyword| format!("  \"{}\"", keyword.text))
                .collect()
        }

        fn folds_scm() -> String {
            let fold_rules = rules::ALL
                .iter()
                .filter(|rule| {
                    matches!(
                        rule.kind,
                        SyntaxRuleKind::Declaration | SyntaxRuleKind::Statement
                    ) && matches!(
                        rule.name,
                        "function_declaration"
                            | "class_declaration"
                            | "type_declaration"
                            | "if_statement"
                            | "loop_statement"
                    )
                })
                .map(|rule| format!("({}) @fold", rule.name))
                .collect::<Vec<_>>()
                .join("\n");

            format!(
                "; Generated by `xo tools grammar tree-sitter`.\n\n(block) @fold\n(class_body) @fold\n{fold_rules}\n"
            )
        }

        fn tags_scm() -> String {
            r#"; Generated by `xo tools grammar tree-sitter`.

(function_declaration
  name: (identifier) @name) @definition.function

(method_declaration
  name: (identifier) @name) @definition.method

(class_declaration
  name: (identifier) @name) @definition.class

(type_declaration
  name: (identifier) @name) @definition.type
"#
            .to_string()
        }

        fn keyword_choices() -> String {
            keywords::ALL
                .iter()
                .map(|keyword| format!("      \"{}\"", keyword.text))
                .collect::<Vec<_>>()
                .join(",\n")
        }

        fn operator_precedence() -> String {
            operators::ALL
                .iter()
                .map(|operator| format!("  {}: {},", operator.name, operator.precedence))
                .collect::<Vec<_>>()
                .join("\n")
        }
    }
}
